// SAT Reading & Writing grammar questions.
// "______" marks the blank; every choice replaces exactly that blank.
// `answer` is the index of the correct choice (choices are shuffled on screen).
// Domains follow the College Board's names for the digital SAT.
(function () {
  const B = "Boundaries";
  const F = "Form, Structure, and Sense";
  const T = "Transitions";

  window.BB_DOMAINS = [
    { id: B, short: "Boundaries" },
    { id: F, short: "Form & Sense" },
    { id: T, short: "Transitions" },
  ];

  window.BB_QUESTIONS = [
    // ---------- Boundaries ----------
    {
      id: "b01", domain: B, skill: "Run-on sentences",
      text: "{A} spent the entire summer working on ______ September, even the harshest critics admitted that the effort had paid off.",
      choices: ["{CRAFT}. By", "{CRAFT}, by", "{CRAFT} by", "{CRAFT} by,"],
      answer: 0,
      why: "Both halves are independent clauses. A period separates them correctly. A comma alone makes a comma splice, and no punctuation makes a run-on.",
    },
    {
      id: "b02", domain: B, skill: "Semicolons",
      text: "{A} had trained for this moment for ______ nothing about {EVENT} felt unfamiliar.",
      choices: ["years; as a result,", "years, as a result,", "years as a result,", "years, as a result"],
      answer: 0,
      why: "\"As a result\" starts a new independent clause, so it needs a semicolon (or period) before it and a comma after it.",
    },
    {
      id: "b03", domain: B, skill: "Colons",
      text: "{B} packed only three things for the ______ a notebook, a phone charger, and a lucky wristband.",
      choices: ["trip:", "trip;", "trip, including:", "trip, they were"],
      answer: 0,
      why: "A colon introduces a list after a complete independent clause. A semicolon can't introduce a list, and a colon shouldn't follow \"including.\"",
    },
    {
      id: "b04", domain: B, skill: "Dashes",
      text: "{B}'s coach—a former champion who rarely handed out ______ called the performance \"nearly flawless.\"",
      choices: ["compliments—", "compliments,", "compliments;", "compliments"],
      answer: 0,
      why: "The extra information opens with a dash, so it has to close with a dash. Mixing a dash with a comma is not allowed.",
    },
    {
      id: "b05", domain: B, skill: "Nonessential elements",
      text: "{C}, who had never lost a match at ______ the final with total confidence.",
      choices: ["home, entered", "home entered", "home; entered", "home—entered"],
      answer: 0,
      why: "The clause \"who had never lost a match at home\" opens with a comma, so it must close with a comma before the main verb \"entered.\"",
    },
    {
      id: "b06", domain: B, skill: "Essential elements",
      text: "Longtime rivals ______ met again in the final round, and the crowd could barely contain its excitement.",
      choices: ["{A} and {B}", "{A}, and {B},", "{A} and {B},", ", {A} and {B},"],
      answer: 0,
      why: "The names identify which rivals, so they are essential and take no commas. A comma also can't separate a subject from its verb.",
    },
    {
      id: "b07", domain: B, skill: "Items in a series",
      text: "{A}'s summer tour stopped in three cities: Lisbon, ______ Madrid, Spain; and Paris, France.",
      choices: ["Portugal;", "Portugal,", "Portugal:", "Portugal"],
      answer: 0,
      why: "When list items already contain commas (city, country), semicolons separate the items. The later items use semicolons too.",
    },
    {
      id: "b08", domain: B, skill: "Conjunctive adverbs",
      text: "{B} hoped for a week of ______ the schedule had other plans.",
      choices: ["rest; however,", "rest, however,", "rest; however", "rest however,"],
      answer: 0,
      why: "\"However\" joins two independent clauses here. Use a semicolon before it and a comma after it.",
    },
    {
      id: "b09", domain: B, skill: "End punctuation",
      text: "Before {EVENT}, {A} quietly wondered whether the new plan would ______",
      choices: ["work.", "work?", "work?.", "work;"],
      answer: 0,
      why: "This is an indirect question: it reports what someone wondered. Indirect questions end with a period, not a question mark.",
    },
    {
      id: "b10", domain: B, skill: "Introductory clauses",
      text: "Because {A} had never seen snow ______ winter trip felt like a real adventure.",
      choices: ["before, the", "before the", "before; the", "before: the"],
      answer: 0,
      why: "A dependent clause that begins a sentence (\"Because...\") is followed by a comma. A semicolon or colon needs an independent clause before it.",
    },
    {
      id: "b11", domain: B, skill: "Colons",
      text: "{C} had exactly one goal for ______ stay calm no matter what happened.",
      choices: ["{EVENT}: to", "{EVENT}; to", "{EVENT}. To", "{EVENT} to"],
      answer: 0,
      why: "The colon follows a complete clause and introduces what the goal was. \"To stay calm...\" isn't a complete sentence, so a semicolon or period won't work.",
    },
    {
      id: "b12", domain: B, skill: "Subject–verb commas",
      text: "The notes that {A} scribbled in the margins of every ______ more useful than the textbook itself.",
      choices: ["chapter were", "chapter, were", "chapter; were", "chapter—were"],
      answer: 0,
      why: "The subject \"The notes that...chapter\" leads straight into its verb \"were.\" No punctuation separates a subject from its verb.",
    },
    {
      id: "b13", domain: B, skill: "Run-on sentences",
      text: "The crowd at {PLACE} went completely ______ was about to attempt something no one had seen before.",
      choices: ["silent; {B}", "silent, {B}", "silent {B}", "silent, and, {B}"],
      answer: 0,
      why: "Two independent clauses can be joined by a semicolon. A comma alone is a splice, and no punctuation is a run-on.",
    },

    // ---------- Form, Structure, and Sense ----------
    {
      id: "f01", domain: F, skill: "Plural possessives",
      text: "Both of the ______ jerseys were signed by {A} after the game.",
      choices: ["twins'", "twin's", "twins", "twins's"],
      answer: 0,
      why: "\"Both\" means more than one twin, and the jerseys belong to them. The plural possessive of \"twins\" is \"twins'.\"",
    },
    {
      id: "f02", domain: F, skill: "Its vs. it's",
      text: "The committee announced that ______ new captain would be {C}.",
      choices: ["its", "it's", "their", "its'"],
      answer: 0,
      why: "A committee is a singular noun, and its possessive is \"its.\" \"It's\" means \"it is,\" and \"its'\" is never correct.",
    },
    {
      id: "f03", domain: F, skill: "Singular possessives",
      text: "Everyone admired ______ determination to finish despite the pouring rain.",
      choices: ["{A}'s", "{A}s", "{A}s'", "{A}"],
      answer: 0,
      why: "The determination belongs to one person, so it takes an apostrophe plus s.",
    },
    {
      id: "f04", domain: F, skill: "Plurals",
      text: "By the end of the year, {B} had broken three long-standing ______",
      choices: ["records.", "record's.", "records'.", "record."],
      answer: 0,
      why: "Nothing belongs to the records, so they need a plain plural with no apostrophe.",
    },
    {
      id: "f05", domain: F, skill: "Subject–verb agreement",
      text: "The collection of trophies in {A_his} display cabinet ______ grown every single year.",
      choices: ["has", "have", "are", "were"],
      answer: 0,
      why: "The subject is \"collection\" (singular), not \"trophies.\" A singular subject takes \"has.\"",
    },
    {
      id: "f06", domain: F, skill: "Subject–verb agreement",
      text: "{A} and {B} ______ been friends since their very first day at {PLACE}.",
      choices: ["have", "has", "is", "was"],
      answer: 0,
      why: "Two subjects joined by \"and\" make a plural subject, which takes \"have.\"",
    },
    {
      id: "f07", domain: F, skill: "Subject–verb agreement",
      text: "Neither {A} nor {B}'s teammates ______ ready for the surprise announcement.",
      choices: ["were", "was", "is", "has been"],
      answer: 0,
      why: "With \"neither...nor,\" the verb agrees with the closer subject. \"Teammates\" is plural, so the verb is \"were.\"",
    },
    {
      id: "f08", domain: F, skill: "Subject–verb agreement",
      text: "Each of the practice drills that {C} designed ______ a specific weakness.",
      choices: ["targets", "target", "are targeting", "have targeted"],
      answer: 0,
      why: "The subject is \"Each,\" which is singular. \"Drills\" sits inside a prepositional phrase and doesn't control the verb.",
    },
    {
      id: "f09", domain: F, skill: "Subject–verb agreement",
      text: "At the back of the room ______ a stack of old notebooks that once belonged to {A}.",
      choices: ["sits", "sit", "are sitting", "have sat"],
      answer: 0,
      why: "The sentence is inverted. The real subject is \"a stack,\" which is singular, so the verb is \"sits.\"",
    },
    {
      id: "f10", domain: F, skill: "Subject–verb agreement",
      text: "{A}, along with {B} and {C}, ______ planning a surprise for the coach.",
      choices: ["is", "are", "were", "have been"],
      answer: 0,
      why: "Phrases like \"along with\" don't make a subject plural. The subject is still just {A}, so use \"is.\"",
    },
    {
      id: "f11", domain: F, skill: "Subject–verb agreement",
      text: "There ______ several reasons why {B} decided to switch positions this season.",
      choices: ["were", "was", "is", "has been"],
      answer: 0,
      why: "In \"there\" sentences, the subject comes after the verb. \"Several reasons\" is plural, so use \"were.\"",
    },
    {
      id: "f12", domain: F, skill: "Pronoun–antecedent agreement",
      text: "When {A} and {B} finished the project, the teacher praised ______ for their careful research.",
      choices: ["them", "him", "her", "us"],
      answer: 0,
      why: "The pronoun refers to two people, {A} and {B}, so it has to be plural: \"them.\"",
    },
    {
      id: "f13", domain: F, skill: "Pronoun–antecedent agreement",
      text: "The fans waved ______ scarves as {A} walked out onto the field.",
      choices: ["their", "its", "his or her", "there"],
      answer: 0,
      why: "\"Fans\" is plural, so the possessive pronoun is \"their.\" \"There\" refers to a place.",
    },
    {
      id: "f14", domain: F, skill: "Pronoun case",
      text: "The coach chose {B} and ______ to lead the warm-up before {EVENT}.",
      choices: ["me", "I", "myself", "mine"],
      answer: 0,
      why: "The pronoun is an object of \"chose.\" Drop \"{B} and\" to test it: \"chose me,\" not \"chose I.\"",
    },
    {
      id: "f15", domain: F, skill: "Relative pronouns",
      text: "The mentor to ______ {A} owed the most was a retired teacher from the neighborhood.",
      choices: ["whom", "who", "which", "what"],
      answer: 0,
      why: "After a preposition (\"to\"), use the object form \"whom\" for a person.",
    },
    {
      id: "f16", domain: F, skill: "Relative pronouns",
      text: "{A} is the kind of teammate ______ encouragement makes everyone around {A_him} better.",
      choices: ["whose", "who's", "who is", "which"],
      answer: 0,
      why: "The encouragement belongs to the teammate, so you need the possessive \"whose.\" \"Who's\" means \"who is.\"",
    },
    {
      id: "f17", domain: F, skill: "Verb tense",
      text: "Last spring, {A} ______ a school record that had stood for twenty years.",
      choices: ["broke", "breaks", "will break", "has been breaking"],
      answer: 0,
      why: "\"Last spring\" puts the action in the finished past, so use the simple past \"broke.\"",
    },
    {
      id: "f18", domain: F, skill: "Verb tense",
      text: "By the time the bus arrived, {B} ______ already finished the entire reading assignment.",
      choices: ["had", "has", "have", "will have"],
      answer: 0,
      why: "The finishing happened before another past event (the bus arriving), which calls for the past perfect \"had finished.\"",
    },
    {
      id: "f19", domain: F, skill: "Verb forms",
      text: "{C} would have ______ the race if the storm had not delayed the start.",
      choices: ["run", "ran", "runned", "running"],
      answer: 0,
      why: "After \"would have,\" use the past participle. The past participle of \"run\" is \"run.\"",
    },
    {
      id: "f20", domain: F, skill: "Finite verbs",
      text: "The notebook that {A} carried to every practice ______ filled with sketches, formulas, and reminders.",
      choices: ["was", "being", "having been", "to be"],
      answer: 0,
      why: "The sentence needs a main verb. \"Being,\" \"having been,\" and \"to be\" can't act as a main verb, which would leave a fragment.",
    },
    {
      id: "f21", domain: F, skill: "Modifiers",
      text: "Exhausted after hours of practice, ______",
      choices: [
        "{A} finally sat down to eat dinner.",
        "dinner was finally eaten by {A}.",
        "the couch was where {A} finally collapsed.",
        "{A_his} dinner was finally ready.",
      ],
      answer: 0,
      why: "The opening phrase describes whoever was exhausted. That person, {A}, has to come right after the comma.",
    },
    {
      id: "f22", domain: F, skill: "Modifiers",
      text: "Known for staying calm under pressure, ______",
      choices: [
        "{A} was chosen to take the final shot.",
        "the coach chose {A} to take the final shot.",
        "the final shot was given to {A}.",
        "{A_his} coach picked {A_him} for the final shot.",
      ],
      answer: 0,
      why: "The person known for staying calm is {A}, so {A} must be the subject right after the modifier.",
    },
    {
      id: "f23", domain: F, skill: "Parallel structure",
      text: "{A}'s morning routine includes stretching, lifting weights, and ______",
      choices: ["running sprints.", "to run sprints.", "sprints are run.", "{A} runs sprints."],
      answer: 0,
      why: "Items in a list should share the same form. \"Stretching\" and \"lifting\" are -ing words, so the last item is \"running.\"",
    },
    {
      id: "f24", domain: F, skill: "Logical comparisons",
      text: "{B}'s score on the practice test was higher than ______",
      choices: ["{C}'s.", "{C}.", "{C}s.", "{C}s'."],
      answer: 0,
      why: "Compare a score to a score, not a score to a person. \"{C}'s\" means \"{C}'s score.\"",
    },
    {
      id: "f25", domain: F, skill: "Plural possessives",
      text: "All of the ______ lockers were covered with posters of {A}.",
      choices: ["players'", "player's", "players", "players's"],
      answer: 0,
      why: "The lockers belong to many players, so use the plural possessive \"players'.\"",
    },

    // ---------- Transitions ----------
    {
      id: "t01", domain: T, skill: "Contrast",
      text: "{A} missed the first three practices of the season. ______ {A} was named a starter for the opening game.",
      choices: ["Nevertheless,", "Therefore,", "For example,", "Similarly,"],
      answer: 0,
      why: "Being named a starter is surprising after missing practice. \"Nevertheless\" signals that contrast.",
    },
    {
      id: "t02", domain: T, skill: "Cause and effect",
      text: "{B} studied the playbook every night for a month. ______ {B} knew every play by heart before the first game.",
      choices: ["As a result,", "However,", "Instead,", "In contrast,"],
      answer: 0,
      why: "Knowing every play is the result of studying every night, so a cause-and-effect transition fits.",
    },
    {
      id: "t03", domain: T, skill: "Examples",
      text: "{C} has several rituals before {EVENT}. ______ {C} always listens to the same song while warming up.",
      choices: ["For instance,", "Nonetheless,", "Meanwhile,", "In other words,"],
      answer: 0,
      why: "The second sentence gives one specific ritual, which is an example of the first sentence's claim.",
    },
    {
      id: "t04", domain: T, skill: "Contrast",
      text: "{A} does {A_his} best practicing alone in the early morning. {B}, ______ prefers a noisy gym full of teammates.",
      choices: ["by contrast,", "similarly,", "therefore,", "for example,"],
      answer: 0,
      why: "The two people have opposite habits, so the transition should show contrast.",
    },
    {
      id: "t05", domain: T, skill: "Sequence",
      text: "First, {A} reviews every mistake from the last game. ______ {A} repeats those exact situations until the right move feels automatic.",
      choices: ["Next,", "In conclusion,", "However,", "For instance,"],
      answer: 0,
      why: "\"First\" sets up a sequence of steps, and \"Next\" continues it.",
    },
    {
      id: "t06", domain: T, skill: "Contrast",
      text: "Critics predicted that {B} would struggle at {EVENT}. ______ {B} delivered the best performance of {B_his} career.",
      choices: ["Instead,", "Additionally,", "Similarly,", "Consequently,"],
      answer: 0,
      why: "What happened was the opposite of the prediction. \"Instead\" shows that one outcome replaced the expected one.",
    },
    {
      id: "t07", domain: T, skill: "Addition",
      text: "{C} became the youngest person ever to win the award. ______ {C} donated the prize money to a local after-school program.",
      choices: ["Moreover,", "However,", "Regardless,", "Otherwise,"],
      answer: 0,
      why: "The second sentence adds another impressive fact on top of the first, so an addition transition fits.",
    },
    {
      id: "t08", domain: T, skill: "Restatement",
      text: "{A} refuses to leave {PLACE} until every detail is perfect. ______ {A} is a perfectionist.",
      choices: ["In other words,", "On the other hand,", "Afterward,", "For example,"],
      answer: 0,
      why: "The second sentence sums up the first in simpler terms, which is a restatement.",
    },
  ];
})();
