// Chapter 1: Independent Clause Connectors & Sentence Boundaries
(function () {
  const { Q } = window.ClauseBank;
  const SPLICE = "Comma splice: a comma alone can't join two independent clauses.";
  const RUNON = "Run-on: two independent clauses are fused with no punctuation at all.";
  window.ClauseBank.add({
    id: 1,
    short: "Clause Connectors",
    title: "Independent Clause Connectors & Sentence Boundaries",
    focus: "Join independent clauses (ICs) with a period, a semicolon, or a comma + FANBOYS.",
    rules: [
      "An independent clause (IC) has a subject and a verb and can stand alone as a sentence.",
      "Legal ways to join two ICs: IC. IC  ·  IC; IC  ·  IC, FANBOYS IC (for, and, nor, but, or, yet, so).",
      "Illegal: IC, IC (comma splice) and IC IC (run-on).",
      "Words like however, therefore and then are NOT FANBOYS: write IC; however, IC.",
      "A dependent clause (Because…, Although…) attaches to an IC with a comma when it comes first: DC, IC.",
      "One subject with two verbs (a compound predicate) needs no comma before \"and\".",
    ],
    questions: [
      Q("c1-01", "IC. IC", "In 2010, Ronaldo was scoring many goals in China when he noticed markings of red paint on the goal ______ the help of Pessi, he discovered that it was a piece of a jersey.",
        ["posts, with", "posts with", "posts so with", "posts. With"], 3,
        "Two independent clauses need a period, a semicolon, or a comma + FANBOYS between them.",
        [SPLICE + " \"Ronaldo was scoring…\" and \"he discovered…\" are both ICs; the phrase \"with the help of Pessi\" doesn't change that.",
          RUNON + " The first IC runs straight into the second.",
          "\"So\" is a FANBOYS conjunction, but it needs a comma before it, and the help of Pessi isn't a result of the paint.",
          "Correct. The period ends the first IC, and \"With the help of Pessi\" opens the second sentence."]),
      Q("c1-02", "IC; IC", "At the regional meet, Simone Biles landed her vault with a flawless ______ judges awarded her the highest score of the night.",
        ["landing; the", "landing, the", "landing the", "landing, so, the"], 0,
        "A semicolon can join two closely related independent clauses.",
        ["Correct. \"Simone Biles landed…\" and \"the judges awarded…\" are both ICs, and a semicolon joins them.",
          SPLICE,
          RUNON,
          "\"So\" can join ICs, but never with a comma after it: write \", so the\"."]),
      Q("c1-03", "IC, FANBOYS IC", "Hermione Granger had read every book in the library's restricted ______ she still could not find the spell the professor had described.",
        ["section, but", "section but", "section, however", "section, she"], 0,
        "IC, FANBOYS IC: a comma plus a coordinating conjunction joins two independent clauses.",
        ["Correct. A comma + \"but\" joins the two ICs and shows the contrast.",
          "Two ICs joined by \"but\" need a comma before the conjunction.",
          "\"However\" isn't a FANBOYS word; with only a comma, this is a comma splice.",
          SPLICE]),
      Q("c1-04", "IC. IC", "Marine biologist Dr. Lena Ortiz tagged forty sea turtles off the coast of Costa ______ weeks, data from the trackers revealed a migration route no one had ever mapped.",
        ["Rica. Within", "Rica, within", "Rica within", "Rica, within the"], 0,
        "A period can separate two independent clauses.",
        ["Correct. The first IC ends with a period, and \"Within weeks, data… revealed\" is a new sentence.",
          SPLICE,
          RUNON,
          "Adding \"the\" doesn't fix the comma splice, and \"within the weeks\" is unidiomatic."]),
      Q("c1-05", "DC, IC", "Because Spider-Man had stayed up all night patrolling the ______ he nearly slept through his chemistry exam.",
        ["city,", "city;", "city.", "city, and"], 0,
        "DC, IC: a dependent clause that comes first is followed by a comma.",
        ["Correct. \"Because… city\" is a dependent clause, so a comma connects it to the IC.",
          "A semicolon needs an IC on both sides; \"Because… city\" is dependent.",
          "A period would leave \"Because… city\" as a fragment.",
          "\"Because…, and he nearly slept…\" uses two connectors; drop the \"and\"."]),
      Q("c1-06", "IC DC", "LeBron James practiced free throws for two hours after the ______ he had missed three in the fourth quarter.",
        ["game because", "game. Because", "game; because", "game, and because"], 0,
        "IC DC: when the dependent clause comes second, no punctuation is needed.",
        ["Correct. \"Because he had missed three…\" is a dependent clause that finishes the IC.",
          "A period would make \"Because he had missed…\" a fragment.",
          "A semicolon needs an IC after it; \"because…\" is dependent.",
          "\"And\" needs another IC after it, but \"because he had missed…\" is dependent."]),
      Q("c1-07", "IC; however, IC", "The Wright brothers' first flight lasted only twelve ______ it changed the course of transportation history.",
        ["seconds; however,", "seconds, however,", "seconds however", "seconds, however"], 0,
        "Conjunctive adverbs (however, therefore, nevertheless) need IC; however, IC.",
        ["Correct. The semicolon joins the ICs, and the comma sets off \"however.\"",
          SPLICE + " \"However\" is not a FANBOYS word.",
          RUNON,
          SPLICE + " It's also missing the comma after \"however.\""]),
      Q("c1-08", "IC, FANBOYS IC", "Beyoncé rehearsed the choreography for six ______ the opening night ran without a single misstep.",
        ["months, so", "months so", "months, therefore", "months therefore"], 0,
        "IC, so IC: a comma + \"so\" shows a result between two ICs.",
        ["Correct. A comma + \"so\" joins the ICs and shows the result of rehearsing.",
          "Two ICs joined by \"so\" need a comma before it.",
          "\"Therefore\" can't join ICs after only a comma; use \"; therefore,\".",
          RUNON]),
      Q("c1-09", "One IC: no split", "The archive at the city museum holds letters ______ Frida Kahlo wrote to friends during her years in Mexico City.",
        ["that", "; that", ". That", ", that"], 0,
        "Don't split a single independent clause with a semicolon or period.",
        ["Correct. \"That Frida Kahlo wrote…\" is an essential clause identifying which letters, so no punctuation.",
          "A semicolon needs an IC on both sides; \"that Frida Kahlo wrote…\" isn't one.",
          "A period would leave \"That Frida Kahlo wrote…\" as a fragment.",
          "An essential \"that\" clause never takes a comma."]),
      Q("c1-10", "IC, FANBOYS IC", "Goku trained under gravity ten times stronger than ______ he wanted to be ready for the coming tournament.",
        ["Earth's, for", "Earth's for", "Earth's, he", "Earth's he"], 0,
        "\"For\" is a FANBOYS conjunction meaning \"because\": IC, for IC.",
        ["Correct. A comma + \"for\" joins the ICs and gives the reason.",
          "Two ICs joined by \"for\" need a comma before it.",
          SPLICE,
          RUNON]),
      Q("c1-11", "IC; then IC", "Taylor Swift wrote the bridge of the song on a hotel ______ she recorded a rough demo on her phone that same night.",
        ["notepad; then", "notepad, then", "notepad then", "notepad, then,"], 0,
        "\"Then\" is not a FANBOYS conjunction, so two ICs need a semicolon (or a period) before it.",
        ["Correct. The semicolon joins the two ICs; \"then\" starts the second.",
          SPLICE,
          RUNON,
          SPLICE + " The extra comma after \"then\" doesn't help."]),
      Q("c1-12", "IC, and IC", "Marie Curie's notebooks are still radioactive ______ researchers who study them must sign a waiver and wear protective gear.",
        ["today, and", "today and", "today, which", "today, so,"], 0,
        "IC, and IC: a comma before the FANBOYS conjunction joins two ICs.",
        ["Correct. A comma + \"and\" joins the two ICs.",
          "Two ICs joined by \"and\" need a comma before the conjunction.",
          "\"Which researchers who study them must sign…\" isn't a grammatical clause.",
          "There is never a comma after \"so\" when it joins clauses."]),
      Q("c1-13", "DC, IC", "Although the Mars rover's wheels were badly ______ engineers on Earth found a way to keep it driving for another year.",
        ["damaged,", "damaged.", "damaged;", "damaged, but"], 0,
        "DC, IC: an introductory dependent clause takes a comma, and only one connector.",
        ["Correct. \"Although… damaged\" is dependent, so a comma links it to the IC.",
          "A period would leave \"Although… damaged\" as a fragment.",
          "A semicolon needs an IC before it; \"Although…\" is dependent.",
          "\"Although\" and \"but\" both connect; using both is redundant."]),
      Q("c1-14", "IC, FANBOYS IC", "Shrek preferred the quiet of his ______ the steady stream of fairy-tale visitors made that quiet hard to find.",
        ["swamp, yet", "swamp yet", "swamp, however", "swamp; yet,"], 0,
        "IC, yet IC: \"yet\" is a FANBOYS word showing contrast.",
        ["Correct. A comma + \"yet\" joins the ICs and signals the contrast.",
          "Two ICs joined by \"yet\" need a comma before it.",
          SPLICE + " \"However\" isn't a FANBOYS word.",
          "No comma follows a FANBOYS conjunction; \"; yet,\" is incorrect."]),
      Q("c1-15", "IC. IC", "Mathematician Katherine Johnson checked the orbital calculations by ______ the astronauts trusted her numbers more than the computer's.",
        ["hand. Famously,", "hand, famously,", "hand famously,", "hand, famously"], 0,
        "A period separates two ICs; an introductory word can then start the new sentence.",
        ["Correct. The period ends the first IC; \"Famously, the astronauts trusted…\" is a complete sentence.",
          SPLICE,
          RUNON,
          SPLICE]),
      Q("c1-16", "IC, noun phrase", "The orchestra rehearsed in the old train ______ a converted station with surprisingly rich acoustics.",
        ["depot,", "depot;", "depot.", "depot, it was"], 0,
        "A semicolon needs an IC on both sides; a descriptive noun phrase after an IC takes a comma.",
        ["Correct. \"A converted station…\" renames the depot, so a comma attaches it.",
          "\"A converted station…\" isn't an IC, so a semicolon can't come before it.",
          "A period would leave \"A converted station…\" as a fragment.",
          SPLICE + " \"It was a converted station\" is an IC."]),
      Q("c1-17", "IC, FANBOYS IC", "Serena Williams won the first set ______ her opponent rallied to take the second.",
        ["easily, but", "easily but", "easily, however", "easily; but,"], 0,
        "IC, but IC: a comma + FANBOYS joins two contrasting ICs.",
        ["Correct. A comma + \"but\" joins the ICs and shows the contrast.",
          "Two ICs joined by \"but\" need a comma before it.",
          SPLICE + " \"However\" isn't a FANBOYS word.",
          "No comma follows \"but\", and a semicolon + \"but\" is nonstandard."]),
      Q("c1-18", "IC; IC", "The new library app tracks every book a student ______ it also recommends titles based on past checkouts.",
        ["borrows;", "borrows,", "borrows", "borrows and,"], 0,
        "A semicolon joins two related ICs.",
        ["Correct. Both \"The new library app tracks…\" and \"it also recommends…\" are ICs.",
          SPLICE,
          RUNON,
          "The comma belongs before \"and\", not after it."]),
      Q("c1-19", "Compound predicate", "Elsa sealed the castle gates ______ walked alone into the frozen mountains.",
        ["and", "; and", ", she", ". And"], 0,
        "One subject + two verbs (a compound predicate) needs no comma before \"and\".",
        ["Correct. Elsa did two things, so \"sealed… and walked…\" needs no punctuation.",
          "A semicolon needs an IC after it; \"and walked…\" has no subject.",
          SPLICE + " \"She walked alone…\" is an IC.",
          "\"And walked alone…\" has no subject, so it would be a fragment."]),
      Q("c1-20", "IC; IC", "Archaeologists in Egypt uncovered a sealed ______ it, they found jars of honey that were still edible.",
        ["tomb; inside", "tomb, inside", "tomb inside", "tomb, and, inside"], 0,
        "A semicolon can join two ICs.",
        ["Correct. \"Inside it, they found…\" is an IC, and the semicolon joins it to the first.",
          SPLICE,
          RUNON,
          "There's no comma after \"and\" when it joins clauses."]),
      Q("c1-21", "IC, FANBOYS IC", "Mario leapt across the final lava ______ Princess Peach was waiting at the end of the castle hall.",
        ["pit, and", "pit and", "pit,", "pit, which"], 0,
        "IC, and IC: a comma + FANBOYS joins two independent clauses.",
        ["Correct. A comma + \"and\" joins the two ICs.",
          "Two ICs joined by \"and\" need a comma before it.",
          SPLICE,
          "\"Which Princess Peach was waiting…\" is ungrammatical."]),
      Q("c1-22", "Compound predicate", "Researchers at the Coral Lab studied how clownfish choose their ______ found that the fish prefer anemones near the reef's edge.",
        ["anemones and", "anemones, and", "anemones;", "anemones. And"], 0,
        "One subject + two verbs (\"studied… and found…\") needs no comma.",
        ["Correct. \"Researchers… studied… and found…\" is a compound predicate.",
          "A comma before \"and\" is only needed when a full IC follows; \"found…\" has no subject.",
          "A semicolon needs an IC after it; \"found that…\" has no subject.",
          "\"And found that…\" would be a fragment."]),
      Q("c1-23", "IC. IC", "Bad Bunny released the album at ______ sunrise, it had broken the streaming platform's single-day record.",
        ["midnight. By", "midnight, by", "midnight by", "midnight, and, by"], 0,
        "A period separates two ICs.",
        ["Correct. The first IC ends at \"midnight\"; \"By sunrise, it had broken…\" is a new sentence.",
          SPLICE,
          RUNON,
          "The comma belongs before \"and\", not after it."]),
      Q("c1-24", "IC, and IC", "Sherlock Holmes examined the muddy boot print for several ______ then he announced that the visitor had come from the countryside.",
        ["minutes, and", "minutes and", "minutes,", "minutes then,"], 0,
        "IC, and IC: the comma + FANBOYS joins the ICs; \"then\" can follow.",
        ["Correct. A comma + \"and\" joins the two ICs.",
          "Two ICs joined by \"and\" need a comma before it.",
          SPLICE,
          "This creates \"minutes then, then he announced\", a run-on with a doubled word."]),
      Q("c1-25", "IC; nevertheless, IC", "The robotics team at Lincoln High lost its first two ______ the students rebuilt the arm and won the state finals.",
        ["matches; nevertheless,", "matches, nevertheless,", "matches nevertheless", "matches; nevertheless"], 0,
        "IC; nevertheless, IC: a semicolon before the conjunctive adverb, a comma after it.",
        ["Correct. The semicolon joins the ICs, and the comma follows \"nevertheless.\"",
          SPLICE,
          RUNON,
          "\"Nevertheless\" needs a comma after it when it opens the clause."]),
    ],
  });
})();
