// Chapter 2: Subject-Verb Agreement
(function () {
  const { Q } = window.ClauseBank;
  window.ClauseBank.add({
    id: 2,
    short: "Subject-Verb Agreement",
    title: "Subject-Verb Agreement",
    focus: "Find the real subject (skip prepositional and parenthetical phrases) and match the verb to it.",
    rules: [
      "Find the true subject: cross out prepositional phrases (of…, in…, with…) and parenthetical phrases (along with…, as well as…, set off by commas).",
      "Singular subject → singular verb (is, was, has, -s). Plural subject → plural verb (are, were, have, no -s).",
      "A and B → plural. Either/neither A or/nor B → match the subject closer to the verb.",
      "Each, every, one of, the number of → singular. A number of → plural.",
      "In inverted sentences (There is…, Among the… lies…), the subject comes AFTER the verb.",
      "3:1 shortcut: if three choices are singular and one is plural (or the reverse), the odd one out is usually the answer.",
    ],
    questions: [
      Q("c2-01", "Possessive subject", "What is the correct pronunciation of Voldemort? In the French-inspired nomenclature favored by author J.K. Rowling, the final letter -t is meant to be silent; as a result, the Dark Lord's name ______ pronounced “Voldemore.”",
        ["are", "have been", "are being", "is"], 3,
        "The subject is \"name\" (singular), so the verb must be singular.",
        ["\"Are\" is plural, but the subject \"name\" is singular.",
          "\"Have been\" is plural and adds an unneeded perfect tense.",
          "\"Are being\" is plural and awkward for a general fact.",
          "Correct. \"The Dark Lord's name is pronounced\": a singular subject with a singular verb, in the present tense for a general fact."]),
      Q("c2-02", "Prepositional phrase", "The collection of rare comic books in Stan's attic ______ worth more than his entire house.",
        ["is", "are", "were", "have been"], 0,
        "Cross out \"of rare comic books in Stan's attic\": the subject is \"collection\" (singular).",
        ["Correct. \"The collection… is\".",
          "\"Are\" agrees with \"books\", the trap inside the prepositional phrase.",
          "\"Were\" is plural.",
          "\"Have been\" is plural."]),
      Q("c2-03", "Each of", "Each of the players on Coach Carter's roster ______ required to keep a B average.",
        ["is", "are", "were", "have been"], 0,
        "\"Each\" is singular, even when followed by \"of the players.\"",
        ["Correct. \"Each… is required\".",
          "\"Are\" matches \"players\", but the subject is \"Each.\"",
          "\"Were\" is plural.",
          "\"Have been\" is plural."]),
      Q("c2-04", "Neither/nor", "Neither the drummer nor the guitarists ______ ready when the curtain rose.",
        ["were", "was", "is", "has been"], 0,
        "With neither/nor, the verb agrees with the closer subject: \"guitarists\" (plural).",
        ["Correct. \"The guitarists were\".",
          "\"Was\" agrees with \"drummer\", but \"guitarists\" is closer to the verb.",
          "\"Is\" is singular and the wrong tense.",
          "\"Has been\" is singular."]),
      Q("c2-05", "Along with", "Taylor Swift, along with her entire band, ______ a full rehearsal before every stadium show.",
        ["holds", "hold", "are holding", "have held"], 0,
        "\"Along with her entire band\" is parenthetical; the subject is \"Taylor Swift\" (singular).",
        ["Correct. \"Taylor Swift… holds\".",
          "\"Hold\" is plural; the band is in a parenthetical phrase, not part of the subject.",
          "\"Are holding\" is plural.",
          "\"Have held\" is plural."]),
      Q("c2-06", "There are", "There ______ three hidden passages beneath the castle, according to the map Ron found.",
        ["are", "is", "was", "has been"], 0,
        "In \"There is/are\" sentences, the subject comes after the verb: \"passages\" (plural).",
        ["Correct. \"There are three hidden passages\".",
          "\"Is\" is singular; the subject \"passages\" is plural.",
          "\"Was\" is singular.",
          "\"Has been\" is singular."]),
      Q("c2-07", "Plural subject", "The members of the band ______ each written at least one song for the new album.",
        ["have", "has", "is", "was"], 0,
        "The subject is \"members\" (plural); \"of the band\" is a prepositional phrase.",
        ["Correct. \"The members… have written\".",
          "\"Has\" matches \"band\", the trap noun.",
          "\"Is written\" is singular and changes the meaning to passive.",
          "\"Was\" is singular."]),
      Q("c2-08", "Collective noun", "The team of engineers ______ finally solved the bridge's swaying problem.",
        ["has", "have", "are", "were"], 0,
        "\"Team\" is a collective noun acting as one unit, so it's singular.",
        ["Correct. \"The team… has solved\".",
          "\"Have\" matches \"engineers\", but the subject is \"team.\"",
          "\"Are solved\" is plural and passive.",
          "\"Were\" is plural."]),
      Q("c2-09", "Inverted sentence", "Under the floorboards of the old theater ______ a box of love letters from the 1920s.",
        ["lies", "lie", "are lying", "have lain"], 0,
        "Inverted order: the subject \"a box\" comes after the verb and is singular.",
        ["Correct. \"A box… lies under the floorboards\".",
          "\"Lie\" is plural, matching \"letters\" or \"floorboards\", not \"box.\"",
          "\"Are lying\" is plural.",
          "\"Have lain\" is plural."]),
      Q("c2-10", "Compound subject", "Simone Biles and her coach ______ the routine three times before every competition.",
        ["review", "reviews", "is reviewing", "has reviewed"], 0,
        "A and B make a plural subject.",
        ["Correct. \"Simone Biles and her coach review\".",
          "\"Reviews\" is singular.",
          "\"Is reviewing\" is singular.",
          "\"Has reviewed\" is singular."]),
      Q("c2-11", "The number of", "The number of fans waiting outside the stadium ______ grown every hour.",
        ["has", "have", "are", "were"], 0,
        "\"The number of…\" is singular (it's one number).",
        ["Correct. \"The number… has grown\".",
          "\"Have\" matches \"fans\", but the subject is \"number.\"",
          "\"Are grown\" is plural and ungrammatical here.",
          "\"Were\" is plural."]),
      Q("c2-12", "A number of", "A number of scientists ______ questioned the study's conclusions.",
        ["have", "has", "is", "was"], 0,
        "\"A number of…\" means \"several\" and is plural.",
        ["Correct. \"A number of scientists have questioned\".",
          "\"Has\" is singular.",
          "\"Is\" is singular.",
          "\"Was\" is singular."]),
      Q("c2-13", "Every one of", "Every one of Sherlock's clues ______ to the same suspect.",
        ["points", "point", "are pointing", "have pointed"], 0,
        "\"Every one\" is singular.",
        ["Correct. \"Every one… points\".",
          "\"Point\" is plural, matching \"clues\".",
          "\"Are pointing\" is plural.",
          "\"Have pointed\" is plural."]),
      Q("c2-14", "Long interrupter", "The recipe for Grandma Rosa's famous dumplings, which several restaurants have tried to copy, ______ a secret ingredient.",
        ["contains", "contain", "are containing", "have contained"], 0,
        "Skip the prepositional phrase and the \"which\" clause: the subject is \"recipe\" (singular).",
        ["Correct. \"The recipe… contains\".",
          "\"Contain\" agrees with \"dumplings\" or \"restaurants\", the traps.",
          "\"Are containing\" is plural.",
          "\"Have contained\" is plural."]),
      Q("c2-15", "3:1 shortcut", "The migration patterns of the monarch butterfly ______ scientists who study climate change.",
        ["fascinate", "fascinates", "is fascinating", "has fascinated"], 0,
        "Subject: \"patterns\" (plural). Three choices are singular and one is plural; the odd one out is the answer.",
        ["Correct. \"The migration patterns… fascinate\".",
          "\"Fascinates\" is singular, matching \"butterfly.\"",
          "\"Is fascinating\" is singular.",
          "\"Has fascinated\" is singular."]),
      Q("c2-16", "Interrupted plural", "Spider-Man's web-shooters, built from spare parts in a high school lab, ______ able to hold the weight of a falling car.",
        ["are", "is", "was", "has been"], 0,
        "The subject is \"web-shooters\" (plural); the phrase between the commas doesn't change it.",
        ["Correct. \"Web-shooters… are able\".",
          "\"Is\" is singular, matching \"lab.\"",
          "\"Was\" is singular.",
          "\"Has been\" is singular."]),
      Q("c2-17", "Either/or", "Either Hermione or Harry ______ the key to the locked door.",
        ["has", "have", "are holding", "were holding"], 0,
        "Either/or with two singular subjects takes a singular verb.",
        ["Correct. \"Either Hermione or Harry has\".",
          "\"Have\" is plural; only one of them has the key.",
          "\"Are holding\" is plural.",
          "\"Were holding\" is plural."]),
      Q("c2-18", "Singular -s noun", "Physics, despite its reputation, ______ the favorite subject of many students at the academy.",
        ["is", "are", "were", "have been"], 0,
        "\"Physics\" ends in -s but is a singular field of study.",
        ["Correct. \"Physics… is\".",
          "\"Are\" treats \"physics\" as plural.",
          "\"Were\" is plural.",
          "\"Have been\" is plural."]),
      Q("c2-19", "A pair of", "The pair of sneakers that LeBron wore in the championship game ______ sold at auction last year.",
        ["was", "were", "have been", "are"], 0,
        "\"Pair\" is singular, so the verb is singular.",
        ["Correct. \"The pair… was sold\".",
          "\"Were\" matches \"sneakers\", the trap.",
          "\"Have been\" is plural.",
          "\"Are\" is plural and the wrong tense for \"last year.\""]),
      Q("c2-20", "Inverted compound", "Among the treasures in the museum ______ a golden mask and two jeweled daggers.",
        ["are", "is", "was", "has been"], 0,
        "Inverted order: the subject \"a golden mask and two jeweled daggers\" is compound, so plural.",
        ["Correct. \"A golden mask and two jeweled daggers are among the treasures\".",
          "\"Is\" is singular; the subject has two items.",
          "\"Was\" is singular.",
          "\"Has been\" is singular."]),
      Q("c2-21", "Prepositional phrase", "The goal of the new study by researchers at the Riverside Institute ______ to measure how music affects memory.",
        ["is", "are", "were", "have been"], 0,
        "The subject is \"goal\" (singular); everything after \"of\" is prepositional.",
        ["Correct. \"The goal… is\".",
          "\"Are\" matches \"researchers\", the trap.",
          "\"Were\" is plural.",
          "\"Have been\" is plural."]),
      Q("c2-22", "As well as", "Pikachu, as well as the other creatures on the trainer's team, ______ ready for the final battle.",
        ["is", "are", "were", "have been"], 0,
        "\"As well as…\" is parenthetical; the subject is \"Pikachu\" (singular).",
        ["Correct. \"Pikachu… is ready\".",
          "\"Are\" treats the parenthetical as part of the subject.",
          "\"Were\" is plural.",
          "\"Have been\" is plural."]),
      Q("c2-23", "Compound subject", "Mathematics and music, according to a recent study, ______ more connected than most people assume.",
        ["are", "is", "was", "has been"], 0,
        "A and B → plural.",
        ["Correct. \"Mathematics and music… are\".",
          "\"Is\" is singular; there are two subjects.",
          "\"Was\" is singular.",
          "\"Has been\" is singular."]),
      Q("c2-24", "One of", "One of the most surprising findings in Dr. Okafor's report ______ that sleep improves problem-solving.",
        ["is", "are", "were", "have been"], 0,
        "\"One of the…\" is singular: the subject is \"One.\"",
        ["Correct. \"One… is\".",
          "\"Are\" matches \"findings\", the trap.",
          "\"Were\" is plural.",
          "\"Have been\" is plural."]),
      Q("c2-25", "Including…", "The stars of the anime series, including Naruto and his rival Sasuke, ______ voiced by actors who also sing.",
        ["are", "is", "was", "has been"], 0,
        "The subject is \"stars\" (plural); \"including…\" is parenthetical.",
        ["Correct. \"The stars… are voiced\".",
          "\"Is\" is singular, matching \"series\" or \"Sasuke.\"",
          "\"Was\" is singular.",
          "\"Has been\" is singular."]),
    ],
  });
})();
