// Chapter 3: Verb vs. Non-Verb Identification
(function () {
  const { Q } = window.ClauseBank;
  const TWO_VERBS = "The sentence already has its main verb later on, so a second conjugated verb here creates two verbs with no conjunction.";
  const NO_VERB = "Without a conjugated verb, the sentence has no main verb, so it becomes a fragment.";
  window.ClauseBank.add({
    id: 3,
    short: "Verb vs. Non-Verb",
    title: "Verb vs. Non-Verb Identification",
    focus: "Decide whether the blank needs the sentence's main verb or a non-verb (participle or modifier).",
    rules: [
      "Every sentence needs exactly one main (conjugated) verb per independent clause.",
      "First scan the sentence for a main verb. If one already exists, the blank must be a NON-verb: an -ing/-ed participle, an infinitive, or a modifier.",
      "If there is no main verb anywhere, the blank must supply it (is, was, has, -s, -ed).",
      "Appositive structure: Title Name, [non-essential modifier], MAIN VERB… The comma after the name pairs with the comma before the main verb.",
      "Never put a single comma between a subject and its verb.",
    ],
    questions: [
      Q("c3-01", "Appositive structure", "Professional basketball player Stephen ______ his shots to force defenders to guard him far beyond the three-point arc, releases the ball with a lightning-fast motion that leaves opponents completely helpless.",
        ["Curry is intending", "Curry, intends", "Curry, intending", "Curry intends"], 2,
        "The main verb is \"releases.\" The blank opens a non-essential modifier: Name, -ing…, verb.",
        ["\"Is intending\" adds a second main verb next to \"releases\" with no conjunction.",
          TWO_VERBS + " \"Intends… releases\".",
          "Correct. \"Curry, intending his shots…, releases\": the participle phrase is set off by commas, and \"releases\" is the only main verb.",
          TWO_VERBS + " It's also missing the comma that pairs with the one before \"releases.\""]),
      Q("c3-02", "Participle modifier", "The striker, ______ past three defenders, slid the ball into the corner of the net.",
        ["dribbling", "dribbled", "dribbles", "was dribbling"], 0,
        "Main verb: \"slid.\" The phrase between the commas must be a non-verb.",
        ["Correct. \"Dribbling past three defenders\" describes the striker; \"slid\" is the main verb.",
          "\"Dribbled\" reads as a second main verb next to \"slid.\"",
          TWO_VERBS,
          TWO_VERBS]),
      Q("c3-03", "Past participle", "Beyoncé's new stage, ______ with mirrors, lasers, and a rotating platform, cost more than her entire first tour.",
        ["built", "builds", "was built", "is building"], 0,
        "Main verb: \"cost.\" The blank describes the stage, so it's a past participle (non-verb).",
        ["Correct. \"Built with mirrors…\" modifies \"stage\"; \"cost\" is the main verb.",
          TWO_VERBS,
          TWO_VERBS,
          TWO_VERBS + " It also wrongly says the stage is doing the building."]),
      Q("c3-04", "Needs main verb", "The ancient scrolls discovered near the Dead Sea ______ to be more than two thousand years old.",
        ["are believed", "being believed", "believed", "having been believed"], 0,
        "\"Discovered near the Dead Sea\" is a modifier, so the sentence still needs its main verb.",
        ["Correct. \"The scrolls… are believed\": the main verb.",
          NO_VERB,
          "\"Believed\" here reads as another modifier, so the sentence still has no main verb.",
          NO_VERB]),
      Q("c3-05", "Participle modifier", "Goku, ______ his energy for one final attack, closed his eyes and focused.",
        ["gathering", "gathered", "gathers", "was gathering"], 0,
        "Main verbs: \"closed… and focused.\" The blank is a modifier.",
        ["Correct. \"Gathering his energy…\" is set off by commas.",
          "\"Gathered\" acts as a second main verb here.",
          TWO_VERBS,
          TWO_VERBS]),
      Q("c3-06", "Needs main verb", "Every spring, the marine biologists ______ the coral reef for signs of bleaching.",
        ["survey", "surveying", "to survey", "having surveyed"], 0,
        "There's no other verb, so the blank must be the main verb.",
        ["Correct. \"The marine biologists survey\" supplies the main verb.",
          NO_VERB,
          NO_VERB,
          NO_VERB]),
      Q("c3-07", "Appositive structure", "Award-winning chef Marco ______ fresh ingredients from local farms every morning, prepares a menu that changes daily.",
        ["Ruiz, who selects", "Ruiz selects", "Ruiz, selects", "Ruiz who selects"], 0,
        "Main verb: \"prepares.\" The blank begins a non-essential clause closed by the comma before \"prepares.\"",
        ["Correct. \"Ruiz, who selects…, prepares\": the \"who\" clause is a non-verb modifier set off by commas.",
          TWO_VERBS,
          "A comma between subject and verb, plus two main verbs.",
          "A non-essential \"who\" clause after a specific name needs a comma before it, to pair with the one before \"prepares.\""]),
      Q("c3-08", "Past participle", "The museum's newest exhibit, ______ in partnership with the city's art school, features sculptures made entirely of recycled plastic.",
        ["designed", "designs", "was designed", "is designing"], 0,
        "Main verb: \"features.\"",
        ["Correct. \"Designed in partnership…\" is a modifier between the commas.",
          TWO_VERBS,
          TWO_VERBS,
          TWO_VERBS]),
      Q("c3-09", "Participle modifier", "Hermione, ______ that the potion was missing a key ingredient, quickly added a pinch of powdered root.",
        ["realizing", "realized", "realizes", "had realized"], 0,
        "Main verb: \"added.\"",
        ["Correct. \"Realizing that…\" is a non-verb modifier.",
          "\"Realized\" competes with \"added\" as a main verb.",
          TWO_VERBS,
          TWO_VERBS]),
      Q("c3-10", "Needs main verb", "Every summer, thousands of monarch butterflies ______ across North America in a journey no single butterfly completes.",
        ["migrate", "migrating", "to migrate", "having migrated"], 0,
        "No other main verb for \"butterflies\", so the blank supplies it.",
        ["Correct. \"Butterflies migrate\".",
          NO_VERB,
          NO_VERB,
          NO_VERB]),
      Q("c3-11", "Appositive structure", "Champion swimmer Katie ______ in the pool by five a.m. every day, credits her success to consistency.",
        ["Ledecky, training", "Ledecky trains", "Ledecky, trains", "Ledecky is training"], 0,
        "Main verb: \"credits.\" Name, -ing…, verb.",
        ["Correct. \"Ledecky, training…, credits\".",
          TWO_VERBS,
          "A comma between the subject and \"trains\", plus two main verbs.",
          TWO_VERBS]),
      Q("c3-12", "Participle modifier", "The documentary, ______ the lives of deep-sea fishermen, won three awards at the festival.",
        ["following", "follows", "has followed", "is following"], 0,
        "Main verb: \"won.\"",
        ["Correct. \"Following the lives…\" describes the documentary.",
          TWO_VERBS,
          TWO_VERBS,
          TWO_VERBS]),
      Q("c3-13", "Needs main verb", "The letters that Frida Kahlo wrote to her friends ______ a side of the painter that few people knew.",
        ["reveal", "revealing", "to reveal", "having revealed"], 0,
        "\"That Frida Kahlo wrote…\" is a clause inside the subject; \"letters\" still needs a main verb.",
        ["Correct. \"The letters… reveal\".",
          NO_VERB,
          NO_VERB,
          NO_VERB]),
      Q("c3-14", "Participle modifier", "Mario, ______ the mushroom just in time, grew to twice his size.",
        ["grabbing", "grabbed", "grabs", "had grabbed"], 0,
        "Main verb: \"grew.\"",
        ["Correct. \"Grabbing the mushroom just in time\" modifies Mario.",
          "\"Grabbed\" acts as a second main verb.",
          TWO_VERBS,
          TWO_VERBS]),
      Q("c3-15", "Reduced clause", "The volunteers ______ the beach before sunrise collected more than two tons of plastic.",
        ["cleaning", "cleaned", "clean", "were cleaning"], 0,
        "Main verb: \"collected.\" The blank starts a modifier identifying which volunteers.",
        ["Correct. \"The volunteers cleaning the beach… collected\".",
          "\"Cleaned\" + \"collected\" gives two main verbs with no conjunction.",
          TWO_VERBS,
          TWO_VERBS]),
      Q("c3-16", "Needs main verb", "In her latest study, astronomer Dr. Priya Nair ______ that the faint signal came from a distant galaxy.",
        ["argues", "arguing", "to argue", "having argued"], 0,
        "\"Came\" belongs to the \"that\" clause; the main clause still needs a verb for Dr. Nair.",
        ["Correct. \"Dr. Priya Nair argues\".",
          NO_VERB,
          NO_VERB,
          NO_VERB]),
      Q("c3-17", "Appositive structure", "Serena ______ her racket after the final point, ran to the stands to hug her family.",
        ["Williams, dropping", "Williams dropped", "Williams, dropped", "Williams drops"], 0,
        "Main verb: \"ran.\"",
        ["Correct. \"Williams, dropping her racket…, ran\".",
          TWO_VERBS,
          "A comma between the subject and \"dropped\", plus two main verbs.",
          TWO_VERBS]),
      Q("c3-18", "Past participle", "The bridge, ______ in 1937, still carries more than a hundred thousand cars a day.",
        ["completed", "completes", "was completed", "is completing"], 0,
        "Main verb: \"carries.\"",
        ["Correct. \"Completed in 1937\" modifies \"bridge.\"",
          TWO_VERBS,
          TWO_VERBS,
          TWO_VERBS]),
      Q("c3-19", "Needs main verb", "The students who joined the robotics club last fall ______ a robot that can sort recycling.",
        ["have built", "building", "to build", "having built"], 0,
        "\"Joined\" belongs to the \"who\" clause; \"students\" still needs a main verb.",
        ["Correct. \"The students… have built\".",
          NO_VERB,
          NO_VERB,
          NO_VERB]),
      Q("c3-20", "Past participle", "Shrek, ______ by the noise outside his swamp, stormed out to confront the visitors.",
        ["annoyed", "annoys", "was annoyed", "is annoying"], 0,
        "Main verb: \"stormed.\"",
        ["Correct. \"Annoyed by the noise…\" describes Shrek.",
          TWO_VERBS,
          TWO_VERBS,
          TWO_VERBS]),
      Q("c3-21", "Appositive structure", "Pop star Bad ______ a surprise acoustic set at the small café, delighted the twenty fans who happened to be inside.",
        ["Bunny, performing", "Bunny performed", "Bunny, performed", "Bunny performs"], 0,
        "Main verb: \"delighted.\"",
        ["Correct. \"Bad Bunny, performing…, delighted\".",
          TWO_VERBS,
          "A comma between the subject and \"performed\", plus two main verbs.",
          TWO_VERBS]),
      Q("c3-22", "Needs main verb", "The newly discovered species of frog, which lives only on a single mountaintop in Peru, ______ its eggs on the undersides of leaves.",
        ["lays", "laying", "to lay", "having laid"], 0,
        "\"Lives\" is inside the \"which\" clause; the subject \"species\" still needs a main verb.",
        ["Correct. \"The species… lays\".",
          NO_VERB,
          NO_VERB,
          NO_VERB]),
      Q("c3-23", "Participle modifier", "Sherlock Holmes, ______ on his pipe in silence, finally announced the name of the thief.",
        ["puffing", "puffed", "puffs", "had puffed"], 0,
        "Main verb: \"announced.\"",
        ["Correct. \"Puffing on his pipe…\" is a modifier.",
          "\"Puffed\" acts as a second main verb.",
          TWO_VERBS,
          TWO_VERBS]),
      Q("c3-24", "Participle modifier", "The ______ for the gala, practiced the same eight bars for three hours.",
        ["violinist, preparing", "violinist prepared", "violinist, prepared", "violinist prepares"], 0,
        "Main verb: \"practiced.\"",
        ["Correct. \"The violinist, preparing for the gala, practiced\".",
          TWO_VERBS,
          "A comma between the subject and \"prepared\", plus two main verbs.",
          TWO_VERBS]),
      Q("c3-25", "Needs main verb", "Each spring, researchers at the Pacific Whale Center ______ the humpbacks that pass the coast and record their songs.",
        ["photograph", "photographing", "to photograph", "having photographed"], 0,
        "\"Pass\" belongs to the \"that\" clause; \"researchers\" needs a main verb, parallel with \"record.\"",
        ["Correct. \"Researchers… photograph… and record\".",
          NO_VERB,
          NO_VERB,
          NO_VERB]),
    ],
  });
})();
