// Chapter 4: Verb Tenses & Aspect
(function () {
  const { Q } = window.ClauseBank;
  window.ClauseBank.add({
    id: 4,
    short: "Verb Tenses",
    title: "Verb Tenses & Aspect",
    focus: "Use time clues to pick the tense: past, future, past perfect, present perfect or present.",
    rules: [
      "Past (happened): a finished time, e.g. \"last summer\", \"in 1969\", \"yesterday\".",
      "Future (will happen): \"next spring\", \"tomorrow\", \"by 2050\".",
      "Past perfect (had happened): an action finished BEFORE another past action (\"By the time they arrived, she had left\").",
      "Present perfect (has/have happened, until now): \"since 2015\", \"so far\", \"over the past decade\".",
      "Present (happens): general truths, facts, habits and how things work (\"Water boils at 100 °C\").",
      "Keep tenses consistent with the rest of the passage unless a time clue says otherwise.",
    ],
    questions: [
      Q("c4-01", "Present (general fact)", "In recent years, scientists across the anime universe have developed advanced devices that evaluate the power levels of supernatural fighters. Researchers in one martial-arts anime world, for example, use a digital power visor. This tool ______ a warrior's raw combat capability, speed, and energy output.",
        ["measures", "had measured", "would have measured", "will have been measuring"], 0,
        "The passage describes what the tool does in general, in the present (\"use\"), so the present tense fits.",
        ["Correct. \"This tool measures…\": the present tense for what the tool does, matching \"use.\"",
          "Past perfect needs an earlier past event; the passage is in the present.",
          "\"Would have measured\" describes something hypothetical that didn't happen.",
          "Future perfect progressive points to a future deadline that the passage never mentions."]),
      Q("c4-02", "Past", "Last summer, {{NAME_1}} ______ a new move that no gymnast had ever attempted in competition.",
        ["landed", "lands", "will land", "has landed"], 0,
        "\"Last summer\" marks a finished past time, so use the simple past.",
        ["Correct. \"Last summer… landed\".",
          "The present doesn't match \"last summer.\"",
          "The future can't happen last summer.",
          "The present perfect can't be used with a finished time like \"last summer.\""]),
      Q("c4-03", "Past perfect", "By the time the firefighters arrived, the neighbors ______ everyone out of the building.",
        ["had already led", "already lead", "will already lead", "are already leading"], 0,
        "Leading everyone out happened before the firefighters arrived (past), so use the past perfect.",
        ["Correct. \"By the time… arrived, … had already led\".",
          "The present doesn't fit a past event.",
          "The future doesn't fit \"arrived.\"",
          "The present progressive doesn't fit a past event."]),
      Q("c4-04", "Present perfect", "Since 2015, the city ______ more than ten thousand trees along its sidewalks.",
        ["has planted", "planted", "had planted", "will plant"], 0,
        "\"Since 2015\" means from then until now: the present perfect.",
        ["Correct. \"Since 2015… has planted\".",
          "The simple past doesn't connect to \"since\" (until now).",
          "The past perfect needs a later past reference point.",
          "The future doesn't fit \"since 2015.\""]),
      Q("c4-05", "Future", "Next spring, the robotics team ______ its new arm at the national competition.",
        ["will debut", "debuted", "has debuted", "had debuted"], 0,
        "\"Next spring\" points to the future.",
        ["Correct. \"Next spring… will debut\".",
          "The past contradicts \"next spring.\"",
          "The present perfect contradicts \"next spring.\"",
          "The past perfect contradicts \"next spring.\""]),
      Q("c4-06", "Present (general truth)", "Water ______ at 100 degrees Celsius at sea level.",
        ["boils", "boiled", "had boiled", "will have boiled"], 0,
        "Scientific facts take the simple present.",
        ["Correct. A general truth: \"Water boils.\"",
          "The past suggests it's no longer true.",
          "The past perfect needs another past event.",
          "The future perfect needs a future deadline."]),
      Q("c4-07", "Past perfect", "When {{NAME_1}} opened the book, {{NAME_1}} discovered that someone ______ notes in every margin.",
        ["had written", "writes", "will write", "has written"], 0,
        "The notes were written before {{NAME_1}} opened the book (an earlier past).",
        ["Correct. \"Had written\": before \"opened\" and \"discovered.\"",
          "The present doesn't fit a past discovery.",
          "The future doesn't fit.",
          "The present perfect doesn't sit inside a past narrative."]),
      Q("c4-08", "Present perfect", "{{NAME_1}} ______ eleven albums so far, and fans are already guessing the title of the next one.",
        ["has released", "released", "had released", "will release"], 0,
        "\"So far\" means up until now: the present perfect.",
        ["Correct. \"Has released… so far\".",
          "The simple past ignores \"so far.\"",
          "The past perfect needs a past reference point.",
          "The future contradicts \"so far.\""]),
      Q("c4-09", "Past", "In 1969, astronauts ______ on the Moon for the first time.",
        ["walked", "walk", "have walked", "had walked"], 0,
        "A specific past year takes the simple past.",
        ["Correct. \"In 1969… walked\".",
          "The present contradicts 1969.",
          "The present perfect can't be used with a specific past year.",
          "The past perfect needs another, later past event."]),
      Q("c4-10", "Present (habit)", "Every morning, {{NAME_1}} ______ for an hour before breakfast.",
        ["stretches", "stretched", "had stretched", "will have stretched"], 0,
        "\"Every morning\" describes a habit: the simple present.",
        ["Correct. A habit: \"stretches.\"",
          "The past suggests the habit ended; nothing says so.",
          "The past perfect needs a past reference point.",
          "The future perfect needs a future deadline."]),
      Q("c4-11", "Future perfect", "By next June, {{NAME_1}} ______ the coral reef for ten straight years.",
        ["will have studied", "studied", "has studied", "had studied"], 0,
        "\"By next June\" is a future deadline: the future perfect.",
        ["Correct. \"By next June… will have studied\".",
          "The past contradicts \"next June.\"",
          "The present perfect stops at now, not next June.",
          "The past perfect is for the past."]),
      Q("c4-12", "Consistency", "The detective entered the room, looked at the broken window, and ______ that the thief had escaped through the garden.",
        ["concluded", "concludes", "will conclude", "has concluded"], 0,
        "In a list of actions, keep the tense consistent: entered, looked, concluded.",
        ["Correct. Simple past, parallel with \"entered\" and \"looked.\"",
          "The present breaks the series.",
          "The future breaks the series.",
          "The present perfect breaks the series."]),
      Q("c4-13", "Past perfect", "{{NAME_1}} was surprised to learn that {{NAME_1_POSS}} opponent ______ under the same master years earlier.",
        ["had trained", "trains", "will train", "has trained"], 0,
        "The training happened \"years earlier\", before {{NAME_1}} learned about it: the past perfect.",
        ["Correct. \"Had trained… years earlier\".",
          "The present contradicts \"years earlier.\"",
          "The future contradicts \"years earlier.\"",
          "The present perfect doesn't sit inside a past narrative."]),
      Q("c4-14", "Present (fact)", "Scientists now know that Earth ______ around the Sun once every 365.25 days.",
        ["travels", "traveled", "had traveled", "will have traveled"], 0,
        "A permanent scientific fact takes the present.",
        ["Correct. \"Earth travels around the Sun.\"",
          "The past suggests it no longer happens.",
          "The past perfect doesn't fit a permanent fact.",
          "The future perfect needs a deadline."]),
      Q("c4-15", "Present progressive", "Right now, the orchestra ______ the final movement of the symphony.",
        ["is rehearsing", "rehearsed", "had rehearsed", "will have rehearsed"], 0,
        "\"Right now\" means happening at this moment: the present progressive.",
        ["Correct. \"Right now… is rehearsing\".",
          "The past contradicts \"right now.\"",
          "The past perfect contradicts \"right now.\"",
          "The future perfect contradicts \"right now.\""]),
      Q("c4-16", "Present perfect", "Since the first smartphones appeared, streaming ______ the way people discover new music.",
        ["has transformed", "transformed", "had transformed", "will transform"], 0,
        "\"Since…\" stretches from the past until now: the present perfect.",
        ["Correct. \"Since… has transformed\".",
          "The simple past doesn't fit \"since.\"",
          "The past perfect needs a later past reference point.",
          "The future doesn't fit \"since.\""]),
      Q("c4-17", "Conditional", "If {{NAME_1}} had left the lab a minute earlier, {{NAME_1}} ______ the bus.",
        ["would have caught", "will catch", "catches", "had caught"], 0,
        "\"If… had left\" (past unreal condition) pairs with \"would have + past participle.\"",
        ["Correct. \"If {{NAME_1}} had left…, {{NAME_1}} would have caught\".",
          "\"Will catch\" is for real future conditions.",
          "The present doesn't fit a past hypothetical.",
          "\"Had caught\" in both halves is incorrect; the result clause needs \"would have.\""]),
      Q("c4-18", "Future", "Tomorrow at noon, the museum ______ its new dinosaur hall to the public.",
        ["will open", "opened", "had opened", "has opened"], 0,
        "\"Tomorrow\" points to the future.",
        ["Correct. \"Tomorrow… will open\".",
          "The past contradicts \"tomorrow.\"",
          "The past perfect contradicts \"tomorrow.\"",
          "The present perfect contradicts \"tomorrow.\""]),
      Q("c4-19", "Past", "Two thousand years ago, Roman engineers ______ a type of concrete that has survived to this day.",
        ["developed", "develop", "will develop", "have developed"], 0,
        "\"Two thousand years ago\" is a finished past time.",
        ["Correct. \"Two thousand years ago… developed\".",
          "The present contradicts \"ago.\"",
          "The future contradicts \"ago.\"",
          "The present perfect can't be used with \"ago.\""]),
      Q("c4-20", "Past perfect", "{{NAME_1}} ______ two Nobel Prizes by the time {{NAME_1}} turned forty-four.",
        ["had won", "wins", "will win", "has won"], 0,
        "\"By the time {{NAME_1}} turned forty-four\" is a past reference point, and the winning came before it.",
        ["Correct. \"Had won… by the time {{NAME_1}} turned forty-four\".",
          "The present doesn't fit a past milestone.",
          "The future doesn't fit.",
          "The present perfect doesn't fit a past reference point."]),
      Q("c4-21", "Present (habit)", "Each year, the festival ______ more than fifty thousand visitors to the small coastal town.",
        ["attracts", "attracted", "had attracted", "will have attracted"], 0,
        "\"Each year\" describes a repeated, ongoing pattern: the present.",
        ["Correct. \"Each year… attracts\".",
          "The past suggests the pattern ended.",
          "The past perfect needs a past reference point.",
          "The future perfect needs a deadline."]),
      Q("c4-22", "Past perfect progressive", "When the bell finally rang, the students ______ their essays for nearly an hour.",
        ["had been writing", "are writing", "will be writing", "write"], 0,
        "An ongoing action that continued up to a past moment takes the past perfect progressive.",
        ["Correct. \"When the bell rang, they had been writing… for nearly an hour.\"",
          "The present doesn't fit \"rang.\"",
          "The future doesn't fit \"rang.\"",
          "The simple present doesn't fit \"rang.\""]),
      Q("c4-23", "Past", "{{NAME_1}} ______ the song during {{NAME_1_POSS}} rehearsal yesterday, but {{NAME_1}} saved the final version for the live show.",
        ["sang", "sings", "will sing", "has sung"], 0,
        "\"Yesterday\" and \"saved\" mark the past.",
        ["Correct. \"Sang… yesterday\".",
          "The present contradicts \"yesterday.\"",
          "The future contradicts \"yesterday.\"",
          "The present perfect can't be used with \"yesterday.\""]),
      Q("c4-24", "Future", "Researchers predict that by 2050, electric cars ______ most of the vehicles on the road.",
        ["will make up", "made up", "had made up", "make up"], 0,
        "\"By 2050\" is a future time.",
        ["Correct. \"By 2050… will make up\".",
          "The past contradicts 2050.",
          "The past perfect contradicts 2050.",
          "The present states it as already true; the passage is a prediction."]),
      Q("c4-25", "Past perfect", "{{NAME_1}} ______ in the swamp for years before {{NAME_2}} showed up at {{NAME_1_POSS}} door.",
        ["had lived", "lives", "will live", "has lived"], 0,
        "The living came before another past event (\"showed up\"): the past perfect.",
        ["Correct. \"Had lived… before {{NAME_2}} showed up\".",
          "The present doesn't fit a past story.",
          "The future doesn't fit.",
          "The present perfect doesn't fit a past reference point."]),
    ],
  });
})();
