// Chapter 5: Logical Transitions
(function () {
  const { Q, B } = window.ClauseBank;
  const C = "Contrast words (However, Nevertheless, In contrast) need the second idea to oppose or surprise you after the first.";
  const A = "Addition words (Additionally, Moreover, In addition) need a second point in the same direction.";
  const E = "Example words (For example, For instance) need the second sentence to be a specific case of the first.";
  const R = "Cause/effect words (Therefore, As a result, Consequently) need the second idea to be caused by the first.";
  const S = "Similarity words (Similarly, Likewise) need two things that match, not a result or a contrast.";
  window.ClauseBank.add({
    id: 5,
    short: "Logical Transitions",
    title: "Logical Transitions",
    kind: "transition",
    focus: "Read both sentences, name the relationship, then pick the transition that matches.",
    rules: [
      "Cover the choices. Read the sentence before and after the blank, and name the relationship in your own words.",
      "Contrast: However, Nevertheless, In contrast, By contrast, Conversely, Even so, Instead.",
      "Addition: Additionally, Moreover, Furthermore, In addition.",
      "Example: For example, For instance, Specifically (gives detail).",
      "Cause/Effect: Therefore, Thus, As a result, Consequently, Accordingly.",
      "Similarity: Similarly, Likewise.",
    ],
    questions: [
      // Benchmark (Review for Understanding): a concession admits a limit on the earlier finding.
      B("Concession Transition", Object.assign(Q("c5-bm", "Concession", "A 2019 study led by linguist {{NAME_1}} tested whether students learn new words faster when the words sound like what they describe, such as “buzz” or “splash.” The study found that the more a word sounded like its meaning, the more likely students were to remember it. ______ the link between sound and memory was weaker than the link between memory and another factor the study measured: how often students saw the word.",
        ["Granted,","In fact,","In other words,","As a result,"], 0,
        "\"Granted\" concedes a point that limits the main claim. Sound helped, but how often students saw the word mattered more: a concession.",
        ["Correct. \"Granted\" admits a limit on the finding: sound helped, but its link to memory was weaker than frequency's.",
          "\"In fact\" strengthens or intensifies the previous point; this sentence limits it.",
          "\"In other words\" restates the previous point; this sentence adds a new, limiting fact.",
          "\"As a result\" needs the weaker link to be caused by the finding, and it isn't."]), { kind: "transition" })),
      Q("c5-01", "Contrast", "During a citywide blackout, firefighter {{NAME_1}} helped rescue hundreds of passengers from stalled subway trains, earning {{NAME_1_OBJ}} the nickname “The Guardian of the City.” ______ despite the fame of {{NAME_1_POSS}} actions that night, {{NAME_1}} is discussed far less today by younger firefighters than other well-known members of the department, such as {{NAME_2}} and {{NAME_3}}.",
        ["For example,","However,","Specifically,","Similarly,"], 1,
        "Famous rescues vs. being discussed less today is a contrast.",
        ["\"For example\" needs an instance of the first idea; being forgotten isn't an example of fame.",
          "Correct. \"However\" signals the surprising contrast: famous then, discussed less now.",
          "\"Specifically\" would add detail about the blackout, not a change in reputation.",
          "\"Similarly\" needs a matching idea; this is the opposite."]),
      Q("c5-02", "Contrast", "{{NAME_1}} faced constant obstacles as a young scientist. ______ {{NAME_1}} became the first person to win Nobel Prizes in two different sciences.",
        ["Nevertheless,", "For instance,", "Similarly,", "Therefore,"], 0,
        "Obstacles → succeeded anyway: a contrast (concession).",
        ["Correct. \"Nevertheless\" means \"in spite of that.\"", E, S, R + " Obstacles didn't cause the prizes."]),
      Q("c5-03", "Emphasis", "Sea otters use rocks as tools to crack open shellfish. ______ some otters carry a favorite rock tucked under their arm for weeks at a time.",
        ["In fact,", "However,", "As a result,", "In contrast,"], 0,
        "The second sentence intensifies the first: they're so attached to tools they keep a favorite.",
        ["Correct. \"In fact\" adds a stronger, surprising detail.", C, R, C]),
      Q("c5-04", "Cause/effect", "{{NAME_1}} missed the last two practices with a sprained ankle. ______ the coach kept {{NAME_1_OBJ}} on the bench for the first quarter.",
        ["As a result,", "However,", "For example,", "Likewise,"], 0,
        "The injury caused the benching.",
        ["Correct. \"As a result\" shows the effect.", C, E, S]),
      Q("c5-05", "Example", "Many animals use camouflage to hide from predators. ______ the leaf-tailed gecko looks almost exactly like a dead leaf.",
        ["For example,", "However,", "Therefore,", "Meanwhile,"], 0,
        "The gecko is a specific example of camouflage.",
        ["Correct. \"For example\" introduces a specific case.", C, R, "\"Meanwhile\" signals something happening at the same time, not an example."]),
      Q("c5-06", "Contrast", "{{NAME_1}} finished the essay in a single evening. ______ {{NAME_2}} needed the entire week and still asked to borrow {{NAME_1_POSS}} notes.",
        ["By contrast,", "Similarly,", "For instance,", "Thus,"], 0,
        "Fast vs. slow: a contrast between two people.",
        ["Correct. \"By contrast\" compares opposites.", S, E, R]),
      Q("c5-07", "Addition", "The new subway line cut commute times in half. ______ it reduced traffic on the city's busiest roads.",
        ["Additionally,", "However,", "For example,", "Instead,"], 0,
        "A second benefit adds to the first.",
        ["Correct. \"Additionally\" adds another benefit.", C, E, "\"Instead\" signals a replacement, but both benefits happened."]),
      Q("c5-08", "Cause/effect", "{{NAME_1}}'s suit was designed to be as light as possible. ______ it offered almost no protection against serious impacts.",
        ["Consequently,", "Similarly,", "For example,", "Moreover,"], 0,
        "Being lightweight caused the lack of protection.",
        ["Correct. \"Consequently\" shows a result.", S, E, A + " The second point is a drawback caused by the first."]),
      Q("c5-09", "Contrast", "Most stars burn for billions of years. ______ the most massive stars burn out in only a few million.",
        ["In contrast,", "Likewise,", "For instance,", "As a result,"], 0,
        "Billions vs. millions: opposite lifespans.",
        ["Correct. \"In contrast\" compares the opposites.", S, E, R]),
      Q("c5-10", "Cause/effect", "The dance team rehearsed the routine every day for six months. ______ the team won the regional championship by a wide margin.",
        ["As a result,", "However,", "For example,", "In contrast,"], 0,
        "Practice led to the win.",
        ["Correct. \"As a result\" shows the effect.", C, E, C]),
      Q("c5-11", "Elaboration", "{{NAME_1}} is known for hiding clues for {{NAME_1_POSS}} fans. ______ {{NAME_1}} capitalized certain letters in {{NAME_1_POSS}} printed lyrics so that fans could decode secret phrases.",
        ["Specifically,", "However,", "As a result,", "In contrast,"], 0,
        "The second sentence spells out exactly how {{NAME_1}} hides clues.",
        ["Correct. \"Specifically\" introduces precise detail about the first idea.", C, R, C]),
      Q("c5-12", "Contrast", "Pluto was once considered the ninth planet. ______ astronomers reclassified it as a dwarf planet in 2006.",
        ["However,", "For example,", "Similarly,", "Furthermore,"], 0,
        "Once a planet → later reclassified: a contrast.",
        ["Correct. \"However\" signals the change.", E, S, A]),
      Q("c5-13", "Cause/effect", "The desert receives less than two inches of rain each year. ______ many plants there store water in thick, waxy leaves.",
        ["Therefore,", "However,", "For example,", "Similarly,"], 0,
        "Little rain causes plants to adapt by storing water.",
        ["Correct. \"Therefore\" shows the adaptation as a result.", C, E, S]),
      Q("c5-14", "Simultaneous contrast", "{{NAME_1}} trained in gravity ten times stronger than Earth's. ______ {{NAME_1_POSS}} rival {{NAME_2}} trained in gravity three hundred times stronger, hoping to surpass {{NAME_1_OBJ}}.",
        ["Meanwhile,", "For example,", "Therefore,", "In other words,"], 0,
        "Two rivals training at the same time in different ways.",
        ["Correct. \"Meanwhile\" sets the two training efforts side by side.", E, R, "\"In other words\" restates the same idea; {{NAME_2}}'s training is a different idea."]),
      Q("c5-15", "Cause/effect", "The museum's ancient coin collection is extremely fragile. ______ visitors are not allowed to touch any of the display cases.",
        ["Thus,", "Nevertheless,", "For example,", "Likewise,"], 0,
        "Fragility causes the no-touching rule.",
        ["Correct. \"Thus\" introduces the result.", C, E, S]),
      Q("c5-16", "Contrast", "{{NAME_1}} is famous for {{NAME_1_POSS}} powerful vaults. ______ {{NAME_1}} is also admired for {{NAME_1_POSS}} precise and graceful beam routines.",
        ["However,", "For example,", "Therefore,", "In other words,"], 0,
        "Power vs. grace: the second sentence turns to a different quality.",
        ["Correct. \"However\" shifts from {{NAME_1_POSS}} power to {{NAME_1_POSS}} grace.", E + " Beam routines aren't an example of vaults.", R, "\"In other words\" would restate the same idea."]),
      Q("c5-17", "Contrast", "The study found that students who slept eight hours scored higher on memory tests. ______ students who slept fewer than six hours forgot nearly a third of what they had learned.",
        ["Conversely,", "Similarly,", "For example,", "As a result,"], 0,
        "The opposite group had the opposite result.",
        ["Correct. \"Conversely\" introduces the reverse case.", S, E, R]),
      Q("c5-18", "Concession", "{{NAME_1}} insisted on being left alone. ______ {{NAME_1}} spent the entire journey talking with {{NAME_2}}.",
        ["Even so,", "For instance,", "Therefore,", "Likewise,"], 0,
        "The words and the actions don't match: a contrast.",
        ["Correct. \"Even so\" signals the unexpected behavior.", E, R, S]),
      Q("c5-19", "Elaboration", "Honeybees tell one another where flowers are through a “waggle dance.” ______ the angle of the dance tells other bees which direction to fly.",
        ["Specifically,", "However,", "Consequently,", "Instead,"], 0,
        "The second sentence explains exactly how the dance works.",
        ["Correct. \"Specifically\" adds the precise detail.", C, R, "\"Instead\" signals a replacement; nothing is replaced."]),
      Q("c5-20", "Contrast", "The city expected about two thousand people at the free concert. ______ more than ten thousand fans showed up.",
        ["Instead,", "For example,", "Similarly,", "Therefore,"], 0,
        "Expected two thousand → got ten thousand.",
        ["Correct. \"Instead\" shows what happened in place of the expectation.", E, S, R]),
      Q("c5-21", "Addition", "{{NAME_1}} spent a year designing the costumes for {{NAME_1_POSS}} tour. ______ {{NAME_1}} worked with the lighting team to match each outfit to a color scheme.",
        ["In addition,", "In contrast,", "For example,", "Nevertheless,"], 0,
        "A second task in the same direction.",
        ["Correct. \"In addition\" adds another effort.", C, E + " Working on lighting isn't an example of designing costumes.", C]),
      Q("c5-22", "Comparison", "Early computers filled entire rooms. ______ today's smartphones are thousands of times more powerful and fit in a pocket.",
        ["By comparison,", "Similarly,", "For example,", "As a result,"], 0,
        "Huge then vs. tiny now: a comparison of opposites.",
        ["Correct. \"By comparison\" sets the two side by side.", S, E, R]),
      Q("c5-23", "Cause/effect", "The detective found mud on the visitor's boots, a train ticket in his pocket, and sunburn on his neck. ______ she concluded that he had traveled from the coast that morning.",
        ["Therefore,", "However,", "For instance,", "Likewise,"], 0,
        "The clues lead to the conclusion.",
        ["Correct. \"Therefore\" introduces the conclusion drawn from the clues.", C, E, S]),
      Q("c5-24", "Similarity", "Elephants can recognize themselves in a mirror. ______ dolphins and magpies have passed similar self-recognition tests.",
        ["Similarly,", "However,", "Therefore,", "For example,"], 0,
        "Other animals share the same ability.",
        ["Correct. \"Similarly\" links matching abilities.", C, R, E + " Dolphins aren't an example of elephants."]),
      Q("c5-25", "Concession", "{{NAME_1}}'s first single was recorded in a bedroom with a borrowed microphone. ______ it was streamed more than a million times in its first week.",
        ["Nevertheless,", "For example,", "Similarly,", "Therefore,"], 0,
        "A humble start vs. a big success: a surprise.",
        ["Correct. \"Nevertheless\" signals success despite the humble setup.", E, S, R + " A borrowed microphone didn't cause the streams."]),
    ],
  });
})();
