// Chapter 6: Punctuation Fundamentals (Semicolon, Dash, Colon)
(function () {
  const { Q, B } = window.ClauseBank;
  const DASH_PAIR = "Dashes come in pairs around non-essential information: if one dash opens it, another must close it.";
  const SEMI_IC = "A semicolon needs a complete independent clause on BOTH sides.";
  const COLON_IC = "A colon needs a complete independent clause BEFORE it.";
  window.ClauseBank.add({
    id: 6,
    short: "Semicolons, Dashes, Colons",
    title: "Punctuation Fundamentals (Semicolon, Dash, Colon)",
    focus: "Paired dashes for non-essential info; semicolons between ICs; colons after an IC to introduce an explanation or a list.",
    rules: [
      "Double dash: set off non-essential appositives or interrupters with a dash on BOTH sides (—like this—). Don't mix a dash with a comma.",
      "Semicolon: joins two independent clauses (IC; IC). It also separates list items that already contain commas.",
      "Colon: comes after a complete IC and introduces a list, a noun, or an explanation of what came before (IC: list/explanation).",
      "No colon after a verb (were:), a preposition (for:), or \"such as\"/\"including\".",
      "A single dash can do a colon's job at the end of an IC (IC—explanation).",
      "No punctuation between a verb and its object (\"concluded that…\").",
    ],
    questions: [
      // Benchmark (Review for Understanding): the closing dash needs an opening dash.
      B("Dash Pair Rule", Q("c6-bm", "Dash pair", "With nearly 12,000 visitors on its first weekend, the Riverbend Festival of Music and ______ or Riverfest, as {{NAME_1}} and most of the town called it—became the largest event the valley had ever hosted.",
        ["Light—","Light:","Light,","Light"], 0,
        "The phrase \"or Riverfest, as {{NAME_1}} and most of the town called it\" ends with a dash, so it must open with a dash. Dashes come in pairs around non-essential information.",
        ["Correct. \"Light—or Riverfest, as… called it—became\": the dashes match.",
          "A colon would split the subject from its verb \"became,\" and it can't pair with the closing dash.",
          "A comma can't pair with the closing dash.",
          "With no opening mark, the closing dash has no partner."])),
      Q("c6-01", "Dash pair", "The museum's most famous ______ a portrait of a woman with a mysterious smile—hangs behind thick bulletproof glass.",
        ["painting—", "painting,", "painting;", "painting:"], 0,
        "The closing dash after \"smile\" needs an opening dash: paired dashes around the appositive.",
        ["Correct. \"painting—a portrait…—hangs\": the dashes match.", "A comma can't pair with a dash.", SEMI_IC, "A colon would separate the subject from its verb \"hangs.\""]),
      Q("c6-02", "Semicolon", "{{NAME_1}} won {{NAME_1_POSS}} first major title at ______ {{NAME_1}} won {{NAME_1_POSS}} last at thirty-five.",
        ["seventeen;", "seventeen,", "seventeen", "seventeen and,"], 0,
        "Two ICs can be joined by a semicolon.",
        ["Correct. Both halves are ICs.", "A comma alone between two ICs is a comma splice.", "Two ICs with no punctuation are a run-on.", "The comma belongs before \"and\", not after it."]),
      Q("c6-03", "Colon + list", "{{NAME_1}}'s kit contained only three ______ a magnifying glass, a notebook, and a pipe.",
        ["items:", "items;", "items, such as:", "items, and"], 0,
        "IC: list. \"{{NAME_1}}'s kit contained only three items\" is complete, so a colon introduces the list.",
        ["Correct.", SEMI_IC + " The list isn't an IC.", "Never put a colon after \"such as.\"", "\"And a magnifying glass…\" makes the list read as extra items."]),
      Q("c6-04", "No colon after 'such as'", "The festival featured dishes such ______ Korean bibimbap, Mexican mole, and Ethiopian injera.",
        ["as", "as:", "as;", "as—"], 0,
        "No punctuation after \"such as\": it already introduces the examples.",
        ["Correct. \"Such as Korean bibimbap…\".", "A colon can't follow \"such as\"; the words before it aren't a complete IC.", SEMI_IC, "A dash would cut \"such as\" off from its examples."]),
      Q("c6-05", "Colon + explanation", "{{NAME_1}} had one reason for staying up all ______ the exam covered material from the entire year.",
        ["night:", "night,", "night", "night, which"], 0,
        "IC: explanation. The second part explains the \"one reason.\"",
        ["Correct. The colon introduces the reason.", "A comma between two ICs is a comma splice.", "Two ICs with no punctuation are a run-on.", "\"Which the exam covered…\" isn't grammatical."]),
      Q("c6-06", "Dash pair", "The robotics club's newest ______ a dog-sized machine that can climb stairs—will compete in the national finals.",
        ["member—", "member,", "member;", "member"], 0,
        DASH_PAIR,
        ["Correct. The dashes match.", "A comma can't close off what a dash opens (or the reverse).", SEMI_IC, "Without an opening dash, \"member a dog-sized machine\" runs together."]),
      Q("c6-07", "Semicolons in a list", "The tour stopped in Tokyo, ______ Seoul, South Korea; and Sydney, Australia.",
        ["Japan;", "Japan,", "Japan:", "Japan"], 0,
        "When list items contain commas, separate the items with semicolons.",
        ["Correct. It matches the semicolon before \"and Sydney.\"", "A comma here blurs where one city's entry ends.", "A colon doesn't separate list items.", "A missing separator runs \"Japan Seoul\" together."]),
      Q("c6-08", "No colon after a verb", "The three finalists ______ {{NAME_1}}, {{NAME_2}}, and {{NAME_3}}.",
        ["were", "were:", "were;", "were—"], 0,
        "Never put a colon or other break between a verb and its complement.",
        ["Correct. \"The three finalists were {{NAME_1}}, {{NAME_2}}, and {{NAME_3}}.\"", "\"The three finalists were\" isn't a complete IC, so no colon.", SEMI_IC, "A dash would split the verb from its complement."]),
      Q("c6-09", "Single dash", "The experiment failed for a simple ______ someone had unplugged the freezer overnight.",
        ["reason—", "reason,", "reason", "reason, and"], 0,
        "After a complete IC, a single dash can introduce an explanation, just like a colon.",
        ["Correct. The dash introduces the explanation.", "A comma between two ICs is a comma splice.", "Two ICs with no punctuation are a run-on.", "\"And\" adds the explanation as if it were a separate event."]),
      Q("c6-10", "DC, IC", "Although the storm knocked out the ______ the concert continued by candlelight.",
        ["power,", "power;", "power:", "power—"], 0,
        "A dependent clause (Although…) is followed by a comma, not a semicolon or colon.",
        ["Correct. DC, IC.", SEMI_IC + " \"Although…\" is dependent.", COLON_IC, "A dash doesn't attach an introductory dependent clause."]),
      Q("c6-11", "Matching pairs", "{{NAME_1}}'s ______ a proud prince named {{NAME_2}}, refused to accept defeat.",
        ["rival,", "rival—", "rival;", "rival:"], 0,
        "The appositive closes with a comma, so it must open with a comma too.",
        ["Correct. \"{{NAME_1}}'s rival, a proud prince named {{NAME_2}}, refused\".", "A dash can't pair with a comma.", SEMI_IC, "A colon would separate the subject from the verb \"refused.\""]),
      Q("c6-12", "Colon + noun", "After months of searching, the archaeologists found what they had been hoping ______ a sealed royal tomb.",
        ["for:", "for;", "for", "for, it was"], 0,
        "IC: noun. The first part is a complete IC, so a colon can introduce the noun it points to.",
        ["Correct. \"…hoping for: a sealed royal tomb.\"", SEMI_IC, "No break makes \"for a sealed royal tomb\" a different, wrong meaning.", "\"It was a sealed royal tomb\" is an IC, so this is a comma splice."]),
      Q("c6-13", "Semicolon", "{{NAME_1}} writes most of {{NAME_1_POSS}} songs on ______ {{NAME_1}} composes the ballads on piano.",
        ["guitar;", "guitar,", "guitar:", "guitar"], 0,
        "Two contrasting ICs: a semicolon.",
        ["Correct. Both halves are ICs.", "A comma alone is a comma splice.", "A colon would mean the second half explains the first; it doesn't, it contrasts.", "Two ICs with no punctuation are a run-on."]),
      Q("c6-14", "Dash pair", "The rover's discovery—traces of ancient ______ excited scientists around the world.",
        ["riverbeds—", "riverbeds,", "riverbeds;", "riverbeds"], 0,
        DASH_PAIR,
        ["Correct. The opening dash after \"discovery\" is closed by this dash.", "A comma can't close what a dash opened.", SEMI_IC, "Without a closing dash, the appositive never ends."]),
      Q("c6-15", "Colon + list", "Every contestant must bring the ______ a recipe card, an apron, and a sharp knife.",
        ["following:", "following;", "following", "following, such as"], 0,
        "\"…must bring the following\" is a complete IC, so a colon introduces the list.",
        ["Correct.", SEMI_IC, "A missing colon runs the list into \"the following.\"", "\"The following, such as…\" is redundant and unclear."]),
      Q("c6-16", "Semicolon + however", "Penguins cannot ______ they are, however, excellent swimmers.",
        ["fly;", "fly,", "fly", "fly, and,"], 0,
        "IC; IC: \"however\" in the middle of the second clause doesn't change that.",
        ["Correct. Both halves are ICs.", "A comma alone between two ICs is a comma splice.", "Two ICs with no punctuation are a run-on.", "The extra comma after \"and\" is incorrect."]),
      Q("c6-17", "No break before object", "The scientists ______ that the glacier had shrunk by forty percent.",
        ["concluded", "concluded:", "concluded;", "concluded—"], 0,
        "No punctuation between a verb and its \"that\" clause.",
        ["Correct.", "\"The scientists concluded\" can't be followed by a colon before its object clause.", SEMI_IC, "A dash would split the verb from its object."]),
      Q("c6-18", "Colon + explanation", "Coach {{NAME_1}} gave {{NAME_1_POSS}} players one simple ______ finish your homework before you touch a basketball.",
        ["rule:", "rule;", "rule", "rule, and"], 0,
        "IC: explanation. The colon introduces what the rule is.",
        ["Correct.", SEMI_IC + " The rule itself is an instruction that explains the first part.", "With no colon, \"rule finish your homework\" runs together.", "\"And finish…\" turns the rule into a separate command."]),
      Q("c6-19", "Dash pair", "The world's oldest known ______ a 4,500-year-old bristlecone pine—grows in California's White Mountains.",
        ["tree—", "tree,", "tree;", "tree:"], 0,
        DASH_PAIR,
        ["Correct.", "A comma can't pair with a dash.", SEMI_IC, "A colon would separate the subject from \"grows.\""]),
      Q("c6-20", "Semicolons in a list", "The panel included {{NAME_1}}, a ______ {{NAME_2}}, a geologist; and {{NAME_3}}, a biologist.",
        ["chemist;", "chemist,", "chemist:", "chemist"], 0,
        "List items with internal commas are separated by semicolons.",
        ["Correct. It matches \"; and {{NAME_3}}.\"", "A comma makes it unclear where each person's entry ends.", "A colon doesn't separate list items.", "A missing separator runs the entries together."]),
      Q("c6-21", "No colon after preposition", "The recipe calls ______ flour, sugar, eggs, and butter.",
        ["for", "for:", "for;", "for—"], 0,
        "No colon after a preposition: \"The recipe calls for\" isn't a complete IC.",
        ["Correct.", COLON_IC, SEMI_IC, "A dash would split the preposition from its object."]),
      Q("c6-22", "Colon + explanation", "{{NAME_1}}'s plan was ______ reach the summit before the storm rolled in.",
        ["simple: reach","simple; reach","simple, reach","simple reach"], 0,
        "\"{{NAME_1}}'s plan was simple\" is a complete IC, and the colon introduces what the plan was.",
        ["Correct. The colon follows a complete clause and introduces the plan itself.",
          "A semicolon needs a complete independent clause on BOTH sides. \"Reach the summit…\" has no subject.",
          "A comma can't introduce an explanation like this.",
          "\"Simple reach\" changes the meaning and leaves \"was\" without its complement."]),
      Q("c6-23", "Colon + list", "{{NAME_1}} noticed three small ______ a torn glove, a muddy cuff, and the faint smell of smoke.",
        ["clues:", "clues;", "clues", "clues, and"], 0,
        "IC: list. A complete independent clause comes before the colon, and the list follows it.",
        ["Correct.", SEMI_IC, "A missing colon runs the list into the IC.", "\"And a torn glove…\" makes the list read as extra items."]),
      Q("c6-24", "Single dash", "After twelve hours of searching, the divers finally found ______ the ship's bell, still engraved with its name.",
        ["it—", "it;", "it", "it, and"], 0,
        "After a complete IC, a dash introduces the noun it refers to.",
        ["Correct. \"…found it—the ship's bell…\".", SEMI_IC, "\"Found it the ship's bell\" runs together.", "\"And the ship's bell\" makes it sound like two separate finds."]),
      Q("c6-25", "Matching commas", "{{NAME_1}}'s album, which was recorded in just three ______ topped the charts for twelve weeks.",
        ["weeks,", "weeks—", "weeks;", "weeks"], 0,
        "A non-essential clause opened with a comma must close with a comma.",
        ["Correct. \"…album, which…weeks, topped\".", "A dash can't close what a comma opened.", SEMI_IC, "Without the closing comma, the clause runs into the main verb."]),
    ],
  });
})();
