// Chapter 7: Appositives & Non-Essential Clauses
(function () {
  const { Q, B } = window.ClauseBank;
  const PAIR = "Non-essential information needs matching punctuation on BOTH sides (comma…comma or dash…dash).";
  window.ClauseBank.add({
    id: 7,
    short: "Appositives",
    title: "Appositives & Non-Essential Clauses",
    focus: "Decide whether information is essential (no commas) or non-essential (set off on both sides).",
    rules: [
      "Essential info identifies WHICH one, so it takes no commas: \"The physicist {{NAME_1}}…\", \"Students who finish early…\".",
      "Non-essential info adds an extra detail; the sentence works without it. Set it off on both sides: \"{{NAME_1}}, a physicist, …\".",
      "\"A/an\" before a description is a strong cue that it's non-essential: \"{{NAME_2}}, a young ninja, …\".",
      "A title placed right before a name, with no \"a/an/the\" (\"author {{NAME_3}}\"), is essential: no commas.",
      "If something is the only one of its kind (\"her first novel\", \"his best friend\"), the name that follows is non-essential: commas.",
      "Use \"which\" with commas for non-essential clauses and \"that\" with no commas for essential ones. Match your pairs: comma–comma, dash–dash.",
    ],
    questions: [
      // Benchmark (Review for Understanding).
      B("Non-Essential Appositive (a/an cue)", Q("c7-01", "Non-essential title", "An industry report led by musicologist {{NAME_2}} at the Brightwater Conservatory of Music found that dedicated fans of {{NAME_1}} who purchase physical vinyl records before a stadium tour have increased streams of a specific re-recorded studio album, ______ due to the unreleased bonus tracks included on the special edition. Fans with these elevated streaming habits were also found to attend multiple concert dates on average.",
        ["Starlight Letters, (Deluxe Edition)", "Starlight Letters (Deluxe Edition)", "Starlight Letters, (Deluxe Edition),", "Starlight Letters (Deluxe Edition),"], 3,
        "\"A specific re-recorded studio album\" (a/an cue) is followed by the album's name as non-essential info, set off by commas on both sides.",
        ["The comma inside the title splits \"(Deluxe Edition)\" from the name, and there's no closing comma.",
          "The opening comma after \"album\" has no matching closing comma.",
          "The comma inside the title wrongly splits the album's name.",
          "Correct. \"…album, Starlight Letters (Deluxe Edition), due to…\": the title is one unit, closed by a comma that matches the one before it."])),
      Q("c7-02", "Essential name", "The physicist ______ discovered a new element with {{NAME_1_POSS}} partner, {{NAME_2}}.",
        ["{{NAME_1}}", "{{NAME_1}},", ", {{NAME_1}},", "—{{NAME_1}},"], 0,
        "\"The physicist\" alone doesn't say which physicist, so the name is essential: no commas.",
        ["Correct. \"The physicist {{NAME_1}} discovered\".", "A single comma separates the subject from its verb.", "Commas would make the name non-essential, but \"the physicist\" needs it to say who.", "A dash can't pair with a comma, and the name is essential."]),
      Q("c7-03", "a/an cue", "______ a composer and actor, wrote many of the musical's songs while riding the subway.",
        ["{{NAME_1}},", "{{NAME_1}}", "{{NAME_1}}—", "{{NAME_1}};"], 0,
        "\"A composer and actor\" is non-essential (a/an cue) and closes with a comma, so it opens with one.",
        ["Correct. \"{{NAME_1}}, a composer and actor, wrote\".", "There's no opening comma to match the closing one.", "A dash can't pair with a comma.", "A semicolon needs an IC on both sides."]),
      Q("c7-04", "Only one of its kind", "The author's debut ______ became a bestseller within a week.",
        ["novel, Glass Harbor,", "novel Glass Harbor,", "novel, Glass Harbor", "novel—Glass Harbor,"], 0,
        "An author has only one debut novel, so its title is extra (non-essential) information: commas on both sides.",
        ["Correct.", "The closing comma has no opening partner.", "The opening comma has no closing partner.", "A dash can't pair with a comma."]),
      Q("c7-05", "who clause after a name", "______ who grew up in Puerto Rico, often blends reggaeton with trap beats.",
        ["{{NAME_1}},", "{{NAME_1}}", "{{NAME_1}}—", "{{NAME_1}};"], 0,
        "A \"who\" clause after a specific name is non-essential: commas on both sides.",
        ["Correct. \"{{NAME_1}}, who grew up…, often blends\".", "There's no opening comma to match the closing one.", "A dash can't pair with a comma.", "A semicolon needs an IC on both sides."]),
      Q("c7-06", "Essential who", "Only the scientists ______ attended both sessions earned the certificate.",
        ["who", ", who", "who,", "—who"], 0,
        "\"Who attended both sessions\" tells WHICH scientists, so it's essential: no commas.",
        ["Correct.", "Commas would make the clause non-essential, but it identifies which scientists.", "A comma after \"who\" splits the clause.", "A dash would make it non-essential and has no partner."]),
      Q("c7-07", "a/an cue", "______ a detective known for {{NAME_1_POSS}} sharp eye, solved the case before the police arrived.",
        ["{{NAME_1}},", "{{NAME_1}}", "{{NAME_1}}—", "{{NAME_1}};"], 0,
        "\"A detective known for…\" is non-essential (a/an cue): commas on both sides.",
        ["Correct.", "There's no opening comma to match the closing one.", "A dash can't pair with a comma.", "A semicolon needs an IC on both sides."]),
      Q("c7-08", "Dash pair", "The striker's secret ______ an hour of extra sprints after every practice—explains her speed in the final minutes.",
        ["weapon—", "weapon,", "weapon", "weapon;"], 0,
        "The closing dash needs an opening dash.",
        ["Correct.", "A comma can't pair with a dash.", "There's no opening dash.", "A semicolon needs an IC on both sides."]),
      Q("c7-09", "Essential title", "{{NAME_1}}'s novel ______ was published when {{NAME_1}} was only twenty.",
        ["Midnight Orchard", "Midnight Orchard,", ", Midnight Orchard,", "—Midnight Orchard—"], 0,
        "{{NAME_1}} wrote several novels, so the title says which one: essential, no commas.",
        ["Correct.", "A single comma separates the subject from its verb.", "Commas would treat the title as extra information, but it's needed to say which novel.", "Dashes would also mark it non-essential."]),
      Q("c7-10", "Only one of its kind", "{{NAME_1}}'s first ______ is still widely read two centuries after its publication.",
        ["novel, Midnight Orchard,", "novel Midnight Orchard,", "novel, Midnight Orchard", "novel—Midnight Orchard,"], 0,
        "{{NAME_1}} had only one first novel, so the title is non-essential: commas on both sides.",
        ["Correct.", "The closing comma has no opening partner.", "The opening comma has no closing partner, and it splits the subject from the verb.", "A dash can't pair with a comma."]),
      Q("c7-11", "which vs that", "The ______ was launched in 2021, can see light from the earliest galaxies.",
        ["telescope, which", "telescope which", "telescope that,", "telescope, that"], 0,
        "A non-essential clause uses \"which\" with commas on both sides.",
        ["Correct. \"The telescope, which was launched in 2021, can see\".", "The closing comma needs an opening partner.", "\"That\" clauses never take commas.", "\"That\" never follows a comma."]),
      Q("c7-12", "Essential that", "The song ______ {{NAME_1}} performed at the opening was written in a single afternoon.",
        ["that", ", that", ", which,", "—that"], 0,
        "\"That {{NAME_1}} performed…\" identifies which song: essential, so no commas.",
        ["Correct.", "\"That\" never follows a comma.", "This breaks the clause and makes it non-essential.", "A dash would make it non-essential and has no partner."]),
      Q("c7-13", "which after comma", "The volcano, ______ last erupted in 1980, is now covered in wildflowers.",
        ["which", "that", "which,", "and it"], 0,
        "Non-essential clause (commas) → \"which\".",
        ["Correct.", "\"That\" can't introduce a non-essential clause set off by commas.", "A comma after \"which\" splits the clause.", "\"And it last erupted…\" leaves the subject \"The volcano\" stranded."]),
      Q("c7-14", "a/an cue", "{{NAME_1}}, ______ ninja who dreams of becoming {{NAME_1_POSS}} village's leader, never gives up on {{NAME_1_POSS}} friends.",
        ["a young", "a, young", "—a young", "a young,"], 0,
        "\"A young ninja…\" is a non-essential appositive already opened by the comma after \"{{NAME_1}}.\"",
        ["Correct.", "There's no comma between \"a\" and its adjective.", "A dash can't follow the opening comma.", "The comma after \"young\" splits the adjective from \"ninja.\""]),
      Q("c7-15", "Essential title", "Best-selling author ______ wrote much of {{NAME_1_POSS}} first book in a café in Edinburgh.",
        ["{{NAME_1}}", "{{NAME_1}},", ", {{NAME_1}},", "{{NAME_1}}—"], 0,
        "A title right before a name with no article (\"author {{NAME_1}}\") is essential: no commas.",
        ["Correct.", "A single comma separates the subject from its verb.", "Commas would cut the name off from its title.", "A single dash separates the subject from its verb."]),
      Q("c7-16", "who clause after a name", "Singer ______ who grew up in Barbados, often returns to visit {{NAME_1_POSS}} family.",
        ["{{NAME_1}},", "{{NAME_1}}", "{{NAME_1}}—", "{{NAME_1}};"], 0,
        "A \"who\" clause after a name is non-essential, and it closes with a comma, so open with one.",
        ["Correct.", "The closing comma has no opening partner.", "A dash can't pair with a comma.", "A semicolon needs an IC on both sides."]),
      Q("c7-17", "Dash pair", "{{NAME_1}}'s ______ mechanical devices that fire synthetic webbing—were built in a high school lab.",
        ["web-shooters—", "web-shooters,", "web-shooters", "web-shooters;"], 0,
        "The closing dash needs an opening dash.",
        ["Correct.", "A comma can't pair with a dash.", "There's no opening dash.", "A semicolon needs an IC on both sides."]),
      Q("c7-18", "Essential who", "The scientist ______ discovered penicillin noticed mold killing bacteria in a dish he had forgotten to clean.",
        ["who", ", who", "—who", "who,"], 0,
        "\"Who discovered penicillin\" tells WHICH scientist: essential, no commas.",
        ["Correct.", "A comma makes it non-essential, and there's no closing comma.", "A dash makes it non-essential, and there's no partner.", "A comma after \"who\" splits the clause."]),
      Q("c7-19", "Non-essential who", "______ discovered a new antibiotic in 1928, noticed mold killing bacteria in a forgotten dish.",
        ["{{NAME_1}}, who", "{{NAME_1}} who", "{{NAME_1}}, that", "{{NAME_1}} who,"], 0,
        "After a specific name, a \"who\" clause is non-essential: commas on both sides.",
        ["Correct.", "The closing comma has no opening partner.", "\"That\" can't follow a comma.", "The comma after \"who\" splits the clause."]),
      Q("c7-20", "Only one of its kind", "{{NAME_1}}'s best ______ a bald monk named {{NAME_2}}, has fought beside {{NAME_1_OBJ}} since childhood.",
        ["friend,", "friend", "friend—", "friend;"], 0,
        "{{NAME_1}} has one best friend, so the description is non-essential and needs commas on both sides.",
        ["Correct.", "The closing comma has no opening partner.", "A dash can't pair with a comma.", "A semicolon needs an IC on both sides."]),
      Q("c7-21", "Matching commas", "The orchestra's conductor, a former ______ insists that every musician learn to sing.",
        ["violinist,", "violinist—", "violinist", "violinist;"], 0,
        PAIR,
        ["Correct. Comma… comma.", "A dash can't close what a comma opened.", "There's no closing comma.", "A semicolon needs an IC on both sides."]),
      Q("c7-22", "Essential name", "The tennis player ______ won the tournament four years in a row.",
        ["{{NAME_1}}", "{{NAME_1}},", ", {{NAME_1}},", "—{{NAME_1}}—"], 0,
        "\"The tennis player\" needs the name to say which one: essential.",
        ["Correct.", "A single comma separates the subject from its verb.", "Commas would mark the name as extra, but it's needed.", "Dashes would also mark it as extra."]),
      Q("c7-23", "a/an cue at the end", "The team named its newest robot after a famous ______ {{NAME_1}}.",
        ["mathematician,", "mathematician", "mathematician;", "mathematician, and"], 0,
        "\"A famous mathematician\" (a/an cue) is followed by the name as a non-essential appositive, set off with a comma.",
        ["Correct.", "With \"a\", the name is extra information and needs a comma.", "A semicolon needs an IC on both sides.", "\"And {{NAME_1}}\" makes it sound like a second person."]),
      Q("c7-24", "Essential that", "The recipe ______ {{NAME_1_POSS}} grandmother keeps in a locked drawer has never been shared outside the family.",
        ["that", ", which", "that,", "—that"], 0,
        "\"That {{NAME_1_POSS}} grandmother keeps…\" identifies which recipe: essential.",
        ["Correct.", "Commas would make it non-essential, and there's no closing comma.", "A comma after \"that\" splits the clause.", "A dash makes it non-essential and has no partner."]),
      Q("c7-25", "a/an cue", "{{NAME_1}}'s loyal ______ a talking donkey, follows {{NAME_1_OBJ}} everywhere.",
        ["companion,", "companion", "companion—", "companion;"], 0,
        "\"A talking donkey\" (a/an cue) is non-essential: commas on both sides.",
        ["Correct.", "The closing comma has no opening partner.", "A dash can't pair with a comma.", "A semicolon needs an IC on both sides."]),
    ],
  });
})();
