// Chapter 1 (extra practice, after the pop-culture set in clause-derby/src/ch1.js): Connecting Independent Clauses.
// IC = independent clause, DC = dependent clause, conj = FANBOYS,
// LW = linking word (however, therefore...). Flexpos = an LW can slide around
// inside its clause, so it can never join two clauses by itself.
window.SatWizz.curriculum.addChapter({
  id: 1,
  short: "Connecting Clauses",
  title: "Connecting Independent Clauses",
  pause: {
    summary: "Two clauses can only be joined in a few legal ways. Figure out what's on each side (IC or DC), then check the connector.",
    rules: [
      "Legal: IC, conj IC · IC; IC · IC. IC · DC, IC · IC DC · IC, DC",
      "Illegal: IC, IC (comma splice) · IC; DC · IC, conj DC · DC, DC (no IC at all)",
      "FANBOYS (for, and, nor, but, or, yet, so) join two ICs only with a comma before them: IC, conj IC.",
      "Linking words (LW) like however, therefore, moreover, nevertheless and instead are Flexpos: they can slide to different spots in a clause. Because they move, they never join clauses on their own. IC, LW, IC is a comma splice. Use IC; LW, IC or IC. LW, IC.",
      "After “; LW,” you still need an IC. IC; LW, DC is illegal.",
    ],
    patterns: [
      { f: "IC, conj IC", ok: true },
      { f: "IC; IC", ok: true },
      { f: "DC, IC", ok: true },
      { f: "IC DC", ok: true },
      { f: "IC, IC", ok: false },
      { f: "IC; DC", ok: false },
      { f: "IC, LW, IC", ok: false },
      { f: "IC; LW, DC", ok: false },
    ],
    example: "{{NAME_1}} practiced daily; however, {{NAME_2}} rested. → IC; LW, IC ✓",
  },
  questions: [
    {
      id: "c2-1", skill: "Comma splices",
      text: "{{NAME_1}} spent the entire summer working on ______ September, even the harshest critics admitted that the effort had paid off.",
      choices: ["{{SKILL}}. By", "{{SKILL}}, by", "{{SKILL}} by", "{{SKILL}} by,"],
      answer: 0,
      notes: [
        "Both sides are ICs. A period is one of the legal ways to separate them.",
        "IC, IC is a comma splice. A comma alone can't join two complete sentences.",
        "No punctuation at all makes a run-on: two ICs crash together.",
        "The comma after “by” splits “by September” and still leaves the two ICs unjoined.",
      ],
    },
    {
      id: "c2-2", skill: "IC, conj IC",
      text: "The crowd at {{LOCATION}} went silent, ______ was about to attempt something no one had seen before.",
      choices: ["and {{NAME_2}}", "{{NAME_2}}", "and, {{NAME_2}}", "{{NAME_2}},"],
      answer: 0,
      notes: [
        "IC, conj IC: the comma is already there, and “and” is the FANBOYS that legally joins the two ICs.",
        "Without a conjunction it's IC, IC, a comma splice.",
        "No comma goes after “and.” The pattern is “, and”, not “, and,”.",
        "A comma between the subject and its verb breaks the second clause. It's still a splice, too.",
      ],
    },
    {
      id: "c2-3", skill: "DC, IC",
      text: "Because {{NAME_1}} had never seen snow ______ winter trip felt like a real adventure.",
      choices: ["before, the", "before the", "before; the", "before: the"],
      answer: 0,
      notes: [
        "The sentence opens with a DC (“Because…”), so it follows DC, IC: a comma, then the main sentence.",
        "With no comma, the DC runs straight into the IC and the reader can't tell where one ends.",
        "IC; IC needs an IC before the semicolon, but “Because…” is a DC.",
        "A colon needs a full IC before it. The part before is only a DC.",
      ],
    },
    {
      id: "c2-4", skill: "IC DC",
      text: "{{NAME_2}} kept practicing ______ the lights at {{LOCATION}} shut off for the night.",
      choices: ["until", "; until", ". Until", ": until"],
      answer: 0,
      notes: [
        "IC DC: when the DC comes second, no punctuation is needed.",
        "IC; DC is illegal. A semicolon needs an IC on both sides.",
        "A period would leave “Until the lights… shut off” as a fragment.",
        "A colon can't introduce a DC that simply adds timing.",
      ],
    },
    {
      id: "c2-5", skill: "IC, conj DC",
      text: "{{NAME_3}} studied the playbook every night, ______ knew every play before {{EVENT}}.",
      choices: ["so {{NAME_3}}", "so because {{NAME_3}}", "because, {{NAME_3}}", "{{NAME_3}}"],
      answer: 0,
      notes: [
        "IC, so IC: “so” is FANBOYS, and both sides are complete sentences.",
        "“So because…” turns the second part into a DC. IC, conj DC is illegal.",
        "“Because,” with a comma after it breaks the clause and isn't a legal connector here.",
        "With nothing but the comma, IC, IC is a comma splice.",
      ],
    },
    {
      id: "c2-6", skill: "IC; IC",
      text: "The first half of {{EVENT}} was ______ second half was a blur of highlights.",
      choices: ["slow; the", "slow, the", "slow the", "slow; while the"],
      answer: 0,
      notes: [
        "Both sides are ICs, so IC; IC works.",
        "IC, IC is a comma splice.",
        "No punctuation creates a run-on.",
        "“; while…” puts a DC after the semicolon. IC; DC is illegal.",
      ],
    },
    {
      id: "c2-7", skill: "DC, DC",
      text: "Although {{NAME_1}} was exhausted after {{EVENT}}, ______",
      choices: [
        "{{NAME_1}} still reviewed the notes from the day.",
        "because the notes from the day still needed review.",
        "which meant reviewing the notes from the day.",
        "while the notes from the day still waited for review.",
      ],
      answer: 0,
      notes: [
        "DC, IC: the “Although…” clause needs a full IC after the comma, and this is one.",
        "DC, DC: “because…” is another dependent clause, so there's no IC anywhere.",
        "“Which…” starts another dependent piece. Still no IC.",
        "“While…” is a DC too. DC, DC never makes a sentence.",
      ],
    },
    {
      id: "c2-8", skill: "IC; LW, DC",
      text: "{{NAME_3}} missed the early ______ still made it to {{LOCATION}} on time.",
      choices: ["bus; however, {{NAME_3}}", "bus, however, {{NAME_3}}", "bus; however, although {{NAME_3}}", "bus however {{NAME_3}}"],
      answer: 0,
      notes: [
        "IC; LW, IC: the semicolon joins the ICs, and “however,” sits in its usual spot.",
        "IC, LW, IC is a comma splice. “However” is Flexpos and can't join clauses.",
        "“; however, although…” makes the second side a DC. IC; LW, DC is illegal.",
        "With no punctuation it's a run-on, and “however” needs a comma after it.",
      ],
    },
    {
      id: "c2-9", skill: "IC, conj IC",
      text: "{{NAME_1}} wanted to rest after the long ______ coach scheduled another practice.",
      choices: ["season, but the", "season, the", "season but, the", "season; but, the"],
      answer: 0,
      notes: [
        "IC, but IC: a comma plus FANBOYS legally joins two complete sentences.",
        "IC, IC is a comma splice.",
        "The comma goes before “but”, not after it.",
        "A semicolon doesn't pair with FANBOYS, and no comma goes after “but.”",
      ],
    },
    {
      id: "c2-10", skill: "IC; IC",
      text: "Tickets for {{EVENT}} sold out in ______ organizers added a second show.",
      choices: ["minutes; the", "minutes, the", "minutes the", "minutes, however, the"],
      answer: 0,
      notes: [
        "Two ICs joined by a semicolon: IC; IC.",
        "IC, IC is a comma splice.",
        "No punctuation makes a run-on.",
        "IC, LW, IC is still a comma splice. “However” can't do the joining.",
      ],
    },
    {
      id: "c2-11", skill: "IC DC",
      text: "{{NAME_2}} skipped dessert ______ {{EVENT}} started early the next morning.",
      choices: ["because", "; because", ". Because", ", however,"],
      answer: 0,
      notes: [
        "IC DC: “because…” is a DC that follows the IC, so it needs no punctuation.",
        "IC; DC is illegal.",
        "A period leaves “Because {{EVENT}} started early…” as a fragment.",
        "IC, LW, IC is a comma splice, and “however” is the wrong logic anyway.",
      ],
    },
    {
      id: "c2-12", skill: "DC, IC",
      text: "When {{NAME_3}} stepped onto the ______ room fell silent.",
      choices: ["stage, the", "stage; the", "stage. The", "stage: the"],
      answer: 0,
      notes: [
        "DC, IC: the “When…” clause ends with a comma, then the IC begins.",
        "A semicolon needs an IC before it, but “When…” is a DC.",
        "A period leaves “When {{NAME_3}} stepped onto the stage.” as a fragment.",
        "A colon needs an IC before it.",
      ],
    },
    {
      id: "c2-13", skill: "IC, LW, IC",
      text: "{{NAME_1}} forgot to set an ______ {{NAME_1}} arrived late to {{LOCATION}}.",
      choices: ["alarm; therefore,", "alarm, therefore,", "alarm, therefore", "alarm therefore,"],
      answer: 0,
      notes: [
        "IC; LW, IC: semicolon before “therefore,” comma after.",
        "IC, LW, IC is a comma splice. “Therefore” can't join clauses.",
        "Still a comma splice, and it's missing the comma after “therefore.”",
        "A run-on: nothing legally separates the two ICs.",
      ],
    },
    {
      id: "c2-14", skill: "Flexpos",
      text: "{{NAME_2}} expected an easy ______ turned out to be the toughest match of the year.",
      choices: ["win; the final, however,", "win, the final, however,", "win; the final however,", "win, the final however"],
      answer: 0,
      notes: [
        "Flexpos in action: “however” slid into the middle of the second IC and is set off by commas. The semicolon does the joining.",
        "Moving “however” doesn't fix the comma splice. IC, IC is still illegal.",
        "A mid-clause “however” needs commas on both sides.",
        "A comma splice, plus “however” is missing its commas.",
      ],
    },
    {
      id: "c2-15", skill: "IC. LW, IC",
      text: "{{NAME_3}} had never lost a home ______ nobody was surprised by the result.",
      choices: ["game. Therefore,", "game, therefore,", "game therefore,", "game; therefore"],
      answer: 0,
      notes: [
        "IC. LW, IC: the period separates the ICs, and “Therefore,” opens the second one.",
        "IC, LW, IC is a comma splice.",
        "A run-on: nothing separates the two ICs.",
        "The semicolon is right, but “therefore” needs a comma after it.",
      ],
    },
    {
      id: "c2-16", skill: "IC, conj IC",
      text: "The bus broke down on the ______ everyone walked the last mile to {{LOCATION}}.",
      choices: ["highway, so", "highway so", "highway, so, since", "highway; so"],
      answer: 0,
      notes: [
        "IC, so IC: a comma plus FANBOYS joins the two ICs.",
        "Joining two ICs with FANBOYS needs a comma before it.",
        "“So, since…” makes the second part a DC. IC, conj DC is illegal.",
        "A semicolon plus FANBOYS isn't one of the legal patterns.",
      ],
    },
    {
      id: "c2-17", skill: "IC; DC",
      text: "{{NAME_2}} kept ______ the cheering at {{LOCATION}} grew louder.",
      choices: ["running as", "running; as", "running. As", "running: as"],
      answer: 0,
      notes: [
        "IC DC: “as the cheering grew louder” is a DC after the IC, so it needs no punctuation.",
        "IC; DC is illegal.",
        "A period leaves the “As…” part as a fragment.",
        "A colon can't introduce a DC like this.",
      ],
    },
    {
      id: "c2-18", skill: "DC, IC",
      text: "______ {{NAME_3}} missed the first half, the team still won.",
      choices: ["Although", "Although,", "However,", "Despite"],
      answer: 0,
      notes: [
        "“Although {{NAME_3}} missed the first half” is a DC, followed by a comma and an IC: DC, IC.",
        "No comma goes right after “Although.”",
        "“However, {{NAME_3}} missed the first half, the team still won” is IC, IC, a comma splice.",
        "“Despite” needs a noun (“despite the rain”), not a full clause.",
      ],
    },
    {
      id: "c2-19", skill: "Flexpos",
      text: "Most people rest after {{EVENT}}; ______ went straight back to {{LOCATION}}.",
      choices: ["{{NAME_1}}, however,", "however {{NAME_1}}", "{{NAME_1}} however,", "{{NAME_1}}, however"],
      answer: 0,
      notes: [
        "The semicolon joins the ICs, and Flexpos “however” sits inside the second IC with commas on both sides.",
        "An opening “however” needs a comma after it.",
        "A mid-clause “however” needs a comma before it too.",
        "A mid-clause “however” needs a comma after it too.",
      ],
    },
    {
      id: "c2-20", skill: "IC, conj IC",
      text: "{{NAME_2}} finished the first draft on ______ revised it all weekend.",
      choices: ["Friday, and {{NAME_2}}", "Friday, {{NAME_2}}", "Friday and, {{NAME_2}}", "Friday; and {{NAME_2}}"],
      answer: 0,
      notes: [
        "IC, and IC: a comma plus FANBOYS joins the two ICs.",
        "IC, IC is a comma splice.",
        "The comma belongs before “and”, not after it.",
        "A semicolon doesn't pair with FANBOYS.",
      ],
    },
  ],
});
