// Bonus chapter 10: Pronouns & Possessives. Unlocks after Chapter 9.
((window.SatWizz = window.SatWizz || {}).chapterData = window.SatWizz.chapterData || []).push({
  id: 10,
  bonus: true,
  short: "Pronouns & Possessives",
  title: "Bonus: Pronouns & Possessives",
  pause: {
    summary: "Apostrophes show ownership, not plurals. Pronouns must match the noun they replace and play the right role in the sentence.",
    rules: [
      "One owner: add 's ({{NAME_1}}'s). Plural owners: make it plural, then add the apostrophe (twins').",
      "Plain plurals never take an apostrophe (three records).",
      "It's = it is. Its = belonging to it. “Its'” is never correct.",
      "Pronoun case: cover the other person to test it. “Chose me” works, so “chose {{NAME_2}} and me” is right.",
      "Who for subjects, whom for objects (and after prepositions), whose for ownership.",
    ],
    patterns: [
      { f: "the players' lockers", ok: true },
      { f: "three record's", ok: false },
      { f: "The team lost its captain.", ok: true },
    ],
    example: "To whom did {{NAME_1}} give the twins' jerseys?",
  },
  questions: [
    {
      id: "c10-1", skill: "Plural possessives",
      text: "Both of the ______ jerseys were signed by {{NAME_1}} after the game.",
      choices: ["twins'", "twin's", "twins", "twins's"],
      answer: 0,
      notes: [
        "Two twins own the jerseys, so make it plural first (twins), then add the apostrophe.",
        "“Twin's” means one twin, but “both” means two.",
        "No apostrophe means no ownership.",
        "Never add 's to a plural that already ends in s.",
      ],
    },
    {
      id: "c10-2", skill: "Its vs. it's",
      text: "The committee announced that ______ new captain would be {{NAME_3}}.",
      choices: ["its", "it's", "their", "its'"],
      answer: 0,
      notes: [
        "One committee owns the captain, so use “its.”",
        "“It's” means “it is.”",
        "“Committee” is singular, so “their” doesn't match.",
        "“Its'” isn't a word.",
      ],
    },
    {
      id: "c10-3", skill: "Singular possessives",
      text: "Everyone admired ______ determination to finish despite the pouring rain.",
      choices: ["{{NAME_1}}'s", "{{NAME_1}}s", "{{NAME_1}}s'", "{{NAME_1}}"],
      answer: 0,
      notes: [
        "One owner: add apostrophe + s.",
        "That's a plural, not a possessive.",
        "A plural possessive, but there's only one person.",
        "It needs the possessive form.",
      ],
    },
    {
      id: "c10-4", skill: "Plurals",
      text: "By the end of the year, {{NAME_2}} had broken three long-standing ______",
      choices: ["records.", "record's.", "records'.", "record."],
      answer: 0,
      notes: [
        "A plain plural. Nothing belongs to the records.",
        "An apostrophe wrongly shows ownership.",
        "An apostrophe wrongly shows ownership.",
        "“Three” needs a plural.",
      ],
    },
    {
      id: "c10-5", skill: "Pronoun agreement",
      text: "When {{NAME_1}} and {{NAME_2}} finished the project, the teacher praised ______ for their careful research.",
      choices: ["them", "him", "her", "us"],
      answer: 0,
      notes: [
        "Two people need a plural pronoun: “them.”",
        "Singular, but there are two people.",
        "Singular, but there are two people.",
        "“Us” would include the writer, who isn't part of the story.",
      ],
    },
    {
      id: "c10-6", skill: "Pronoun agreement",
      text: "The fans waved ______ scarves as {{NAME_1}} walked out at {{LOCATION}}.",
      choices: ["their", "its", "his or her", "there"],
      answer: 0,
      notes: [
        "“Fans” is plural, so use “their.”",
        "“Its” is singular and refers to things.",
        "Singular, but “fans” is plural.",
        "“There” is a place, not ownership.",
      ],
    },
    {
      id: "c10-7", skill: "Pronoun case",
      text: "The coach chose {{NAME_2}} and ______ to lead the warm-up before {{EVENT}}.",
      choices: ["me", "I", "myself", "mine"],
      answer: 0,
      notes: [
        "Cover “{{NAME_2}} and”: “chose me.” It's the object form.",
        "“Chose I” is wrong. “I” is a subject form.",
        "“Myself” only works when the subject is also “I.”",
        "“Mine” shows ownership.",
      ],
    },
    {
      id: "c10-8", skill: "Who / whom / whose",
      text: "The mentor to ______ {{NAME_1}} owed the most was a retired teacher from the neighborhood.",
      choices: ["whom", "who", "which", "what"],
      answer: 0,
      notes: [
        "After a preposition (“to”), use the object form “whom.”",
        "“Who” is the subject form.",
        "“Which” is for things, not people.",
        "“What” doesn't fit here.",
      ],
    },
    {
      id: "c10-9", skill: "Who / whom / whose",
      text: "{{NAME_1}} is the kind of teammate ______ encouragement makes everyone around {{NAME_1_OBJ}} better.",
      choices: ["whose", "who's", "who is", "which"],
      answer: 0,
      notes: [
        "The encouragement belongs to the teammate, so use the possessive “whose.”",
        "“Who's” means “who is.”",
        "“Who is encouragement…” makes no sense.",
        "“Which” is for things.",
      ],
    },
    {
      id: "c10-10", skill: "Plural possessives",
      text: "All of the ______ lockers were covered with posters of {{NAME_1}}.",
      choices: ["players'", "player's", "players", "players's"],
      answer: 0,
      notes: [
        "Many players own lockers, so it's a plural possessive.",
        "That's only one player.",
        "It needs to show ownership.",
        "Never add 's to a plural ending in s.",
      ],
    },
  ],
});
