// Chapter 3: Subject-Verb Agreement.
// Questions tagged with `shortcut` follow the answer-choice ratio checks
// taught in the lesson; `forms` marks each choice: s = singular verb,
// p = plural verb, x = non-verb. The content check in questions.js verifies
// that the odd one out really is the answer.
((window.SatWizz = window.SatWizz || {}).chapterData = window.SatWizz.chapterData || []).push({
  id: 3,
  short: "Subject-Verb Agreement",
  title: "Subject-Verb Agreement",
  pause: {
    summary: "Singular subjects take singular verbs (is, has, runs), and plural subjects take plural verbs (are, have, run). The trap is that the SAT hides the real subject.",
    rules: [
      "Cross out prepositional phrases (of the…, in the…, with the…, from the…) between the subject and the verb. The subject is never inside one. “The box [of pens] is.”",
      "“Along with,” “as well as” and “together with” don't make a subject plural.",
      "“And” makes a plural subject. With either/or and neither/nor, the verb matches the closer subject.",
      "Each, every, one, a list, a group and a collection are singular.",
      "In “There is/are…” and flipped sentences, the subject comes after the verb.",
      "3:1 shortcut: if three choices are plural verbs and one is singular (or three singular and one plural), the odd one out is the answer.",
      "2:1 shortcut: in a verb spot, cross out the choice that isn't a verb. Of the three left, two will match (both singular or both plural). The odd one is the answer.",
    ],
    patterns: [
      { f: "The box [of pens] is", ok: true },
      { f: "The box [of pens] are", ok: false },
      { f: "3:1 → has / have / are / were → has", ok: true },
      { f: "2:1 → sits / sitting / sit / are sitting → sits", ok: true },
    ],
    example: "The list [of {{NAME_1_POSS}} goals] is taped to the mirror.",
  },
  questions: [
    {
      id: "c3-1", skill: "Prepositional traps", shortcut: "3:1", forms: ["s", "p", "p", "p"],
      text: "The collection of trophies in {{NAME_1_POSS}} display cabinet ______ grown every single year.",
      choices: ["has", "have", "are", "were"],
      answer: 0,
      notes: [
        "Cross out “of trophies in … cabinet” and the subject is “collection,” which is singular. It takes “has.” (3:1: the only singular choice.)",
        "“Have” is plural. It matches “trophies,” which is the trap inside the prepositional phrase.",
        "“Are” is plural, and “are grown” also changes the meaning.",
        "“Were” is plural and past tense. It doesn't match “collection.”",
      ],
    },
    {
      id: "c3-2", skill: "Compound subjects", shortcut: "3:1", forms: ["p", "s", "s", "s"],
      text: "{{NAME_1}} and {{NAME_2}} ______ been friends since their very first day at {{LOCATION}}.",
      choices: ["have", "has", "is", "was"],
      answer: 0,
      notes: [
        "Two people joined by “and” make a plural subject, so use “have.” (3:1: the only plural choice.)",
        "“Has” is singular, but the subject is two people.",
        "“Is” is singular, and “is been” isn't a verb form.",
        "“Was” is singular, and “was been” isn't a verb form.",
      ],
    },
    {
      id: "c3-3", skill: "Either/or, neither/nor", shortcut: "3:1", forms: ["p", "s", "s", "s"],
      text: "Neither {{NAME_1}} nor {{NAME_2}}'s teammates ______ ready for the surprise announcement.",
      choices: ["were", "was", "is", "has been"],
      answer: 0,
      notes: [
        "With neither/nor, match the closer subject. “Teammates” is plural, so use “were.”",
        "“Was” matches {{NAME_1}}, but that's the farther subject.",
        "“Is” is singular and switches to present tense.",
        "“Has been” is singular. It doesn't match “teammates.”",
      ],
    },
    {
      id: "c3-4", skill: "Each / every", shortcut: "3:1", forms: ["s", "p", "p", "p"],
      text: "Each of the practice drills that {{NAME_3}} designed ______ a specific weakness.",
      choices: ["targets", "target", "are targeting", "have targeted"],
      answer: 0,
      notes: [
        "“Each” is the subject and it's singular, so use “targets.”",
        "“Target” is plural. It matches “drills,” which sits inside “of the practice drills.”",
        "“Are targeting” is plural.",
        "“Have targeted” is plural.",
      ],
    },
    {
      id: "c3-5", skill: "Flipped sentences", shortcut: "3:1", forms: ["s", "p", "p", "p"],
      text: "At the back of the room ______ a stack of old notebooks that once belonged to {{NAME_1}}.",
      choices: ["sits", "sit", "are sitting", "have sat"],
      answer: 0,
      notes: [
        "Flip it: “A stack … sits at the back of the room.” The subject “stack” is singular.",
        "“Sit” is plural. It matches “notebooks,” the trap.",
        "“Are sitting” is plural.",
        "“Have sat” is plural.",
      ],
    },
    {
      id: "c3-6", skill: "Along with", shortcut: "3:1", forms: ["s", "p", "p", "p"],
      text: "{{NAME_1}}, along with {{NAME_2}} and {{NAME_3}}, ______ planning a surprise for the coach.",
      choices: ["is", "are", "were", "have been"],
      answer: 0,
      notes: [
        "“Along with…” is extra. The subject is still just {{NAME_1}}, so use “is.”",
        "“Are” treats the “along with” names as part of the subject. They aren't.",
        "“Were” is plural.",
        "“Have been” is plural.",
      ],
    },
    {
      id: "c3-7", skill: "There is / there are", shortcut: "3:1", forms: ["p", "s", "s", "s"],
      text: "There ______ several reasons why {{NAME_2}} decided to switch positions this season.",
      choices: ["were", "was", "is", "has been"],
      answer: 0,
      notes: [
        "In a “there” sentence the subject comes after the verb. “Several reasons” is plural, so use “were.”",
        "“Was” is singular.",
        "“Is” is singular.",
        "“Has been” is singular.",
      ],
    },
    {
      id: "c3-8", skill: "Prepositional traps", shortcut: "2:1", forms: ["s", "x", "p", "p"],
      text: "The box of old trophies from {{NAME_1_POSS}} early seasons ______ in the attic.",
      choices: ["sits", "sitting", "sit", "are sitting"],
      answer: 0,
      notes: [
        "Cross out “of old trophies from … seasons.” The subject is “box,” which is singular: “sits.” (2:1: drop “sitting,” then the odd one out.)",
        "“Sitting” isn't a verb on its own, so the sentence would have no main verb.",
        "“Sit” is plural. It matches “trophies,” the trap.",
        "“Are sitting” is plural.",
      ],
    },
    {
      id: "c3-9", skill: "Prepositional traps", shortcut: "2:1", forms: ["p", "s", "s", "x"],
      text: "The members of the band that {{NAME_2}} joined last year ______ at {{LOCATION}} every Friday.",
      choices: ["rehearse", "rehearses", "has rehearsed", "rehearsing"],
      answer: 0,
      notes: [
        "The subject is “members,” which is plural, so use “rehearse.” (2:1: drop “rehearsing,” then the odd one out.)",
        "“Rehearses” is singular. It matches “band,” the trap.",
        "“Has rehearsed” is singular.",
        "“Rehearsing” isn't a verb on its own.",
      ],
    },
    {
      id: "c3-10", skill: "One of", shortcut: "3:1", forms: ["s", "p", "p", "p"],
      text: "One of the paintings in {{NAME_3_POSS}} collection ______ over a hundred years old.",
      choices: ["is", "are", "were", "have been"],
      answer: 0,
      notes: [
        "The subject is “One,” which is singular, so use “is.”",
        "“Are” matches “paintings,” which is inside “of the paintings.”",
        "“Were” is plural.",
        "“Have been” is plural.",
      ],
    },
    {
      id: "c3-11", skill: "Prepositional traps", shortcut: "3:1", forms: ["p", "s", "s", "s"],
      text: "The results of the survey that {{NAME_1}} conducted at {{LOCATION}} ______ surprising.",
      choices: ["were", "was", "is", "has been"],
      answer: 0,
      notes: [
        "Cross out “of the survey…” and the subject is “results,” which is plural. Use “were.”",
        "“Was” matches “survey,” the trap.",
        "“Is” is singular.",
        "“Has been” is singular.",
      ],
    },
    {
      id: "c3-12", skill: "Either/or, neither/nor", shortcut: "3:1", forms: ["s", "p", "p", "p"],
      text: "Neither the coaches nor {{NAME_2}} ______ ready to give up.",
      choices: ["was", "were", "are", "have been"],
      answer: 0,
      notes: [
        "Match the closer subject, {{NAME_2}}, one person. So use “was.”",
        "“Were” matches “coaches,” the farther subject.",
        "“Are” is plural.",
        "“Have been” is plural.",
      ],
    },
    {
      id: "c3-13", skill: "Collective nouns", shortcut: "3:1", forms: ["s", "p", "p", "p"],
      text: "A list of tips for getting better at {{SKILL}} ______ taped to the wall.",
      choices: ["is", "are", "were", "have been"],
      answer: 0,
      notes: [
        "The subject is “list,” which is singular, so use “is.”",
        "“Are” matches “tips,” the trap.",
        "“Were” is plural.",
        "“Have been” is plural.",
      ],
    },
    {
      id: "c3-14", skill: "Prepositional traps", shortcut: "2:1", forms: ["p", "s", "s", "x"],
      text: "The students in {{NAME_3_POSS}} study group ______ every Tuesday.",
      choices: ["meet", "meets", "has met", "meeting"],
      answer: 0,
      notes: [
        "The subject is “students,” which is plural, so use “meet.” (2:1: drop “meeting,” then the odd one out.)",
        "“Meets” matches “group,” the trap.",
        "“Has met” is singular.",
        "“Meeting” isn't a verb on its own.",
      ],
    },
    {
      id: "c3-15", skill: "Flipped sentences", shortcut: "3:1", forms: ["p", "s", "s", "s"],
      text: "Behind the stage at {{LOCATION}} ______ two old pianos.",
      choices: ["stand", "stands", "has stood", "is standing"],
      answer: 0,
      notes: [
        "Flip it: “Two old pianos stand behind the stage.” The subject is plural.",
        "“Stands” is singular.",
        "“Has stood” is singular.",
        "“Is standing” is singular.",
      ],
    },
    {
      id: "c3-16", skill: "Along with", shortcut: "3:1", forms: ["s", "p", "p", "p"],
      text: "{{NAME_1}}, together with the rest of the team, ______ for {{EVENT}} every morning.",
      choices: ["trains", "train", "are training", "have trained"],
      answer: 0,
      notes: [
        "“Together with…” doesn't change the subject. {{NAME_1}} is one person, so use “trains.”",
        "“Train” is plural.",
        "“Are training” is plural.",
        "“Have trained” is plural.",
      ],
    },
    {
      id: "c3-17", skill: "Each / every", shortcut: "3:1", forms: ["s", "p", "p", "p"],
      text: "Every one of the tickets for {{EVENT}} ______ sold within an hour.",
      choices: ["was", "were", "have been", "are"],
      answer: 0,
      notes: [
        "“Every one” is singular, so use “was.”",
        "“Were” matches “tickets,” the trap.",
        "“Have been” is plural.",
        "“Are” is plural and switches to present tense.",
      ],
    },
    {
      id: "c3-18", skill: "Prepositional traps", shortcut: "2:1", forms: ["s", "p", "x", "p"],
      text: "The noise from the crowds outside {{LOCATION}} ______ it hard to focus.",
      choices: ["makes", "make", "making", "are making"],
      answer: 0,
      notes: [
        "The subject is “noise,” which is singular, so use “makes.” (2:1: drop “making,” then the odd one out.)",
        "“Make” matches “crowds,” the trap.",
        "“Making” isn't a verb on its own.",
        "“Are making” is plural.",
      ],
    },
    {
      id: "c3-19", skill: "Prepositional traps", shortcut: "3:1", forms: ["p", "s", "s", "s"],
      text: "The pages of {{NAME_1_POSS}} notebook ______ covered in formulas.",
      choices: ["are", "is", "was", "has been"],
      answer: 0,
      notes: [
        "The subject is “pages,” which is plural, so use “are.”",
        "“Is” matches “notebook,” the trap.",
        "“Was” is singular.",
        "“Has been” is singular.",
      ],
    },
    {
      id: "c3-20", skill: "Either/or, neither/nor", shortcut: "2:1", forms: ["p", "s", "x", "s"],
      text: "Either the captain or the players ______ going to speak at {{EVENT}}.",
      choices: ["are", "is", "being", "was"],
      answer: 0,
      notes: [
        "Match the closer subject, “players,” which is plural. Use “are.” (2:1: drop “being,” then the odd one out.)",
        "“Is” matches “captain,” the farther subject.",
        "“Being” isn't a verb on its own.",
        "“Was” is singular.",
      ],
    },
  ],
});
