// Chapter 3 (extra practice, after the pop-culture set in clause-derby/src/ch3.js): Verb vs. Non-Verb Identification.
// `shortcut: "2:1"` marks verb-spot questions where the 2:1 ratio check works
// (see ch3.js for the `forms` codes).
window.SatWizz.curriculum.addChapter({
  id: 3,
  short: "Verb vs. Non-Verb",
  title: "Verb vs. Non-Verb Identification",
  pause: {
    summary: "Every sentence needs one main verb, a real action with a tense (ran, is, practices). Before you pick, ask: does this sentence already have its main verb?",
    rules: [
      "Main verbs have a tense and can stand alone with a subject: {{NAME_1}} practiced / is practicing / practices.",
      "Non-verbs can't be the main verb: -ing words (practicing), “to” words (to practice) and “having + verb” (having practiced).",
      "No main verb yet? The blank needs a main verb.",
      "Already has a main verb? The blank usually needs a non-verb that adds detail. A second main verb after a comma creates a splice.",
      "Skip interrupters set off by commas (“, hoping to win,”) to find the subject and its verb.",
      "2:1 shortcut in a verb spot: cross out the non-verb. Two of the remaining three will match in number. The odd one is the answer.",
    ],
    patterns: [
      { f: "{{NAME_1}}, hoping to win, trained.", ok: true },
      { f: "{{NAME_1}}, hoping to win, training.", ok: false },
      { f: "{{NAME_1}} stayed late, reviewing notes.", ok: true },
      { f: "{{NAME_1}} stayed late, reviewed notes.", ok: false },
    ],
    example: "{{NAME_1}}, hoping to win, trained daily. → main verb: trained",
  },
  questions: [
    {
      id: "c4-1", skill: "Main verb needed",
      text: "{{NAME_1}}, hoping to impress the judges at {{EVENT}}, ______ a routine no one had tried before.",
      choices: ["performed", "performing", "to perform", "having performed"],
      answer: 0,
      notes: [
        "Skip “hoping to impress…” and you get “{{NAME_1}} performed a routine.” That's the main verb the sentence needs.",
        "“Performing” is an -ing non-verb, so the sentence would have no main verb.",
        "“To perform” is a “to” form, not a main verb.",
        "“Having performed” is a non-verb. The sentence would still be missing its main verb.",
      ],
    },
    {
      id: "c4-2", skill: "Main verb needed",
      text: "Determined to improve at {{SKILL}}, {{NAME_2}} ______ extra practice every weekend.",
      choices: ["scheduled", "scheduling", "to schedule", "having scheduled"],
      answer: 0,
      notes: [
        "The opener describes {{NAME_2}}. Then {{NAME_2}} needs a main verb: “scheduled.”",
        "“Scheduling” is a non-verb, so the sentence is a fragment.",
        "“To schedule” can't be the main verb.",
        "“Having scheduled” is a non-verb, so there's still no main verb.",
      ],
    },
    {
      id: "c4-3", skill: "Non-verb needed",
      text: "{{NAME_3}} stayed late at {{LOCATION}}, ______ every mistake from the morning session.",
      choices: ["reviewing", "reviewed", "reviews", "has reviewed"],
      answer: 0,
      notes: [
        "The main verb is already “stayed.” The part after the comma adds detail, so it takes the non-verb “reviewing.”",
        "“Reviewed” adds a second main verb after a comma, which is a splice.",
        "“Reviews” is a second main verb and also shifts tense.",
        "“Has reviewed” is a second main verb after a comma.",
      ],
    },
    {
      id: "c4-4", skill: "Non-verb needed",
      text: "The goal of the new schedule is ______ more time for {{SKILL}}.",
      choices: ["to create", "creates", "created", "has created"],
      answer: 0,
      notes: [
        "The main verb is “is.” What follows names the goal, so it takes “to create.”",
        "“Is creates” stacks two main verbs.",
        "“Is created” changes the meaning: the goal isn't being created.",
        "“Is has created” stacks two main verbs.",
      ],
    },
    {
      id: "c4-5", skill: "Non-verb needed",
      text: "The volunteers ______ at {{LOCATION}} every Saturday include {{NAME_1}} and {{NAME_2}}.",
      choices: ["working", "work", "works", "have worked"],
      answer: 0,
      notes: [
        "The main verb is “include.” “Working at…” is a non-verb that tells which volunteers.",
        "“Work” adds a second main verb: “The volunteers work … include” doesn't work.",
        "“Works” is a second main verb, and it's singular too.",
        "“Have worked” is a second main verb.",
      ],
    },
    {
      id: "c4-6", skill: "Main verb needed",
      text: "{{NAME_2}}'s plan for {{EVENT}} ______ simple: practice a little every day.",
      choices: ["was", "being", "to be", "having been"],
      answer: 0,
      notes: [
        "“Plan” needs a main verb, and “was” is the only one. A colon also needs a complete sentence before it.",
        "“Being” is a non-verb, so it leaves a fragment.",
        "“To be” is a “to” form.",
        "“Having been” is a non-verb.",
      ],
    },
    {
      id: "c4-7", skill: "Non-verb needed",
      text: "Before {{EVENT}}, {{NAME_3}} practiced for hours, ______ each move until it felt automatic.",
      choices: ["repeating", "repeated", "repeats", "and repeating"],
      answer: 0,
      notes: [
        "“Practiced” is the main verb. “Repeating…” is a non-verb that describes how.",
        "“Repeated” adds a second main verb after a comma, which is a splice.",
        "“Repeats” is a second main verb in the wrong tense.",
        "“And repeating” pairs a main verb with a non-verb, so it isn't parallel.",
      ],
    },
    {
      id: "c4-8", skill: "Main verb needed", shortcut: "2:1", forms: ["p", "s", "x", "s"],
      text: "The students, hoping to finish before {{EVENT}}, ______ late at {{LOCATION}}.",
      choices: ["stay", "stays", "staying", "has stayed"],
      answer: 0,
      notes: [
        "Skip the interrupter. “The students stay late” needs a plural main verb. (2:1: drop “staying,” then the odd one out.)",
        "“Stays” is singular, but “students” is plural.",
        "“Staying” is a non-verb, so the sentence has no main verb.",
        "“Has stayed” is singular.",
      ],
    },
    {
      id: "c4-9", skill: "Main verb needed",
      text: "Excited about the trip to {{LOCATION}}, {{NAME_1}} ______ {{NAME_1_POSS}} bag the night before.",
      choices: ["packed", "packing", "to pack", "having packed"],
      answer: 0,
      notes: [
        "{{NAME_1}} needs a main verb: “packed.”",
        "“Packing” is a non-verb, so it leaves a fragment.",
        "“To pack” can't be the main verb.",
        "“Having packed” is a non-verb.",
      ],
    },
    {
      id: "c4-10", skill: "Non-verb needed",
      text: "{{NAME_2}} opened the letter slowly, ______ that it contained good news.",
      choices: ["hoping", "hoped", "hopes", "and hopes"],
      answer: 0,
      notes: [
        "“Opened” is the main verb. “Hoping…” adds how {{NAME_2}} felt without a second verb.",
        "“Hoped” after a comma makes a second main verb, which is a splice.",
        "“Hopes” is a second main verb in the wrong tense.",
        "“And hopes” shifts from past to present tense.",
      ],
    },
    {
      id: "c4-11", skill: "Non-verb needed",
      text: "{{NAME_3}} went to {{LOCATION}} early ______ a good seat.",
      choices: ["to get", "gets", "got", "has gotten"],
      answer: 0,
      notes: [
        "“Went” is the main verb. “To get” explains why, and it's a non-verb.",
        "“Went early gets” stacks two main verbs.",
        "“Went early got” stacks two main verbs.",
        "“Has gotten” is a second main verb.",
      ],
    },
    {
      id: "c4-12", skill: "Main verb needed", shortcut: "2:1", forms: ["s", "p", "x", "p"],
      text: "The coach who trained {{NAME_1}} and {{NAME_2}} ______ at {{EVENT}} last year.",
      choices: ["was honored", "were honored", "being honored", "have been honored"],
      answer: 0,
      notes: [
        "The subject is “the coach,” one person, so it takes the singular main verb “was honored.” (2:1: drop “being honored,” then the odd one out.)",
        "“Were” is plural. It matches the two names, which aren't the subject.",
        "“Being honored” is a non-verb, so it leaves a fragment.",
        "“Have been” is plural.",
      ],
    },
    {
      id: "c4-13", skill: "Main verb needed",
      text: "The best way to get better at {{SKILL}} ______ to practice a little every day.",
      choices: ["is", "being", "to be", "having been"],
      answer: 0,
      notes: [
        "“The best way” needs a main verb: “is.”",
        "“Being” is a non-verb.",
        "“To be” is a “to” form.",
        "“Having been” is a non-verb.",
      ],
    },
    {
      id: "c4-14", skill: "Non-verb needed",
      text: "Tired from {{EVENT}}, {{NAME_2}} sat on the bench, ______ at the empty field.",
      choices: ["staring", "stared", "stares", "and stares"],
      answer: 0,
      notes: [
        "“Sat” is the main verb. “Staring…” adds detail as a non-verb.",
        "“Stared” is a second main verb after a comma, which is a splice.",
        "“Stares” is a second main verb in the wrong tense.",
        "“And stares” shifts tense.",
      ],
    },
    {
      id: "c4-15", skill: "Non-verb needed",
      text: "The flyers ______ on every wall at {{LOCATION}} announced the date of {{EVENT}}.",
      choices: ["posted", "were posted", "are posted", "have posted"],
      answer: 0,
      notes: [
        "The main verb is “announced.” “Posted on every wall” is a non-verb that tells which flyers.",
        "“Were posted” adds a second main verb.",
        "“Are posted” adds a second main verb in present tense.",
        "“Have posted” is a second main verb, and it says the flyers did the posting.",
      ],
    },
    {
      id: "c4-16", skill: "Main verb needed", shortcut: "2:1", forms: ["s", "p", "x", "p"],
      text: "{{NAME_3}}, along with two classmates, ______ a new club for students interested in {{SKILL}}.",
      choices: ["has started", "have started", "starting", "were starting"],
      answer: 0,
      notes: [
        "The subject is {{NAME_3}} (“along with” doesn't count), so it takes a singular main verb: “has started.” (2:1: drop “starting,” then the odd one out.)",
        "“Have started” is plural.",
        "“Starting” is a non-verb, so it leaves a fragment.",
        "“Were starting” is plural.",
      ],
    },
    {
      id: "c4-17", skill: "Main verb needed",
      text: "{{NAME_1}} ______ for hours before finally solving the problem.",
      choices: ["struggled", "struggling", "to struggle", "having struggled"],
      answer: 0,
      notes: [
        "{{NAME_1}} needs a main verb: “struggled.”",
        "“Struggling” is a non-verb.",
        "“To struggle” is a “to” form.",
        "“Having struggled” is a non-verb.",
      ],
    },
    {
      id: "c4-18", skill: "Main verb needed",
      text: "Having finished the essay early, {{NAME_2}} ______ the rest of the evening reading.",
      choices: ["spent", "spending", "to spend", "having spent"],
      answer: 0,
      notes: [
        "“Having finished…” is the non-verb opener. {{NAME_2}} still needs the main verb “spent.”",
        "“Spending” is a non-verb.",
        "“To spend” is a “to” form.",
        "“Having spent” is another non-verb.",
      ],
    },
    {
      id: "c4-19", skill: "Main verb needed", shortcut: "2:1", forms: ["p", "s", "x", "s"],
      text: "The players on {{NAME_3_POSS}} team ______ together before every game.",
      choices: ["huddle", "huddles", "huddling", "has huddled"],
      answer: 0,
      notes: [
        "The subject is “players,” which is plural. It needs the plural main verb “huddle.” (2:1: drop “huddling,” then the odd one out.)",
        "“Huddles” matches “team,” the trap.",
        "“Huddling” is a non-verb.",
        "“Has huddled” is singular.",
      ],
    },
    {
      id: "c4-20", skill: "Non-verb needed",
      text: "The band played for hours at {{LOCATION}}, ______ the crowd dancing until midnight.",
      choices: ["keeping", "kept", "keeps", "and keeps"],
      answer: 0,
      notes: [
        "“Played” is the main verb. “Keeping…” adds the result as a non-verb.",
        "“Kept” after a comma is a second main verb, which is a splice.",
        "“Keeps” is a second main verb in the wrong tense.",
        "“And keeps” shifts to present tense.",
      ],
    },
  ],
});
