// Chapter 5: Verb Tenses.
((window.SatWizz = window.SatWizz || {}).chapterData = window.SatWizz.chapterData || []).push({
  id: 5,
  short: "Verb Tenses",
  title: "Verb Tenses",
  pause: {
    summary: "Tense tells when something happens. Find the time clue in the sentence, then keep the verbs consistent unless the time really changes.",
    rules: [
      "Finished past (yesterday, last spring, in 1999) → simple past: broke, hosted.",
      "Started in the past and still true (since, for… so far) → present perfect: has organized, has lost.",
      "The earlier of two past events (by the time…, before…) → past perfect: had finished.",
      "Done by a future point (by next June) → future perfect: will have trained.",
      "Happening now (right now, currently) → present progressive: is revising.",
      "Habits (every day, always) → simple present: practices.",
      "After has, have, had or would have, use the past participle: would have run, had given (not ran, gave).",
    ],
    patterns: [
      { f: "Last spring, {{NAME_1}} broke a record.", ok: true },
      { f: "Since 2019, {{NAME_1}} organized the run.", ok: false },
      { f: "would have ran", ok: false },
      { f: "walks … and practices", ok: true },
    ],
    example: "By the time the bus arrived, {{NAME_2}} had already finished.",
  },
  questions: [
    {
      id: "c5-1", skill: "Time clues",
      text: "Last spring, {{NAME_1}} ______ a school record that had stood for twenty years.",
      choices: ["broke", "breaks", "will break", "has been breaking"],
      answer: 0,
      notes: [
        "“Last spring” is finished past time, so use the simple past “broke.”",
        "“Breaks” is present, but it happened last spring.",
        "“Will break” is future.",
        "“Has been breaking” suggests it's still going on, which doesn't fit a finished record.",
      ],
    },
    {
      id: "c5-2", skill: "Past perfect",
      text: "By the time the bus arrived, {{NAME_2}} ______ already finished the entire reading assignment.",
      choices: ["had", "has", "have", "will have"],
      answer: 0,
      notes: [
        "Finishing happened before another past event (the bus arriving), so use the past perfect “had finished.”",
        "“Has finished” connects to now, but the story is in the past.",
        "“Have” is plural and present.",
        "“Will have” is future.",
      ],
    },
    {
      id: "c5-3", skill: "Past participles",
      text: "{{NAME_3}} would have ______ the race if the storm had not delayed the start.",
      choices: ["run", "ran", "runned", "running"],
      answer: 0,
      notes: [
        "“Would have” takes the past participle, and the past participle of “run” is “run.”",
        "“Would have ran” is a common mistake. “Ran” is simple past.",
        "“Runned” isn't a word.",
        "“Would have running” isn't a verb form.",
      ],
    },
    {
      id: "c5-4", skill: "Present perfect",
      text: "Every year since 2019, {{NAME_1}} ______ the charity run at {{LOCATION}}.",
      choices: ["has organized", "organized", "will organize", "had organized"],
      answer: 0,
      notes: [
        "“Since 2019” means it started in the past and is still true, so use the present perfect.",
        "Simple past cuts it off. “Since” needs a connection to now.",
        "Future doesn't fit “since 2019.”",
        "Past perfect needs a later past event to compare with.",
      ],
    },
    {
      id: "c5-5", skill: "Future perfect",
      text: "By the time {{EVENT}} begins next month, {{NAME_2}} ______ for six straight weeks.",
      choices: ["will have trained", "trained", "has trained", "had trained"],
      answer: 0,
      notes: [
        "The training will be complete by a future point, so use the future perfect.",
        "Simple past ignores “next month.”",
        "Present perfect connects to now, not to a future point.",
        "Past perfect is for the past, not the future.",
      ],
    },
    {
      id: "c5-6", skill: "Consistency",
      text: "When {{NAME_3}} walked into {{LOCATION}}, the crowd ______ to cheer.",
      choices: ["began", "begins", "will begin", "has begun"],
      answer: 0,
      notes: [
        "“Walked” sets the scene in the past, and the reaction happened at the same time: “began.”",
        "“Begins” shifts to present.",
        "“Will begin” shifts to future.",
        "“Has begun” breaks the past-tense story.",
      ],
    },
    {
      id: "c5-7", skill: "Time clues",
      text: "Right now, {{NAME_1}} ______ the final draft of a speech for {{EVENT}}.",
      choices: ["is revising", "revised", "had revised", "will have revised"],
      answer: 0,
      notes: [
        "“Right now” means it's in progress, so use the present progressive.",
        "“Revised” is finished past.",
        "“Had revised” is the earlier of two past events.",
        "“Will have revised” is complete by a future point.",
      ],
    },
    {
      id: "c5-8", skill: "Time clues",
      text: "Yesterday, {{NAME_1}} ______ three chapters before dinner.",
      choices: ["finished", "finishes", "will finish", "is finishing"],
      answer: 0,
      notes: [
        "“Yesterday” is finished past, so use “finished.”",
        "Present tense doesn't fit “yesterday.”",
        "Future doesn't fit “yesterday.”",
        "“Is finishing” is happening now, not yesterday.",
      ],
    },
    {
      id: "c5-9", skill: "Consistency",
      text: "Every afternoon, {{NAME_2}} walks to {{LOCATION}} and ______ {{SKILL}} for an hour.",
      choices: ["practices", "practiced", "will practice", "had practiced"],
      answer: 0,
      notes: [
        "“Walks” is a present-tense habit. Keep it consistent with “practices.”",
        "“Practiced” shifts to past for no reason.",
        "“Will practice” shifts to future.",
        "“Had practiced” shifts to past perfect.",
      ],
    },
    {
      id: "c5-10", skill: "Past perfect",
      text: "{{NAME_3}} ______ at {{LOCATION}} for three years before moving away in 2021.",
      choices: ["had worked", "has worked", "works", "will work"],
      answer: 0,
      notes: [
        "The working came before another past event (moving in 2021), so use the past perfect.",
        "Present perfect connects to now, but it ended before 2021.",
        "Present tense contradicts “before moving away.”",
        "Future doesn't fit a past timeline.",
      ],
    },
    {
      id: "c5-11", skill: "Future perfect",
      text: "By next June, {{NAME_1}} ______ every chapter in this book.",
      choices: ["will have finished", "finished", "has finished", "had finished"],
      answer: 0,
      notes: [
        "Done by a future point, so use “will have finished.”",
        "Past tense doesn't match “next June.”",
        "Present perfect doesn't point to a future deadline.",
        "Past perfect is for the past.",
      ],
    },
    {
      id: "c5-12", skill: "Consistency",
      text: "When {{NAME_2}} was ten, {{NAME_2}} ______ of becoming a champion someday.",
      choices: ["dreamed", "dreams", "will dream", "has dreamed"],
      answer: 0,
      notes: [
        "“When {{NAME_2}} was ten” is past, so use “dreamed.”",
        "“Dreams” shifts to present.",
        "“Will dream” shifts to future.",
        "“Has dreamed” links to now, but the clue fixes it at age ten.",
      ],
    },
    {
      id: "c5-13", skill: "Present perfect",
      text: "Since the start of the season, the team ______ only one game.",
      choices: ["has lost", "lost", "loses", "will lose"],
      answer: 0,
      notes: [
        "“Since the start of the season” runs up to now, so use the present perfect.",
        "Simple past doesn't connect to “since.”",
        "Present tense doesn't fit a count so far.",
        "Future contradicts “since.”",
      ],
    },
    {
      id: "c5-14", skill: "Time clues",
      text: "Tomorrow, {{NAME_3}} ______ the results of {{EVENT}} to the whole school.",
      choices: ["will announce", "announced", "has announced", "had announced"],
      answer: 0,
      notes: [
        "“Tomorrow” is future, so use “will announce.”",
        "Past tense contradicts “tomorrow.”",
        "Present perfect is already done, which contradicts “tomorrow.”",
        "Past perfect contradicts “tomorrow.”",
      ],
    },
    {
      id: "c5-15", skill: "Consistency",
      text: "{{NAME_1}} was halfway through the speech when the microphone suddenly ______.",
      choices: ["stopped", "stops", "will stop", "has stopped"],
      answer: 0,
      notes: [
        "“Was halfway” sets the past, and the interruption is past too: “stopped.”",
        "“Stops” shifts to present.",
        "“Will stop” shifts to future.",
        "“Has stopped” breaks the past-tense story.",
      ],
    },
    {
      id: "c5-16", skill: "Conditionals",
      text: "If {{NAME_2}} had studied the map, {{NAME_2}} ______ lost on the way to {{LOCATION}}.",
      choices: ["would not have gotten", "will not get", "does not get", "had not gotten"],
      answer: 0,
      notes: [
        "“If … had studied” (didn't happen) pairs with “would not have gotten.”",
        "“Will not get” is a future result, which doesn't fit a past “if.”",
        "“Does not get” is present tense.",
        "“Had not gotten” makes both halves past perfect, which breaks the if/then pattern.",
      ],
    },
    {
      id: "c5-17", skill: "Past participles",
      text: "By the end of {{EVENT}}, {{NAME_3}} had ______ more than ten miles.",
      choices: ["run", "ran", "runs", "running"],
      answer: 0,
      notes: [
        "“Had” takes the past participle “run.”",
        "“Had ran” is a common mistake.",
        "“Had runs” isn't a verb form.",
        "“Had running” isn't a verb form.",
      ],
    },
    {
      id: "c5-18", skill: "Past participles",
      text: "The coach has ______ the same pep talk before every game for years.",
      choices: ["given", "gave", "give", "giving"],
      answer: 0,
      notes: [
        "“Has” takes the past participle “given.”",
        "“Has gave” uses simple past where the participle belongs.",
        "“Has give” is missing the participle ending.",
        "“Has giving” isn't a verb form.",
      ],
    },
    {
      id: "c5-19", skill: "Time clues",
      text: "Right now, the crowd at {{LOCATION}} ______ for an encore.",
      choices: ["is cheering", "cheered", "had cheered", "will have cheered"],
      answer: 0,
      notes: [
        "“Right now” means in progress, so use the present progressive.",
        "Past doesn't fit “right now.”",
        "Past perfect doesn't fit “right now.”",
        "Future perfect doesn't fit “right now.”",
      ],
    },
    {
      id: "c5-20", skill: "Time clues",
      text: "In 1999, the old stadium ______ its first championship game.",
      choices: ["hosted", "hosts", "has hosted", "will host"],
      answer: 0,
      notes: [
        "A specific past year calls for simple past: “hosted.”",
        "Present tense contradicts 1999.",
        "Present perfect doesn't go with a specific past date.",
        "Future contradicts 1999.",
      ],
    },
  ],
});
