// Chapter 5 (extra practice, after the pop-culture set in clause-derby/src/ch5.js): Transitions.
// `kind: "transition"` questions use the SAT's logical-transition prompt.
window.SatWizz.curriculum.addChapter({
  id: 5,
  short: "Transitions",
  title: "Transitions",
  pause: {
    summary: "Read both sentences first and name how they relate. Then pick the transition from that category, and punctuate it like the linking word (LW) it is.",
    rules: [
      "Contrast (goes against the last idea): however, nevertheless, instead, by contrast, still.",
      "Cause / effect (a result): therefore, thus, as a result, consequently.",
      "Addition (more in the same direction): moreover, additionally, furthermore, likewise, similarly.",
      "Example: for example, for instance. Sequence: first, next, then, finally. Summary: in short, in other words.",
      "Connector rules: IC, LW, IC is a comma splice. “; LW” can't lead into a DC. And “though” can't start a clause after a semicolon (IC; though, IC is illegal), but IC; IC, though. at the end is fine.",
    ],
    patterns: [
      { f: "IC. However, IC", ok: true },
      { f: "IC; however, IC", ok: true },
      { f: "IC, however, IC", ok: false },
      { f: "IC; though, IC", ok: false },
      { f: "IC; IC, though.", ok: true },
    ],
    example: "{{NAME_1}} missed practice. Nevertheless, {{NAME_1}} started the game. → contrast",
  },
  questions: [
    {
      id: "c6-1", skill: "Contrast", kind: "transition",
      text: "{{NAME_1}} missed the first three practices of the season. ______ {{NAME_1}} was named a starter for the opening game.",
      choices: ["Nevertheless,", "Therefore,", "For example,", "Similarly,"],
      answer: 0,
      notes: [
        "Being named a starter is surprising after missing practice. That's contrast, so “Nevertheless” fits.",
        "“Therefore” says missing practice caused the starting spot. That's backwards.",
        "The second sentence isn't an example of the first.",
        "“Similarly” needs two alike ideas. These two clash.",
      ],
    },
    {
      id: "c6-2", skill: "Cause / effect", kind: "transition",
      text: "{{NAME_2}} studied the playbook every night for a month. ______ {{NAME_2}} knew every play by heart before the first game.",
      choices: ["As a result,", "However,", "Instead,", "In contrast,"],
      answer: 0,
      notes: [
        "Knowing every play is the result of studying, so this is cause and effect.",
        "“However” signals contrast, but these ideas agree.",
        "“Instead” means one thing replaced another. Nothing was replaced.",
        "“In contrast” needs opposing ideas.",
      ],
    },
    {
      id: "c6-3", skill: "Example", kind: "transition",
      text: "{{NAME_3}} has several rituals before {{EVENT}}. ______ {{NAME_3}} always listens to the same song while warming up.",
      choices: ["For instance,", "Nonetheless,", "Meanwhile,", "In other words,"],
      answer: 0,
      notes: [
        "The song is one specific ritual, an example of the first sentence.",
        "“Nonetheless” signals contrast, and nothing contrasts here.",
        "“Meanwhile” means at the same time. It doesn't show how the ideas connect.",
        "“In other words” restates. The second sentence gives a specific case instead.",
      ],
    },
    {
      id: "c6-4", skill: "Contrast", kind: "transition",
      text: "{{NAME_1}} does {{NAME_1_POSS}} best practicing alone in the early morning. {{NAME_2}}, ______ prefers a noisy gym full of teammates.",
      choices: ["by contrast,", "similarly,", "therefore,", "for example,"],
      answer: 0,
      notes: [
        "Opposite habits call for a contrast word.",
        "“Similarly” would mean their habits match. They don't.",
        "One person's habit doesn't cause the other's.",
        "{{NAME_2}}'s habit isn't an example of {{NAME_1}}'s.",
      ],
    },
    {
      id: "c6-5", skill: "Contrast", kind: "transition",
      text: "Critics predicted that {{NAME_2}} would struggle at {{EVENT}}. ______ {{NAME_2}} delivered the best performance of {{NAME_2_POSS}} career.",
      choices: ["Instead,", "Additionally,", "Similarly,", "Consequently,"],
      answer: 0,
      notes: [
        "What happened replaced what was predicted, so “Instead” fits.",
        "“Additionally” adds a similar point, but this one opposes the prediction.",
        "“Similarly” needs matching ideas.",
        "The critics' prediction didn't cause the great performance.",
      ],
    },
    {
      id: "c6-6", skill: "Addition", kind: "transition",
      text: "{{NAME_3}} became the youngest person ever to win the award. ______ {{NAME_3}} donated the prize money to a local after-school program.",
      choices: ["Moreover,", "However,", "Regardless,", "Otherwise,"],
      answer: 0,
      notes: [
        "A second impressive fact piles on the first. That's addition.",
        "“However” signals contrast, but both facts are positive.",
        "“Regardless” means despite something, and nothing is being overcome.",
        "“Otherwise” means “if not,” which makes no sense here.",
      ],
    },
    {
      id: "c6-7", skill: "Connector punctuation",
      text: "{{NAME_2}} hoped for a week of ______ the schedule had other plans.",
      choices: ["rest; however,", "rest, however,", "rest; however", "rest however,"],
      answer: 0,
      notes: [
        "Two ICs with an LW between them: IC; LW, IC.",
        "IC, LW, IC is a comma splice.",
        "“However” needs a comma after it.",
        "A run-on: nothing legally separates the ICs.",
      ],
    },
    {
      id: "c6-8", skill: "Connector punctuation",
      text: "{{NAME_1}} expected to lose the ______ won by a single point.",
      choices: ["match; instead, {{NAME_1}}", "match; though, {{NAME_1}}", "match, instead, {{NAME_1}}", "match instead {{NAME_1}}"],
      answer: 0,
      notes: [
        "IC; LW, IC with a contrast word. That's legal and logical.",
        "IC; though, IC is the illegal “though” setup.",
        "IC, LW, IC is a comma splice.",
        "A run-on with no punctuation.",
      ],
    },
    {
      id: "c6-9", skill: "Cause / effect", kind: "transition",
      text: "The storm knocked out power at {{LOCATION}}. ______ {{EVENT}} was moved to the following week.",
      choices: ["Consequently,", "However,", "For example,", "Similarly,"],
      answer: 0,
      notes: [
        "The power outage caused the move, so this is cause and effect.",
        "“However” signals contrast, but these ideas agree.",
        "Moving the event isn't an example of a storm.",
        "“Similarly” compares two alike things. This is a result.",
      ],
    },
    {
      id: "c6-10", skill: "Addition", kind: "transition",
      text: "{{NAME_1}} leads the team in points. ______ {{NAME_1}} has the most assists.",
      choices: ["Additionally,", "However,", "Instead,", "Therefore,"],
      answer: 0,
      notes: [
        "A second strength adds to the first. That's addition.",
        "Nothing contrasts: both stats are strengths.",
        "Nothing is replaced.",
        "Scoring points doesn't cause assists.",
      ],
    },
    {
      id: "c6-11", skill: "Contrast", kind: "transition",
      text: "Most experts expected only a small crowd at {{EVENT}}. ______ more than a thousand people showed up.",
      choices: ["However,", "Similarly,", "Furthermore,", "For instance,"],
      answer: 0,
      notes: [
        "A huge crowd goes against the expectation. That's contrast.",
        "“Similarly” would mean the ideas match. They clash.",
        "“Furthermore” adds a supporting point, but this one opposes.",
        "It isn't an example of the experts' expectation.",
      ],
    },
    {
      id: "c6-12", skill: "Example", kind: "transition",
      text: "Great players rarely waste practice time. ______ {{NAME_2}} runs the same drill fifty times before every game.",
      choices: ["For example,", "Nevertheless,", "In contrast,", "Otherwise,"],
      answer: 0,
      notes: [
        "{{NAME_2}}'s routine is a specific case of the general claim.",
        "“Nevertheless” signals contrast. The ideas agree.",
        "“In contrast” needs opposite ideas.",
        "“Otherwise” means “if not,” which doesn't fit.",
      ],
    },
    {
      id: "c6-13", skill: "Sequence", kind: "transition",
      text: "First, {{NAME_3}} read the question carefully. ______ {{NAME_3}} crossed out two answers right away.",
      choices: ["Then,", "However,", "For instance,", "Instead,"],
      answer: 0,
      notes: [
        "“First” starts a sequence, and “Then” continues it.",
        "Nothing contrasts: these are steps in order.",
        "Crossing out answers isn't an example of reading carefully.",
        "Nothing was replaced.",
      ],
    },
    {
      id: "c6-14", skill: "Summary", kind: "transition",
      text: "{{NAME_1}} practiced daily, studied film, and never missed a meeting. ______ {{NAME_1}} was the most prepared player at {{EVENT}}.",
      choices: ["In short,", "However,", "For example,", "Meanwhile,"],
      answer: 0,
      notes: [
        "The second sentence sums up the list, so “In short” fits.",
        "No contrast: being prepared matches the list.",
        "The second sentence is a conclusion, not an example.",
        "“Meanwhile” means at the same time, which doesn't fit a conclusion.",
      ],
    },
    {
      id: "c6-15", skill: "Addition", kind: "transition",
      text: "{{NAME_2}} always arrives early to stretch before practice. ______ {{NAME_3}} shows up an hour before every game to warm up.",
      choices: ["Likewise,", "Instead,", "Consequently,", "For example,"],
      answer: 0,
      notes: [
        "Two players with the same kind of habit, so the similarity word fits.",
        "“Instead” means one replaced the other. It didn't.",
        "One player's habit doesn't cause the other's.",
        "{{NAME_3}}'s habit isn't an example of {{NAME_2}}'s.",
      ],
    },
    {
      id: "c6-16", skill: "Flexpos",
      text: "{{NAME_1}} was exhausted after {{EVENT}}; ______ went to practice the next morning.",
      choices: ["{{NAME_1}}, nevertheless,", "nevertheless {{NAME_1}}", ", nevertheless, {{NAME_1}}", "{{NAME_1}} nevertheless,"],
      answer: 0,
      notes: [
        "Flexpos: the LW slides into the second IC with commas on both sides.",
        "An opening LW needs a comma after it.",
        "A comma right after a semicolon is never correct.",
        "A mid-clause LW needs a comma before it too.",
      ],
    },
    {
      id: "c6-17", skill: "Connector punctuation",
      text: "The plan was ______ nobody wanted to change it.",
      choices: ["simple; therefore,", "simple, therefore,", "simple; therefore, because", "simple therefore"],
      answer: 0,
      notes: [
        "IC; LW, IC: legal punctuation and logical cause/effect.",
        "IC, LW, IC is a comma splice.",
        "“; therefore, because…” leads into a DC. IC; LW, DC is illegal.",
        "A run-on with no punctuation.",
      ],
    },
    {
      id: "c6-18", skill: "“Though” rules",
      text: "{{NAME_2}} loves {{SKILL}}; the early practices are ______",
      choices: ["hard, though.", "hard; though.", "hard. Though.", "hard though,"],
      answer: 0,
      notes: [
        "“Though” can sit at the end of a clause with a comma before it: IC; IC, though.",
        "A semicolon before a lone “though” leaves it as a fragment.",
        "“Though.” can't be a sentence by itself.",
        "A sentence can't end with a comma, and “though” needs one before it here.",
      ],
    },
    {
      id: "c6-19", skill: "Contrast", kind: "transition",
      text: "{{NAME_3}} didn't take the bus to {{LOCATION}}. ______ {{NAME_3}} rode a bike the whole way.",
      choices: ["Instead,", "Similarly,", "Therefore,", "For example,"],
      answer: 0,
      notes: [
        "Biking replaced the bus, so “Instead” fits.",
        "“Similarly” needs matching ideas.",
        "Not taking the bus doesn't directly cause biking. It's a replacement, not a result.",
        "Biking isn't an example of not taking the bus.",
      ],
    },
    {
      id: "c6-20", skill: "Cause / effect", kind: "transition",
      text: "The team won every game in the regular season. ______ it earned the top seed for {{EVENT}}.",
      choices: ["Thus,", "However,", "For instance,", "Nonetheless,"],
      answer: 0,
      notes: [
        "Winning every game led to the top seed. That's cause and effect.",
        "“However” signals contrast.",
        "The top seed isn't an example of winning.",
        "“Nonetheless” signals contrast.",
      ],
    },
  ],
});
