// Chapter 6 (extra practice, after the pop-culture set in clause-derby/src/ch6.js): Punctuation Fundamentals (semicolons, colons, dashes, ", which").
window.SatWizz.curriculum.addChapter({
  id: 6,
  short: "Semicolons, Colons, Dashes",
  title: "Punctuation Fundamentals: Semicolons, Colons, Dashes",
  pause: {
    summary: "Each strong punctuation mark has one job and one rule about what comes before it. Check the left side first.",
    rules: [
      "Semicolon: IC; IC. It's also the separator for list items that already contain commas: A, B; C, D; and E, F.",
      "Colon: the left side MUST be an IC. The right side can be an IC, a list or a noun phrase that explains the left.",
      "Never put a colon after “include,” “are,” “such as” or any other unfinished left side.",
      "Single dash: works like a colon (or comma) after an IC. The left side MUST be an IC. Never put a dash right before FANBOYS (for, and, nor, but, or, yet, so).",
      "“, which” starts a describing clause (a DC). It takes a comma, never a semicolon or a period.",
    ],
    patterns: [
      { f: "IC: list", ok: true },
      { f: "Snacks include: list", ok: false },
      { f: "IC—noun phrase", ok: true },
      { f: "IC—but IC", ok: false },
      { f: "noun, which…", ok: true },
      { f: "noun; which…", ok: false },
    ],
    example: "{{NAME_1}} packed three things: water, snacks, and a map.",
  },
  questions: [
    {
      id: "c7-1", skill: "Colons",
      text: "{{NAME_2}} packed only three things for the ______ a notebook, a phone charger, and a lucky wristband.",
      choices: ["trip:", "trip;", "trip, including:", "trip, they were"],
      answer: 0,
      notes: [
        "The left side is an IC and a list follows, so a colon is right.",
        "A semicolon needs an IC on both sides, and a list isn't one.",
        "A colon can't follow “including.” The left side isn't complete.",
        "“, they were…” creates a comma splice.",
      ],
    },
    {
      id: "c7-2", skill: "Colons",
      text: "{{NAME_3}} had exactly one goal for ______ stay calm no matter what happened.",
      choices: ["{{EVENT}}: to", "{{EVENT}}; to", "{{EVENT}}. To", "{{EVENT}} to"],
      answer: 0,
      notes: [
        "IC on the left, and the right side explains the goal. That's a colon's job.",
        "“To stay calm…” isn't an IC, so a semicolon can't come before it.",
        "A period leaves “To stay calm…” as a fragment.",
        "With no punctuation, the goal runs straight into the event and the meaning blurs.",
      ],
    },
    {
      id: "c7-3", skill: "Semicolon lists",
      text: "{{NAME_1}}'s summer tour stopped in three cities: Lisbon, ______ Madrid, Spain; and Paris, France.",
      choices: ["Portugal;", "Portugal,", "Portugal:", "Portugal"],
      answer: 0,
      notes: [
        "The items already contain commas (city, country), so semicolons separate them, matching the rest of the list.",
        "A comma makes it impossible to tell where one item ends and the next begins.",
        "A colon doesn't separate list items.",
        "With no punctuation, Portugal and Madrid run together.",
      ],
    },
    {
      id: "c7-4", skill: "Single dashes",
      text: "{{NAME_1}} finally understood what the coach ______ is only useful when it is focused.",
      choices: ["meant—practice", "meant, practice", "meant practice", "meant; and practice"],
      answer: 0,
      notes: [
        "The left side is an IC, and the dash introduces the explanation, just like a colon would.",
        "A comma between two ICs is a splice.",
        "No punctuation makes a run-on.",
        "A semicolon doesn't pair with FANBOYS.",
      ],
    },
    {
      id: "c7-5", skill: "Dashes & FANBOYS",
      text: "The rain at {{LOCATION}} kept ______ the game went on anyway.",
      choices: ["falling, but", "falling—but", "falling; but", "falling but,"],
      answer: 0,
      notes: [
        "IC, but IC: a comma plus FANBOYS.",
        "Never put a dash before FANBOYS.",
        "A semicolon doesn't pair with FANBOYS.",
        "The comma goes before “but,” not after it.",
      ],
    },
    {
      id: "c7-6", skill: ", which",
      text: "{{NAME_2}} donated the prize money to the community ______ used it to buy new laptops.",
      choices: ["library, which", "library which", "library; which", "library. Which"],
      answer: 0,
      notes: [
        "“, which” starts a describing clause, and it takes a comma.",
        "A non-essential “which” clause needs a comma before it.",
        "A semicolon needs an IC after it, and “which…” isn't one.",
        "A period leaves “Which used it…” as a fragment.",
      ],
    },
    {
      id: "c7-7", skill: "Colons",
      text: "The three skills tested at {{EVENT}} ______ speed, accuracy, and focus.",
      choices: ["are", "are:", "are;", "are—"],
      answer: 0,
      notes: [
        "“The three skills … are” isn't a complete IC, so the list completes the sentence directly.",
        "A colon needs a complete IC on the left. “…are:” is unfinished.",
        "A semicolon needs ICs on both sides.",
        "A dash also needs an IC on the left.",
      ],
    },
    {
      id: "c7-8", skill: "Colons",
      text: "{{NAME_3}} learned an important ______ hard work beats talent when talent doesn't work hard.",
      choices: ["lesson:", "lesson,", "lesson", "lesson, that"],
      answer: 0,
      notes: [
        "The IC on the left names a lesson, and the IC on the right spells it out. That's a colon's job.",
        "A comma between two ICs is a splice.",
        "No punctuation makes a run-on.",
        "“, that” muddles the sentence and still doesn't join the ICs legally.",
      ],
    },
    {
      id: "c7-9", skill: "Semicolons",
      text: "{{NAME_1}} loved the first ______ second one was even better.",
      choices: ["song; the", "song, the", "song the", "song, and, the"],
      answer: 0,
      notes: [
        "Both sides are complete sentences, so a semicolon joins them: IC; IC.",
        "IC, IC is a comma splice.",
        "No punctuation makes a run-on.",
        "No comma goes after “and.”",
      ],
    },
    {
      id: "c7-10", skill: "Semicolon lists",
      text: "The club visited three places: Austin, Texas; Denver, ______ and Boise, Idaho.",
      choices: ["Colorado;", "Colorado,", "Colorado:", "Colorado"],
      answer: 0,
      notes: [
        "Items with internal commas are separated by semicolons, matching “Texas;”.",
        "A comma blurs where the items begin and end.",
        "A colon isn't a list separator.",
        "Something has to separate the items.",
      ],
    },
    {
      id: "c7-11", skill: "Colons",
      text: "After weeks of work, {{NAME_2}} finally mastered the hardest part of ______",
      choices: ["{{SKILL}}: the timing.", "{{SKILL}}; the timing.", "{{SKILL}}, it was the timing.", "{{SKILL}} was: the timing."],
      answer: 0,
      notes: [
        "IC on the left, and a noun phrase that explains it on the right. That's a colon.",
        "“The timing” isn't an IC, so a semicolon can't come before it.",
        "“, it was the timing” is a comma splice.",
        "“…was:” breaks the sentence. A colon can't split a verb from what completes it.",
      ],
    },
    {
      id: "c7-12", skill: "Single dashes",
      text: "{{NAME_3}} had only one thing on {{NAME_3_POSS}} ______ winning {{EVENT}}.",
      choices: ["mind—", "mind;", "mind, and", "mind, which"],
      answer: 0,
      notes: [
        "The left side is an IC, and the dash introduces what that one thing is.",
        "“Winning {{EVENT}}” isn't an IC, so a semicolon can't come before it.",
        "“, and winning…” isn't a second IC.",
        "“, which winning…” makes no sense.",
      ],
    },
    {
      id: "c7-13", skill: "Colons",
      text: "{{NAME_1}}'s favorite snacks ______ pretzels, grapes, and granola.",
      choices: ["include", "include:", "include;", "include—"],
      answer: 0,
      notes: [
        "“Snacks include…” flows straight into its list with no punctuation.",
        "A colon can't come right after “include.” The left side isn't complete.",
        "A semicolon needs ICs on both sides.",
        "A dash needs an IC on the left.",
      ],
    },
    {
      id: "c7-14", skill: "Dashes & FANBOYS",
      text: "{{NAME_2}} wanted to sleep ______ the alarm had other ideas.",
      choices: ["in, but", "in—but", "in; but", "in but,"],
      answer: 0,
      notes: [
        "IC, but IC.",
        "No dash before FANBOYS.",
        "A semicolon doesn't pair with FANBOYS.",
        "The comma goes before “but.”",
      ],
    },
    {
      id: "c7-15", skill: ", which",
      text: "The team celebrated in the old ______ was decorated with banners for the occasion.",
      choices: ["gym, which", "gym which,", "gym; which", "gym. Which"],
      answer: 0,
      notes: [
        "“, which” adds a describing clause with a comma.",
        "The comma belongs before “which,” not after.",
        "A semicolon needs an IC after it.",
        "A period leaves “Which was decorated…” as a fragment.",
      ],
    },
    {
      id: "c7-16", skill: "Semicolons",
      text: "{{NAME_3}} checked the scoreboard ______ numbers still didn't look real.",
      choices: ["twice; the", "twice, the", "twice the", "twice: and the"],
      answer: 0,
      notes: [
        "Two complete sentences joined by a semicolon: IC; IC.",
        "IC, IC is a comma splice.",
        "No punctuation makes a run-on.",
        "A colon followed by “and” is never correct.",
      ],
    },
    {
      id: "c7-17", skill: "Colons",
      text: "The coach gave {{NAME_1}} one piece of ______ never stop moving your feet.",
      choices: ["advice:", "advice;", "advice, that", "advice"],
      answer: 0,
      notes: [
        "IC on the left names the advice, and the colon introduces it.",
        "A semicolon can't introduce an explanation like this.",
        "“, that never stop…” doesn't make sense.",
        "No punctuation makes a run-on.",
      ],
    },
    {
      id: "c7-18", skill: "Colons",
      text: "The two things {{NAME_2}} needed before {{EVENT}} ______ sleep and a good breakfast.",
      choices: ["were", "were:", "were—", "were;"],
      answer: 0,
      notes: [
        "The left side isn't a complete IC, so the sentence continues with no punctuation.",
        "A colon needs a complete IC before it.",
        "A dash also needs a complete IC before it.",
        "A semicolon needs ICs on both sides.",
      ],
    },
    {
      id: "c7-19", skill: "Colons",
      text: "{{NAME_2}} finally understood the ______ every sentence needs at least one independent clause.",
      choices: ["rule:", "rule,", "rule, that", "rule and"],
      answer: 0,
      notes: [
        "IC: IC. The colon introduces what the rule is.",
        "A comma between two ICs is a splice.",
        "“, that every sentence…” is muddled and doesn't legally join the clauses.",
        "“And” joining two ICs needs a comma before it, and the logic calls for an explanation, not an addition.",
      ],
    },
    {
      id: "c7-20", skill: "Single dashes",
      text: "{{NAME_3}} brought three things to {{LOCATION}}______ map, a flashlight, and extra batteries.",
      choices: ["—a", "; a", ", they were a", ", and a"],
      answer: 0,
      notes: [
        "The left side is an IC, and the dash introduces the list of three things.",
        "A semicolon needs an IC after it, and a list isn't one.",
        "“, they were…” is a comma splice.",
        "“, and a map…” makes it sound like a fourth item instead of the list of three.",
      ],
    },
  ],
});
