// Chapter 8: Appositives & Non-Essential Clauses.
((window.SatWizz = window.SatWizz || {}).chapterData = window.SatWizz.chapterData || []).push({
  id: 8,
  short: "Appositives",
  title: "Appositives & Non-Essential Clauses",
  pause: {
    summary: "Extra information gets matching punctuation on both sides. Information that tells you which one gets no punctuation at all.",
    rules: [
      "Non-essential (you could delete it and the sentence still works): wrap it symmetrically: “, info ,” or “— info —”.",
      "Never mix the pair. A dash that opens must close with a dash, and a comma that opens must close with a comma.",
      "Thumb test: cover the extra info with your thumb. If the sentence still makes sense, it needs the pair.",
      "Essential (it tells you which one): no commas. “The researcher {{NAME_1}} presented…” has no commas, because the name tells us which researcher.",
      "Essential “who” and “that” clauses (students who finish early…) take no commas either, and never put a single comma between a subject and its verb.",
    ],
    patterns: [
      { f: "{{NAME_1}}, a captain, won.", ok: true },
      { f: "{{NAME_1}}—a captain, won.", ok: false },
      { f: "The researcher {{NAME_1}} spoke.", ok: true },
      { f: "The researcher, {{NAME_1}} spoke.", ok: false },
    ],
    example: "{{NAME_2}}, the youngest player on the team, scored the winning point.",
  },
  questions: [
    {
      id: "c8-1", skill: "Dash pairs",
      text: "{{NAME_2}}'s coach—a former champion who rarely handed out ______ called the performance “nearly flawless.”",
      choices: ["compliments—", "compliments,", "compliments;", "compliments"],
      answer: 0,
      notes: [
        "The extra info opened with a dash, so it closes with a dash.",
        "A comma can't close a dash-opened interruption.",
        "A semicolon would split the subject from its verb.",
        "Without a closing mark, the interruption never ends.",
      ],
    },
    {
      id: "c8-2", skill: "Comma pairs",
      text: "{{NAME_3}}, who had never lost a match at ______ the final with total confidence.",
      choices: ["home, entered", "home entered", "home; entered", "home—entered"],
      answer: 0,
      notes: [
        "The “who” clause opened with a comma, so it closes with a comma before “entered.”",
        "With no closing comma, the extra info runs into the main verb.",
        "A semicolon can't close an interruption.",
        "A dash can't close a comma-opened interruption.",
      ],
    },
    {
      id: "c8-3", skill: "Essential names",
      text: "Longtime rivals ______ met again in the final round, and the crowd could barely contain its excitement.",
      choices: ["{{NAME_1}} and {{NAME_2}}", "{{NAME_1}}, and {{NAME_2}},", "{{NAME_1}} and {{NAME_2}},", ", {{NAME_1}} and {{NAME_2}},"],
      answer: 0,
      notes: [
        "The names tell you which rivals, so they're essential and take no commas.",
        "The commas split the subject apart for no reason.",
        "A lone comma between the subject and its verb is never allowed.",
        "The names are essential, so the comma pair doesn't belong.",
      ],
    },
    {
      id: "c8-4", skill: "Essential names",
      text: "The researcher ______ presented the findings at {{EVENT}}.",
      choices: ["{{NAME_1}}", "{{NAME_1}},", ", {{NAME_1}},", ", {{NAME_1}}"],
      answer: 0,
      notes: [
        "The name tells us which researcher, so it's essential. No commas.",
        "This puts a lone comma between the subject and its verb.",
        "It treats the name as extra, but the name identifies the researcher.",
        "An unmatched comma isn't symmetrical, and it's unneeded anyway.",
      ],
    },
    {
      id: "c8-5", skill: "Comma pairs",
      text: "{{NAME_2}}, the youngest player on the ______ scored the winning point.",
      choices: ["team,", "team", "team—", "team;"],
      answer: 0,
      notes: [
        "The appositive opened with a comma, so it closes with one.",
        "Missing the closing comma.",
        "A dash doesn't match the opening comma.",
        "A semicolon would split the subject from its verb.",
      ],
    },
    {
      id: "c8-6", skill: "Comma pairs",
      text: "{{NAME_1}}'s mentor, a retired teacher from the ______ taught {{NAME_1_OBJ}} everything about {{SKILL}}.",
      choices: ["neighborhood,", "neighborhood", "neighborhood—", "neighborhood;"],
      answer: 0,
      notes: [
        "A comma opened the extra info, so a comma closes it.",
        "Missing the closing comma.",
        "A dash doesn't match the opening comma.",
        "A semicolon would cut the sentence in half.",
      ],
    },
    {
      id: "c8-7", skill: "Essential clauses",
      text: "Students ______ the chapter early can start the bonus review.",
      choices: ["who finish", "who finish,", ", who finish", ", who finish,"],
      answer: 0,
      notes: [
        "“Who finish the chapter early” tells you which students, so it's essential. No commas.",
        "A lone comma separates the subject from its verb.",
        "This treats essential info as extra, and it isn't closed.",
        "The pair treats essential info as extra. We need to know which students.",
      ],
    },
    {
      id: "c8-8", skill: "Comma pairs",
      text: "{{NAME_1}}, a sophomore from the debate ______ gave the opening speech at {{EVENT}}.",
      choices: ["team,", "team", "team—", "team;"],
      answer: 0,
      notes: [
        "The appositive opened with a comma, so it closes with a comma.",
        "Missing the closing comma.",
        "A dash doesn't match the opening comma.",
        "A semicolon splits the subject from its verb.",
      ],
    },
    {
      id: "c8-9", skill: "Dash pairs",
      text: "The trophy—a silver cup older than the ______ sat in the center of {{LOCATION}}.",
      choices: ["school itself—", "school itself,", "school itself;", "school itself"],
      answer: 0,
      notes: [
        "Opened with a dash, so it closes with a dash.",
        "A comma doesn't match the opening dash.",
        "A semicolon splits the subject from its verb.",
        "The interruption never closes.",
      ],
    },
    {
      id: "c8-10", skill: "Essential names",
      text: "The author ______ will speak at {{EVENT}} on Friday.",
      choices: ["{{NAME_2}}", "{{NAME_2}},", ", {{NAME_2}},", ", {{NAME_2}}"],
      answer: 0,
      notes: [
        "The name identifies which author, so no commas.",
        "A lone comma between the subject and its verb.",
        "The name is essential, not extra.",
        "An unmatched comma.",
      ],
    },
    {
      id: "c8-11", skill: "Essential clauses",
      text: "The book ______ inspired {{NAME_3}} to start writing is still on {{NAME_3_POSS}} desk.",
      choices: ["that", ", that", "that,", ", which"],
      answer: 0,
      notes: [
        "“That inspired {{NAME_3}}…” tells which book, so it's essential. No commas.",
        "“That” clauses never take a comma before them.",
        "A comma after “that” splits the clause.",
        "“, which…” opens extra info that never closes before “is,” so the pair is broken.",
      ],
    },
    {
      id: "c8-12", skill: "Comma pairs",
      text: "The coach, who had seen hundreds of ______ called it the best performance of the season.",
      choices: ["games,", "games", "games—", "games;"],
      answer: 0,
      notes: [
        "The “who” clause opened with a comma, so it closes with one.",
        "Missing the closing comma.",
        "A dash doesn't match.",
        "A semicolon splits the subject from its verb.",
      ],
    },
    {
      id: "c8-13", skill: "Dash pairs",
      text: "Our mascot—a giant foam ______ led the parade through {{LOCATION}}.",
      choices: ["tiger—", "tiger,", "tiger", "tiger;"],
      answer: 0,
      notes: [
        "A dash opened the extra info, so a dash closes it.",
        "A comma doesn't match the opening dash.",
        "The interruption never closes.",
        "A semicolon splits the subject from its verb.",
      ],
    },
    {
      id: "c8-14", skill: "Essential clauses",
      text: "The student ______ the essay contest will read it aloud at {{EVENT}}.",
      choices: ["who won", ", who won", "who won,", ", who won,"],
      answer: 0,
      notes: [
        "“Who won the essay contest” identifies which student, so it's essential. No commas.",
        "An unmatched comma, and the info is essential anyway.",
        "A lone comma between the subject and its verb.",
        "The pair wrongly treats essential info as extra.",
      ],
    },
    {
      id: "c8-15", skill: "Comma pairs",
      text: "{{NAME_1}} thanked {{NAME_1_POSS}} ______ Ms. Rivera, after {{EVENT}}.",
      choices: ["mentor,", "mentor", "mentor—", "mentor;"],
      answer: 0,
      notes: [
        "“Ms. Rivera” is extra info about the mentor. The closing comma is already there, so it opens with a comma.",
        "Missing the opening comma, so the pair doesn't match.",
        "A dash doesn't match the closing comma.",
        "A semicolon cuts off the rest of the sentence.",
      ],
    },
    {
      id: "c8-16", skill: "Comma pairs",
      text: "{{NAME_3}}, captain of the team for three years ______ announced plans to retire.",
      choices: ["running,", "running", "running—", "running;"],
      answer: 0,
      notes: [
        "A comma opened the appositive, so a comma closes it.",
        "Missing the closing comma.",
        "A dash doesn't match.",
        "A semicolon splits the subject from its verb.",
      ],
    },
    {
      id: "c8-17", skill: "Essential names",
      text: "The word ______ appears in every chapter of this lesson.",
      choices: ["“clause”", ", “clause”,", "“clause”,", ", “clause”"],
      answer: 0,
      notes: [
        "The quoted word tells us which word, so it's essential. No commas.",
        "The pair treats essential info as extra.",
        "A lone comma between the subject and its verb.",
        "An unmatched comma.",
      ],
    },
    {
      id: "c8-18", skill: "Dash pairs",
      text: "The three finalists—{{NAME_1}}, {{NAME_2}}, and ______ waited nervously backstage.",
      choices: ["{{NAME_3}}—", "{{NAME_3}},", "{{NAME_3}}", "{{NAME_3}};"],
      answer: 0,
      notes: [
        "A list inside a dash pair has to close with a dash.",
        "A comma can't close the dash pair.",
        "The interruption never closes.",
        "A semicolon splits the subject from its verb.",
      ],
    },
    {
      id: "c8-19", skill: "Comma pairs",
      text: "{{NAME_2}}'s plan, which was to practice every morning before ______ worked perfectly.",
      choices: ["school,", "school", "school—", "school;"],
      answer: 0,
      notes: [
        "The “which” clause opened with a comma, so it closes with one.",
        "Missing the closing comma.",
        "A dash doesn't match.",
        "A semicolon splits the subject from its verb.",
      ],
    },
    {
      id: "c8-20", skill: "Comma pairs",
      text: "Our neighbor, a nurse who works night ______ still finds time to coach at {{LOCATION}}.",
      choices: ["shifts,", "shifts", "shifts—", "shifts;"],
      answer: 0,
      notes: [
        "A comma opened the appositive, so a comma closes it.",
        "Missing the closing comma.",
        "A dash doesn't match the opening comma.",
        "A semicolon splits the subject from its verb.",
      ],
    },
  ],
});
