// Chapter 9: Modifiers & Parallelism.
((window.SatWizz = window.SatWizz || {}).chapterData = window.SatWizz.chapterData || []).push({
  id: 9,
  short: "Modifiers & Parallelism",
  title: "Modifiers & Parallelism",
  pause: {
    summary: "Two alignment rules. A describing phrase must touch its target, and paired or listed items must match in form.",
    rules: [
      "The target rule: an opening phrase (“Exhausted after practice, …”) describes whatever comes right after the comma. Ask “who was exhausted?” and put that noun there.",
      "Dangling modifier: “Exhausted, the couch looked great.” Now the couch is exhausted.",
      "A possessive isn't a target. In “Tired, {{NAME_1}}'s bed looked great,” the bed is still what comes after the comma.",
      "A/B parallelism: in pairs and lists, every item takes the same form (running, lifting, swimming / to read, to write, to draw).",
      "Paired phrases need matching halves: not only X but also Y · both X and Y · rather X than Y.",
      "Compare like with like: a score to a score (“{{NAME_3}}'s”), not a score to a person.",
    ],
    patterns: [
      { f: "Exhausted, {{NAME_1}} sat down.", ok: true },
      { f: "Exhausted, dinner was eaten.", ok: false },
      { f: "to read, to write, and to draw", ok: true },
      { f: "to read, to write, and drawing", ok: false },
    ],
    example: "Known for staying calm, {{NAME_1}} took the final shot. → target: {{NAME_1}}",
  },
  questions: [
    {
      id: "c9-1", skill: "Target rule",
      text: "Exhausted after hours of practice, ______",
      choices: [
        "{{NAME_1}} finally sat down to eat dinner.",
        "dinner was finally eaten by {{NAME_1}}.",
        "the couch was where {{NAME_1}} finally collapsed.",
        "{{NAME_1_POSS}} dinner was finally ready.",
      ],
      answer: 0,
      notes: [
        "Who was exhausted? {{NAME_1}}. The target sits right after the comma.",
        "This says the dinner was exhausted.",
        "This says the couch was exhausted.",
        "The target is “dinner,” not {{NAME_1}}. A possessive doesn't count.",
      ],
    },
    {
      id: "c9-2", skill: "Target rule",
      text: "Known for staying calm under pressure, ______",
      choices: [
        "{{NAME_1}} was chosen to take the final shot.",
        "the coach chose {{NAME_1}} to take the final shot.",
        "the final shot was given to {{NAME_1}}.",
        "{{NAME_1_POSS}} coach picked {{NAME_1_OBJ}} for the final shot.",
      ],
      answer: 0,
      notes: [
        "The calm one is {{NAME_1}}, and {{NAME_1}} comes right after the comma.",
        "This says the coach is known for staying calm.",
        "This says the shot is calm.",
        "The target becomes the coach again.",
      ],
    },
    {
      id: "c9-3", skill: "Target rule",
      text: "Walking into {{LOCATION}} for the first time, ______",
      choices: [
        "{{NAME_2}} noticed how quiet the room was.",
        "the quiet of the room surprised {{NAME_2}}.",
        "the room seemed quiet to {{NAME_2}}.",
        "{{NAME_2_POSS}} first impression was the quiet.",
      ],
      answer: 0,
      notes: [
        "{{NAME_2}} is the one walking in, and {{NAME_2}} touches the modifier.",
        "This says the quiet was walking in.",
        "This says the room was walking.",
        "This says the impression was walking.",
      ],
    },
    {
      id: "c9-4", skill: "Parallel lists",
      text: "{{NAME_1}}'s morning routine includes stretching, lifting weights, and ______",
      choices: ["running sprints.", "to run sprints.", "sprints are run.", "{{NAME_1}} runs sprints."],
      answer: 0,
      notes: [
        "Stretching, lifting, running: all -ing forms.",
        "“To run” breaks the -ing pattern.",
        "A whole clause doesn't match the other items.",
        "A full sentence doesn't match the other items.",
      ],
    },
    {
      id: "c9-5", skill: "Parallel lists",
      text: "{{NAME_3}} likes to read, to write, and ______",
      choices: ["to draw.", "drawing.", "draws.", "to drawing."],
      answer: 0,
      notes: [
        "To read, to write, to draw: all “to” forms.",
        "“Drawing” breaks the “to” pattern.",
        "“Draws” is a verb, not a “to” form.",
        "“To drawing” isn't a form at all.",
      ],
    },
    {
      id: "c9-6", skill: "A/B pairs",
      text: "For {{NAME_2}}, winning {{EVENT}} was less about talent than about ______ every single day.",
      choices: ["showing up", "to show up", "you show up", "it was showing up"],
      answer: 0,
      notes: [
        "“About talent” / “about showing up”: both halves use a noun form after “about.”",
        "“About to show up” changes the meaning and breaks the pattern.",
        "“About you show up” isn't grammatical.",
        "“About it was…” puts a clause where a noun form belongs.",
      ],
    },
    {
      id: "c9-7", skill: "Comparisons",
      text: "{{NAME_2}}'s score on the practice test was higher than ______",
      choices: ["{{NAME_3}}'s.", "{{NAME_3}}.", "{{NAME_3}}s.", "{{NAME_3}}s'."],
      answer: 0,
      notes: [
        "Score to score: “{{NAME_3}}'s” means “{{NAME_3}}'s score.”",
        "This compares a score to a person.",
        "A plural, not a possessive.",
        "A plural possessive, but only one person is meant.",
      ],
    },
    {
      id: "c9-8", skill: "Target rule",
      text: "Covered in mud after the game, ______",
      choices: [
        "{{NAME_3}} headed straight for the showers.",
        "the showers were where {{NAME_3}} headed.",
        "{{NAME_3_POSS}} coach sent {{NAME_3_OBJ}} to the showers.",
        "a shower was what {{NAME_3}} needed.",
      ],
      answer: 0,
      notes: [
        "{{NAME_3}} was muddy, and {{NAME_3}} is the target.",
        "This says the showers were muddy.",
        "This says the coach was muddy.",
        "This says the shower was muddy.",
      ],
    },
    {
      id: "c9-9", skill: "Target rule",
      text: "After finishing the final exam, ______",
      choices: [
        "{{NAME_1}} celebrated with friends at {{LOCATION}}.",
        "friends joined {{NAME_1}} to celebrate.",
        "a celebration was held for {{NAME_1}}.",
        "{{NAME_1_POSS}} friends threw a party.",
      ],
      answer: 0,
      notes: [
        "{{NAME_1}} finished the exam, so {{NAME_1}} comes right after the comma.",
        "This says the friends finished the exam.",
        "This says the celebration finished the exam.",
        "The possessive makes “friends” the target.",
      ],
    },
    {
      id: "c9-10", skill: "Target rule",
      text: "A talented speaker, ______",
      choices: [
        "{{NAME_2}} won the debate easily.",
        "the debate was won easily by {{NAME_2}}.",
        "{{NAME_2_POSS}} speech won the debate.",
        "the judges gave {{NAME_2}} first place.",
      ],
      answer: 0,
      notes: [
        "The talented speaker is {{NAME_2}}.",
        "This says the debate is a talented speaker.",
        "This says the speech is a speaker.",
        "This says the judges are the talented speaker.",
      ],
    },
    {
      id: "c9-11", skill: "A/B pairs",
      text: "{{NAME_3}} would rather practice at {{LOCATION}} than ______ at home.",
      choices: ["study", "studying", "to study", "studies"],
      answer: 0,
      notes: [
        "“Rather practice … than study”: both halves use the base verb.",
        "“Studying” doesn't match “practice.”",
        "“To study” doesn't match.",
        "“Studies” doesn't match.",
      ],
    },
    {
      id: "c9-12", skill: "A/B pairs",
      text: "{{NAME_1}} is not only a strong player but also ______",
      choices: ["a thoughtful leader.", "leads thoughtfully.", "leading with thought.", "someone who leads thoughtful."],
      answer: 0,
      notes: [
        "“A strong player” / “a thoughtful leader”: noun phrase matches noun phrase.",
        "A verb phrase doesn't match a noun phrase.",
        "An -ing phrase doesn't match.",
        "It should be “thoughtfully,” and it still doesn't mirror the first half.",
      ],
    },
    {
      id: "c9-13", skill: "Parallel lists",
      text: "At {{LOCATION}}, the volunteers cleaned the floors, painted the walls, and ______ new lights.",
      choices: ["installed", "installing", "were installing", "to install"],
      answer: 0,
      notes: [
        "Cleaned, painted, installed: all simple past.",
        "Breaks the past-tense pattern.",
        "Switches to a different verb form.",
        "A “to” form breaks the pattern.",
      ],
    },
    {
      id: "c9-14", skill: "A/B pairs",
      text: "The coach praised {{NAME_2}} both for effort and ______",
      choices: ["for teamwork.", "teamwork was great.", "because of teamwork.", "being a team player."],
      answer: 0,
      notes: [
        "“Both for effort and for teamwork”: matching halves.",
        "A clause doesn't match “for effort.”",
        "“Because of” doesn't mirror “for.”",
        "An -ing phrase doesn't match.",
      ],
    },
    {
      id: "c9-15", skill: "Comparisons",
      text: "The crowd at this year's final was louder than ______",
      choices: ["the crowd at last year's final.", "last year.", "last year's final.", "the final last year was."],
      answer: 0,
      notes: [
        "Crowd to crowd: a logical comparison.",
        "This compares a crowd to a year.",
        "This compares a crowd to a final.",
        "This compares a crowd to a final, and it's awkward.",
      ],
    },
    {
      id: "c9-16", skill: "Target rule",
      text: "Hoping to impress the scouts, ______",
      choices: [
        "{{NAME_1}} arrived at {{LOCATION}} two hours early.",
        "the scouts were impressed by {{NAME_1}}.",
        "{{NAME_1_POSS}} early arrival surprised everyone.",
        "two hours early was when {{NAME_1}} arrived.",
      ],
      answer: 0,
      notes: [
        "{{NAME_1}} is the one hoping, and {{NAME_1}} is the target.",
        "This says the scouts hoped to impress themselves.",
        "This says the arrival was hoping.",
        "This says a time was hoping.",
      ],
    },
    {
      id: "c9-17", skill: "Parallel lists",
      text: "The workshop covers grammar, vocabulary, and ______",
      choices: ["reading strategies.", "how to read strategically.", "reading strategically is covered.", "to read with strategy."],
      answer: 0,
      notes: [
        "Three noun phrases: grammar, vocabulary, reading strategies.",
        "A “how to” phrase doesn't match the nouns.",
        "A clause doesn't match.",
        "A “to” form doesn't match.",
      ],
    },
    {
      id: "c9-18", skill: "A/B pairs",
      text: "{{NAME_2}} enjoys running in the morning more than ______ at night.",
      choices: ["swimming", "to swim", "swim", "a swim"],
      answer: 0,
      notes: [
        "“Running” / “swimming”: -ing matches -ing.",
        "A “to” form doesn't match “running.”",
        "A base verb doesn't match.",
        "A noun phrase doesn't match the -ing form.",
      ],
    },
    {
      id: "c9-19", skill: "Comparisons",
      text: "{{NAME_1}}'s speech at {{EVENT}} was shorter than ______",
      choices: ["{{NAME_2}}'s.", "{{NAME_2}}.", "{{NAME_2}} spoke.", "the speaker {{NAME_2}}."],
      answer: 0,
      notes: [
        "Speech to speech: “{{NAME_2}}'s” means {{NAME_2}}'s speech.",
        "Speech to person.",
        "Speech to an action.",
        "Speech to a person.",
      ],
    },
    {
      id: "c9-20", skill: "Target rule",
      text: "To prepare for {{EVENT}}, ______",
      choices: [
        "{{NAME_3}} studied old game footage every night.",
        "old game footage was studied every night.",
        "every night was spent on old game footage.",
        "{{NAME_3_POSS}} nights were spent studying footage.",
      ],
      answer: 0,
      notes: [
        "{{NAME_3}} is the one preparing, and {{NAME_3}} is the target.",
        "No one is doing the preparing. The footage becomes the target.",
        "The target becomes “every night.”",
        "The target is “nights,” not {{NAME_3}}.",
      ],
    },
  ],
});
