// Builds the whole SatWizz app as ONE self-contained HTML file:
//
//   node scripts/build-single.js      → dist/index.html
//
// It reads the real index.html and inlines everything it loads locally:
// css/styles.css, every js/… script (in the same order), and the icons (as
// data URIs). The result runs by double-click or from any static host.
//
// What stays external, on purpose:
//   • Google Fonts (optional; system fonts are used offline).
//   • The Supabase client from its CDN (optional; without it, or without keys
//     in js/config.js, SatWizz runs in guest mode with localStorage).
//   • sw.js: browsers require a service worker to be its own file, so Lock In
//     *push* alerts work only if sw.js is uploaded next to index.html. In-app
//     Lock In banners and everything else work from the single file.
// The web app manifest is dropped (it needs separate files to be installable).
//
// Re-run after changing index.html, css/ or js/.
"use strict";

const fs = require("fs");
const path = require("path");

const repo = path.resolve(__dirname, "..");
const read = (f) => fs.readFileSync(path.join(repo, f), "utf8");
const safeScript = (code) => code.replace(/<\/script/gi, "<\\/script");
const safeStyle = (code) => code.replace(/<\/style/gi, "<\\/style");
const dataUri = (f) => `data:image/png;base64,${fs.readFileSync(path.join(repo, f)).toString("base64")}`;

let html = read("index.html");
const inlined = [];

// Stylesheet → <style>.
html = html.replace(/<link rel="stylesheet" href="(css\/[^"]+)">/g, (m, href) => {
  inlined.push(href);
  return `<style>\n/* ===== ${href} ===== */\n${safeStyle(read(href))}\n</style>`;
});

// Local scripts → inline <script>, same order. CDN scripts stay as they are.
html = html.replace(/<script src="((?:js|clause-derby\/src)\/[^"]+)"><\/script>/g, (m, src) => {
  inlined.push(src);
  return `<script>\n/* ===== ${src} ===== */\n${safeScript(read(src))}\n</script>`;
});

// Icons → data URIs; the manifest needs separate files, so it goes.
html = html.replace(/<link rel="(icon|apple-touch-icon)"([^>]*?) href="(icons\/[^"]+)">/g, (m, rel, attrs, href) => {
  inlined.push(href);
  return `<link rel="${rel}"${attrs} href="${dataUri(href)}">`;
});
html = html.replace(/<link rel="manifest"[^>]*>\n?/, "");

html = html.replace("<!doctype html>", "<!doctype html>\n<!-- SatWizz single-file build, generated by scripts/build-single.js from the project sources. Edit those, then rebuild. -->");

// Nothing local may be left behind.
const leftovers = html.match(/(?:src|href)="(?!https?:|data:|#)[^"]+"/g) || [];
if (leftovers.length) {
  console.error("Unresolved local references:", leftovers);
  process.exit(1);
}

const out = path.join(repo, "dist", "index.html");
fs.mkdirSync(path.dirname(out), { recursive: true });
fs.writeFileSync(out, html);
console.log(`wrote ${path.relative(repo, out)} (${(html.length / 1024).toFixed(0)} KB, ${inlined.length} files inlined)`);
