// Builds the whole SatWizz app as ONE self-contained HTML file:
//
//   node scripts/build-single.js      → dist/index.html
//
// It reads the real index.html and inlines everything it loads locally:
// css/styles.css, every js/… script (in the same order), and the icons (as
// data URIs). The result runs by double-click or from any static host.
//
// What stays external, on purpose:
//   • Google Fonts (optional; system fonts are used offline).
//   • The Supabase client from its CDN (optional; without it, or without keys
//     in js/config.js, SatWizz runs in guest mode with localStorage).
//   • sw.js: browsers require a service worker to be its own file, so Lock In
//     *push* alerts work only if sw.js is uploaded next to index.html. In-app
//     Lock In banners and everything else work from the single file.
// The web app manifest is dropped (it needs separate files to be installable).
//
// It also writes dist/privacy.html and dist/terms.html from js/legal.js:
// standalone pages with their own web addresses, for Google's sign-in screen.
// Upload them next to index.html.
//
// Re-run after changing index.html, css/ or js/.
"use strict";

const fs = require("fs");
const path = require("path");

const repo = path.resolve(__dirname, "..");
const read = (f) => fs.readFileSync(path.join(repo, f), "utf8");
const safeScript = (code) => code.replace(/<\/script/gi, "<\\/script");
const safeStyle = (code) => code.replace(/<\/style/gi, "<\\/style");
const dataUri = (f) => `data:image/png;base64,${fs.readFileSync(path.join(repo, f)).toString("base64")}`;

let html = read("index.html");
const inlined = [];

// Stylesheet → <style>.
html = html.replace(/<link rel="stylesheet" href="(css\/[^"]+)">/g, (m, href) => {
  inlined.push(href);
  return `<style>\n/* ===== ${href} ===== */\n${safeStyle(read(href))}\n</style>`;
});

// Local scripts → inline <script>, same order. CDN scripts stay as they are.
html = html.replace(/<script src="((?:js|clause-derby\/src)\/[^"]+)"><\/script>/g, (m, src) => {
  inlined.push(src);
  return `<script>\n/* ===== ${src} ===== */\n${safeScript(read(src))}\n</script>`;
});

// Icons → data URIs; the manifest needs separate files, so it goes.
html = html.replace(/<link rel="(icon|apple-touch-icon)"([^>]*?) href="(icons\/[^"]+)">/g, (m, rel, attrs, href) => {
  inlined.push(href);
  return `<link rel="${rel}"${attrs} href="${dataUri(href)}">`;
});
html = html.replace(/<link rel="manifest"[^>]*>\n?/, "");

html = html.replace("<!doctype html>", "<!doctype html>\n<!-- SatWizz single-file build, generated by scripts/build-single.js from the project sources. Edit those, then rebuild. -->");

// Nothing local may be left behind.
const leftovers = html.match(/(?:src|href)="(?!https?:|data:|mailto:|#)[^"]+"/g) || [];
if (leftovers.length) {
  console.error("Unresolved local references:", leftovers);
  process.exit(1);
}

const out = path.join(repo, "dist", "index.html");
fs.mkdirSync(path.dirname(out), { recursive: true });
fs.writeFileSync(out, html);
console.log(`wrote ${path.relative(repo, out)} (${(html.length / 1024).toFixed(0)} KB, ${inlined.length} files inlined)`);

// ---------- Standalone Privacy Policy and Terms of Service ----------
const vm = require("vm");
const sandbox = { window: {} };
vm.runInNewContext(read("js/legal.js"), sandbox);
const legal = sandbox.window.SatWizz.legal;
const page = (kind) => {
  const d = legal.LEGAL[kind];
  // Links between the documents point at the other page instead of the in-site overlay.
  const body = legal.bodyHtml(kind).replace(/href="#(privacy|terms)" data-legal="\1"/g, 'href="$1.html"');
  return `<!doctype html>
<!-- Generated by scripts/build-single.js from js/legal.js. Edit that, then rebuild. -->
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${d.title} · ${legal.OWNER}</title>
<meta name="description" content="${legal.OWNER} ${d.title}">
<script>
(function () {
  var t = "dark";
  try { t = localStorage.getItem("satwizz.theme") || "dark"; } catch (e) { /* storage blocked */ }
  if (t === "dark" || t === "light") document.documentElement.setAttribute("data-theme", t);
})();
</script>
<style>
:root { --bg: #eaeef8; --surface: #ffffff; --surface-2: #f2f4fb; --ink: #16213a; --muted: #5a6680; --line: #d5dbea; --volt: #3b4ff0; color-scheme: light; }
:root[data-theme="dark"] { --bg: #0d1322; --surface: #151d31; --surface-2: #1c2640; --ink: #e9edf8; --muted: #9aa6c2; --line: #2a3654; --volt: #8193ff; color-scheme: dark; }
@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) { --bg: #0d1322; --surface: #151d31; --surface-2: #1c2640; --ink: #e9edf8; --muted: #9aa6c2; --line: #2a3654; --volt: #8193ff; color-scheme: dark; }
}
* { box-sizing: border-box; }
body { margin: 0; background: var(--bg); color: var(--ink); font: 16px/1.6 system-ui, -apple-system, "Segoe UI", Roboto, sans-serif; }
main { max-width: 760px; margin: 0 auto; padding: 24px 16px 48px; }
.card { background: var(--surface); border: 1px solid var(--line); border-radius: 18px; padding: 24px 20px; display: grid; gap: 12px; }
h1 { margin: 0; font-size: 1.7rem; line-height: 1.2; }
h3 { margin: 10px 0 0; font-size: 1.05rem; }
p, ul { margin: 0; }
ul { padding-left: 1.2em; display: grid; gap: 4px; }
section { display: grid; gap: 6px; }
a { color: var(--volt); font-weight: 600; }
.brand { font-weight: 800; font-size: 1.1rem; text-decoration: none; color: var(--ink); }
.brand span { color: var(--volt); }
.top { display: flex; justify-content: space-between; align-items: center; margin-bottom: 14px; gap: 12px; }
.legal-date, .legal-foot { color: var(--muted); font-size: 0.9rem; }
.legal-summary { padding: 12px 16px; border-radius: 12px; background: var(--surface-2); border: 1px solid var(--line); }
.legal-summary ul { margin-top: 6px; }
</style>
</head>
<body>
<main>
  <div class="top"><a class="brand" href="./">Sat<span>Wizz</span></a><a href="./">← Back to SatWizz</a></div>
  <article class="card">
    <h1>${d.title}</h1>
    ${body}
  </article>
</main>
</body>
</html>
`;
};
for (const kind of ["privacy", "terms"]) {
  const file = path.join(repo, "dist", `${kind}.html`);
  fs.writeFileSync(file, page(kind));
  console.log(`wrote ${path.relative(repo, file)}`);
}
