// Vocab Vault bank: core words, A–C. Format: see js/vocab/bank.js.
window.SatWizzBank("core", `
abandon|v|to leave behind or give up completely|desert, forsake, quit|keep, maintain|Old French a bandon (under another's control)|When the storm grew worse, the hikers had to ______ their plan to reach the summit and turn back.
abundant|adj|existing in large quantities; more than enough|plentiful, ample, copious|scarce, sparse|Latin abundare (to overflow)|After the spring rains, wildflowers were so ______ that the hillside looked purple from miles away.
accessible|adj|easy to reach, enter, or understand|reachable, available, approachable|inaccessible, remote|Latin accedere (to approach)|The museum added ramps and elevators so that every gallery would be ______ to visitors using wheelchairs.
accommodate|v|to make room for or adjust to meet someone's needs|house, adapt, oblige|refuse, reject|Latin accommodare (to make fit)|The small theater added extra rows of seats to ______ the unexpectedly large crowd.
accumulate|v|to gather or build up gradually over time|amass, collect, gather|disperse, scatter|Latin ad- (to) + cumulus (heap)|If you never empty the gutters, leaves and twigs will ______ until water can no longer drain.
accurate|adj|correct and free of errors|precise, exact, correct|inaccurate, wrong|Latin accuratus (done with care)|{{NAME_1}} double-checked every measurement so that the final map would be completely ______.
acknowledge|v|to admit or recognize that something is true or exists|admit, recognize, concede|deny, ignore|Old English on + knowledge|After reviewing the replay, the referee had to ______ that the call had been a mistake.
acquire|v|to get or gain something, often through effort|obtain, gain, procure|lose, forfeit|Latin ad- (to) + quaerere (to seek)|Over three summers of practice, {{NAME_1}} managed to ______ real skill in {{SKILL}}.
adapt|v|to change in order to suit new conditions|adjust, modify, acclimate|resist, persist|Latin ad- (to) + aptare (to fit)|Animals that live in the desert must ______ to extreme heat and very little water.
adequate|adj|enough or good enough for a particular need|sufficient, acceptable, satisfactory|inadequate, insufficient|Latin adaequare (to make equal)|The old gym was not ideal, but it was ______ for a few weeks of practice.
adhere|v|to stick to something or follow it closely|stick, cling, comply|detach, disregard|Latin ad- (to) + haerere (to stick)|Players who do not ______ to the safety rules will be removed from the game.
adjacent|adj|next to or very near something else|neighboring, adjoining, bordering|distant, separate|Latin ad- (near) + jacere (to lie)|The library is ______ to the cafeteria, so students can walk between them in seconds.
advantageous|adj|providing a benefit or favorable position|beneficial, favorable, helpful|disadvantageous, harmful|French avantage (benefit)|Starting the race on the inside lane proved ______, since it was the shortest path around the track.
adverse|adj|harmful or unfavorable|unfavorable, hostile, harmful|favorable, beneficial|Latin adversus (turned against)|The new medicine works well for most patients, though a few experience ______ side effects.
aesthetic|adj|concerned with beauty or artistic taste|artistic, visual, decorative|practical, functional|Greek aisthetikos (of perception)|The architect cared about function, but she also made ______ choices, like the curved glass entrance.
affirm|v|to state firmly or confirm that something is true|assert, confirm, declare|deny, contradict|Latin affirmare (to make firm)|The witness was asked to ______ under oath that her account was accurate.
aggregate|n|a total formed by combining several separate parts|total, sum, whole|part, piece|Latin aggregare (to add to a flock)|No single test decides your grade; the final mark is the ______ of all twelve quizzes.
alleviate|v|to make pain or a problem less severe|relieve, ease, lessen|aggravate, worsen|Latin ad- + levis (light)|Planting trees along the street helped ______ the summer heat for people waiting at the bus stop.
allocate|v|to set aside or distribute for a particular purpose|assign, allot, distribute|withhold, hoard|Latin ad- + locare (to place)|The club decided to ______ half of its budget to new equipment and half to travel.
alter|v|to change or make different|change, modify, adjust|preserve, maintain|Latin alter (other)|The tailor offered to ______ the jacket so that the sleeves would be shorter.
alternative|n|another possible choice or option|option, substitute, choice|necessity, requirement|Latin alternus (one after another)|If the bridge is closed, the ferry is the only ______ for crossing the river.
ambition|n|a strong desire to achieve something|drive, aspiration, determination|apathy, indifference|Latin ambitio (going around seeking votes)|{{NAME_1}}'s ______ to become a doctor kept {{NAME_1_OBJ}} studying long after everyone else had gone home.
amend|v|to make small changes to improve something|revise, modify, correct|preserve, retain|Latin emendare (to free from fault)|The student council voted to ______ its rules so that freshmen could also serve as officers.
analogy|n|a comparison between two things to explain or clarify|comparison, parallel, likeness|difference, contrast|Greek analogia (proportion)|The teacher used ______ to explain electricity, comparing a wire to a pipe carrying water.
analyze|v|to examine something closely in order to understand it|examine, study, evaluate|ignore, overlook|Greek analyein (to break up)|Before writing the report, {{NAME_1}} had to ______ two years of attendance data.
anecdote|n|a short, interesting story about a real event|story, account, tale|statistics, data|Greek anekdota (unpublished things)|The speaker opened with a funny ______ about getting lost on the way to her first job interview.
anomaly|n|something that differs from what is normal or expected|irregularity, oddity, exception|norm, rule|Greek anomalos (uneven)|Every reading was normal except one strange ______: a temperature of 140 degrees on a cool morning.
anticipate|v|to expect or predict and prepare for something|expect, foresee, predict|overlook, ignore|Latin ante- (before) + capere (to take)|The organizers did not ______ such a large crowd, so they ran out of programs within an hour.
apathy|n|lack of interest or concern|indifference, unconcern, detachment|enthusiasm, passion|Greek a- (without) + pathos (feeling)|Voter ______ was so widespread that fewer than one in five residents bothered to vote.
apparent|adj|clearly visible or understood; obvious|obvious, evident, clear|hidden, obscure|Latin apparere (to appear)|It was ______ from the muddy footprints that someone had walked through the kitchen.
appease|v|to calm someone by giving them what they want|pacify, placate, soothe|provoke, anger|Old French a pais (to peace)|To ______ the angry customers, the manager offered everyone a free meal.
appreciate|v|to recognize the value or quality of something|value, admire, treasure|disregard, belittle|Latin ad- + pretium (price)|After a week of camping, {{NAME_1}} learned to ______ simple things like hot water and a soft bed.
apprehensive|adj|anxious or fearful that something bad will happen|anxious, uneasy, nervous|confident, calm|Latin apprehendere (to seize)|{{NAME_1}} felt ______ before the audition, worried that {{NAME_1_POSS}} voice would crack.
arduous|adj|requiring great effort; difficult and tiring|strenuous, grueling, demanding|easy, effortless|Latin arduus (steep)|The climb to the summit was ______, taking nine hours over steep and rocky ground.
articulate|adj|able to express ideas clearly and effectively|eloquent, clear, fluent|inarticulate, incoherent|Latin articulus (small joint)|{{NAME_1}} was so ______ in the debate that even the opposing team praised {{NAME_1_POSS}} clear arguments.
ascertain|v|to find out for certain|determine, discover, establish|guess, assume|Old French acertener (to make certain)|Detectives worked for weeks to ______ exactly when the painting had been taken.
aspire|v|to have a strong hope of achieving something|aim, seek, hope|settle, give up|Latin aspirare (to breathe upon)|Many young musicians ______ to play in a national orchestra one day.
assert|v|to state something confidently and forcefully|declare, claim, maintain|deny, retract|Latin asserere (to claim)|The lawyer continued to ______ that her client had been out of town on the night of the theft.
assess|v|to judge or evaluate the quality or value of something|evaluate, appraise, gauge|ignore, neglect|Latin assidere (to sit beside, as a judge)|The coach watched the tryouts to ______ which players were ready for the varsity team.
assimilate|v|to absorb and fully understand information or ideas|absorb, integrate, digest|reject, exclude|Latin assimilare (to make like)|It took the new employees a month to ______ all of the company's procedures.
astute|adj|clever at noticing things and making good judgments|shrewd, perceptive, sharp|foolish, naive|Latin astutus (crafty)|Always ______ about money, {{NAME_1}} noticed the trend months before other investors did.
attain|v|to succeed in reaching or achieving something|achieve, reach, accomplish|fail, miss|Latin attingere (to touch)|With steady practice, the team was able to ______ its goal of a winning season.
attribute|v|to regard something as caused by someone or something|credit, ascribe, assign|dissociate, separate|Latin attribuere (to assign)|Doctors ______ the drop in flu cases to the school's new vaccination program.
augment|v|to make something greater by adding to it|increase, expand, enlarge|reduce, decrease|Latin augere (to increase)|{{NAME_1}} took a weekend job to ______ the small income {{NAME_1}} earned from tutoring.
authentic|adj|real and genuine; not fake|genuine, real, original|fake, counterfeit|Greek authentikos (original)|Experts confirmed that the signature on the old letter was ______ and not a forgery.
autonomy|n|freedom to make one's own decisions|independence, self-rule, freedom|dependence, control|Greek autos (self) + nomos (law)|Older students were given more ______, choosing their own research topics and deadlines.
benevolent|adj|kind and generous; wanting to help others|kind, charitable, generous|cruel, malicious|Latin bene (well) + volens (wishing)|The ______ shop owner gave free meals to anyone who could not afford to pay.
bias|n|an unfair preference for or against something|prejudice, partiality, favoritism|fairness, impartiality|Old French biais (slant)|The judges were chosen from other towns to avoid any ______ toward the local team.
bolster|v|to support or strengthen|strengthen, reinforce, boost|weaken, undermine|Old English bolster (cushion)|The new evidence helped ______ the scientist's theory, which many had doubted.
brevity|n|the quality of being short or concise|conciseness, shortness, succinctness|wordiness, length|Latin brevis (short)|The audience loved the speech for its ______: it lasted barely three minutes.
candor|n|the quality of being open and honest|honesty, frankness, openness|deceit, evasiveness|Latin candor (whiteness, purity)|Reporters appreciated the mayor's ______ when she admitted that the plan had failed.
capacity|n|the maximum amount something can hold or do|volume, capability, ability|inability, incapacity|Latin capax (able to hold)|The stadium's ______ is fifty thousand people, and every seat was filled for the final.
catalyst|n|something that causes or speeds up an important change|trigger, spark, stimulus|obstacle, hindrance|Greek katalysis (dissolving)|The new coach was the ______ for the team's turnaround, inspiring players to train harder than ever.
caution|n|care taken to avoid danger or mistakes|care, prudence, wariness|recklessness, carelessness|Latin cavere (to beware)|The icy roads called for extreme ______, so the bus driver slowed to a crawl.
cease|v|to come or bring to an end|stop, halt, end|begin, continue|Latin cessare (to stop)|The factory will ______ operations next month after nearly a century in business.
chronological|adj|arranged in the order in which events happened|sequential, ordered, consecutive|random, disordered|Greek chronos (time) + logos (account)|The museum's timeline is ______, starting with the town's founding and ending with today.
circumvent|v|to find a way around an obstacle or rule|bypass, evade, sidestep|confront, face|Latin circum (around) + venire (to come)|The engineers built a temporary road to ______ the flooded section of the highway.
clarify|v|to make something easier to understand|explain, illuminate, simplify|confuse, obscure|Latin clarus (clear)|The teacher drew a diagram on the board to ______ the difference between the two terms.
coherent|adj|logical and consistent; easy to follow|logical, clear, consistent|incoherent, confused|Latin cohaerere (to stick together)|After a night of rest, {{NAME_1}}'s account of what had happened was finally clear and ______.
collaborate|v|to work together with others on a task|cooperate, team up, join forces|compete, work alone|Latin com- (with) + laborare (to work)|Students from three schools will ______ on a single robot for the national competition.
commend|v|to praise formally or officially|praise, applaud, compliment|criticize, condemn|Latin commendare (to entrust)|The mayor will ______ the volunteers for their tireless work during the flood.
compatible|adj|able to exist or work together without conflict|harmonious, consistent, suited|incompatible, conflicting|Latin compati (to suffer with)|The new charger is ______ with every phone model sold in the last five years.
compensate|v|to make up for something, often by paying|repay, offset, reimburse|deprive, penalize|Latin compensare (to weigh together)|To ______ for the canceled flight, the airline gave every passenger a free ticket.
competent|adj|having enough skill to do something well|capable, skilled, qualified|incompetent, unqualified|Latin competere (to be fit)|{{NAME_1}} was not the fastest typist, but {{NAME_1}} was ______ enough to finish the report on time.
complacent|adj|too satisfied with oneself to see danger or the need to improve|smug, self-satisfied, careless|vigilant, concerned|Latin complacere (to please)|After three easy wins, the team grew ______ and stopped practicing hard.
complement|v|to complete or improve something by adding to it|enhance, complete, supplement|clash, detract|Latin complere (to fill up)|The bright scarf was chosen to ______ the gray coat.
comprehensive|adj|including all or nearly all parts of something|thorough, complete, extensive|limited, partial|Latin comprehendere (to grasp)|The final exam was ______, covering every chapter from the entire year.
comprise|v|to consist of or be made up of|include, contain, consist of|exclude, omit|French compris (included)|The committee will ______ five teachers, three parents, and two students.
concise|adj|giving information clearly in few words|brief, succinct, short|wordy, rambling|Latin concidere (to cut up)|The editor asked that every summary be ______: no more than fifty words.
concur|v|to agree with someone's opinion|agree, assent, accord|disagree, dissent|Latin con- (together) + currere (to run)|All three judges ______ that the final dive deserved a perfect score.
condone|v|to accept or allow behavior that is wrong|excuse, overlook, permit|condemn, forbid|Latin condonare (to give up entirely)|The principal made it clear that she would not ______ cheating of any kind.
conducive|adj|making a certain outcome likely or possible|favorable, helpful, beneficial|unfavorable, harmful|Latin conducere (to bring together)|The quiet, well-lit library is ______ to long hours of studying.
confide|v|to tell someone a secret because you trust them|reveal, disclose, entrust|conceal, withhold|Latin confidere (to trust fully)|{{NAME_1}} decided to ______ in {{NAME_2}}, sharing a worry {{NAME_1}} had told no one else.
conform|v|to follow accepted rules or standards|comply, obey, fit in|rebel, deviate|Latin conformare (to shape)|All new buildings must ______ to the city's safety code.
consensus|n|general agreement among a group|agreement, accord, unanimity|disagreement, discord|Latin consentire (to agree)|After two hours of discussion, the group finally reached ______ on where to hold the picnic.
consequence|n|a result or effect of an action|result, outcome, effect|cause, origin|Latin consequi (to follow closely)|Missing the bus had one unfortunate ______: {{NAME_1}} was late for the final exam.
considerable|adj|large in size, amount, or importance|substantial, significant, sizable|negligible, minor|Latin considerare (to examine)|The new bridge saved commuters ______ time, cutting the trip from an hour to twenty minutes.
consistent|adj|acting or done the same way over time|steady, reliable, constant|inconsistent, erratic|Latin consistere (to stand firm)|{{NAME_1}}'s grades were ______ all year, never dropping below a B.
conspicuous|adj|easy to notice; standing out|noticeable, obvious, prominent|inconspicuous, hidden|Latin conspicere (to look at attentively)|In {{NAME_1_POSS}} bright orange jacket, {{NAME_1}} was ______ in the crowd of gray suits.
constrain|v|to restrict or limit|restrict, limit, confine|free, liberate|Latin constringere (to bind tightly)|A tight budget will ______ the club's travel plans this year.
contemplate|v|to think deeply about something for a long time|consider, ponder, reflect on|ignore, disregard|Latin contemplari (to observe)|{{NAME_1}} sat by the lake to ______ whether to accept the job offer across the country.
contemporary|adj|belonging to the present time; modern|modern, current, present-day|ancient, old-fashioned|Latin con- (with) + tempus (time)|The gallery shows only ______ art, made by artists who are still working today.
contend|v|to argue or claim that something is true|argue, maintain, assert|concede, deny|Latin contendere (to strive)|Some historians ______ that the war could have been avoided entirely.
contradict|v|to say the opposite of something; to deny|dispute, deny, oppose|confirm, agree|Latin contra (against) + dicere (to say)|The second witness went on to ______ the first, insisting the car had been blue, not red.
controversial|adj|causing strong public disagreement|disputed, contentious, divisive|uncontroversial, accepted|Latin controversus (turned against)|The plan to close the park was ______, with hundreds of residents protesting at city hall.
convey|v|to communicate or make an idea known|communicate, express, transmit|conceal, withhold|Latin conviare (to accompany)|The painting manages to ______ a deep sense of loneliness without showing a single face.
cordial|adj|warm and friendly in a polite way|friendly, warm, gracious|hostile, unfriendly|Latin cor (heart)|Although the two rivals had argued for years, their meeting was surprisingly ______.
credible|adj|able to be believed; trustworthy|believable, plausible, reliable|unbelievable, dubious|Latin credere (to believe)|The reporter refused to publish the story until she found sources that were ______ enough to confirm it.
criteria|n|standards used to judge or decide something|standards, measures, benchmarks|guesses, whims|Greek kriterion (means of judging)|The judges announced their ______ in advance: creativity, accuracy, and presentation.
crucial|adj|extremely important; decisive|vital, essential, critical|trivial, unimportant|Latin crux (cross)|Getting enough sleep before the test is ______, since tired students make more mistakes.
cultivate|v|to develop or improve through effort|develop, nurture, foster|neglect, abandon|Latin cultivare (to till)|{{NAME_1}} worked hard to ______ good habits, like reading for twenty minutes every night.
cumulative|adj|increasing by successive additions|accumulated, collective, growing|individual, single|Latin cumulus (heap)|The ______ effect of small daily savings was a fund large enough to buy a car.
curtail|v|to reduce or limit something|reduce, cut back, restrict|extend, expand|French court (short)|The city had to ______ bus service on weekends because of a shortage of drivers.
cynical|adj|believing that people act only out of selfishness|distrustful, skeptical, pessimistic|trusting, optimistic|Greek kynikos (doglike; a school of philosophers)|After so many broken promises, the voters had grown ______ about every new campaign pledge.
`);
