// Vocab Vault bank: core words, D–F. Format: see js/vocab/bank.js.
window.SatWizzBank("core", `
daunting|adj|seeming difficult to deal with; intimidating|intimidating, formidable, overwhelming|easy, manageable|Latin domitare (to tame)|The pile of unread textbooks looked ______ at first, but {{NAME_1}} finished one chapter at a time.
debate|v|to discuss or argue about something formally|discuss, argue, dispute|agree, accept|Old French debatre (to fight)|The council will ______ the new parking rules at Tuesday's meeting before voting.
decisive|adj|settling an issue; able to make decisions quickly|conclusive, determined, firm|indecisive, hesitant|Latin decidere (to cut off)|The goal in the final minute was ______, giving the team its first championship.
decline|v|to become smaller or worse; to refuse politely|decrease, diminish, refuse|increase, accept|Latin declinare (to turn aside)|Sales of paper maps began to ______ as more drivers used phone navigation.
deduce|v|to reach a conclusion by reasoning from evidence|infer, conclude, reason|guess, assume|Latin de- (from) + ducere (to lead)|From the wet umbrella by the door, {{NAME_1}} was able to ______ that it was raining outside.
defer|v|to put off until later; to yield to another's judgment|postpone, delay, yield|hasten, advance|Latin differre (to carry apart)|The committee agreed to ______ the vote until all members could attend.
deficient|adj|lacking something necessary; not good enough|lacking, inadequate, insufficient|sufficient, adequate|Latin deficere (to fail)|The doctor found that {{NAME_1}}'s diet was ______ in iron, which explained the constant tiredness.
definitive|adj|final and authoritative; not able to be questioned|conclusive, final, authoritative|tentative, provisional|Latin definire (to set bounds)|The new biography is considered ______, the most complete account of the inventor's life ever written.
degrade|v|to lower in quality or condition|deteriorate, worsen, damage|improve, enhance|Latin de- (down) + gradus (step)|Over time, sunlight will ______ the plastic until it cracks and crumbles.
deliberate|adj|done on purpose; slow and careful|intentional, planned, careful|accidental, hasty|Latin deliberare (to weigh well)|The foul was clearly ______; the player looked right at the referee before tripping his opponent.
delineate|v|to describe or outline precisely|outline, define, describe|blur, confuse|Latin de- + linea (line)|The contract will ______ exactly which tasks each partner is responsible for.
demonstrate|v|to show clearly by giving proof or examples|show, prove, display|conceal, disprove|Latin demonstrare (to point out)|The science fair project was designed to ______ how plants grow toward light.
denounce|v|to publicly declare something wrong or evil|condemn, criticize, censure|praise, endorse|Latin denuntiare (to announce)|Leaders from every party came forward to ______ the attack on the peaceful protesters.
depict|v|to show or represent in a picture or words|portray, represent, illustrate|misrepresent, distort|Latin depingere (to paint)|The mural on the library wall is meant to ______ the town's history from its founding to today.
deplete|v|to use up the supply of something|exhaust, drain, consume|replenish, restore|Latin deplere (to empty out)|A long, dry summer can ______ the reservoir until there is barely any water left.
derive|v|to obtain something from a source|obtain, draw, extract|originate, create|Latin derivare (to draw off water)|Many English words ______ from Latin, which is why roots are useful to memorize.
designate|v|to officially choose for a particular purpose|appoint, assign, name|reject, dismiss|Latin designare (to mark out)|The city will ______ the old factory as a historic site, protecting it from demolition.
deter|v|to discourage someone from doing something|discourage, prevent, dissuade|encourage, motivate|Latin de- (away) + terrere (to frighten)|Bright lights and cameras are meant to ______ thieves from breaking into the parking lot.
detrimental|adj|causing harm or damage|harmful, damaging, destructive|beneficial, helpful|Latin detrimentum (loss)|Staying up all night before an exam can be ______ to your performance.
deviate|v|to depart from a usual or expected course|stray, diverge, depart|conform, follow|Latin de- (from) + via (way)|The pilot had to ______ from the planned route to avoid a thunderstorm.
devise|v|to plan or invent something clever|invent, design, create|destroy, copy|Old French deviser (to divide, plan)|The engineers had to ______ a way to carry water to the village without electricity.
devoid|adj|completely lacking in something|lacking, empty, free of|full, rich|Old French devoidier (to empty out)|The desert landscape was ______ of trees, with nothing but sand for miles.
dexterity|n|skill in using the hands or mind|skill, agility, adroitness|clumsiness, awkwardness|Latin dexter (right-handed, skillful)|Repairing a watch requires great ______, since the parts are smaller than grains of rice.
dichotomy|n|a sharp division between two opposing things|division, contrast, split|unity, sameness|Greek dicha (in two) + temnein (to cut)|The novel explores the ______ between city life and country life.
diligent|adj|showing steady, careful effort|hardworking, industrious, conscientious|lazy, careless|Latin diligere (to value highly)|{{NAME_1}} was ______ about homework, finishing every assignment the day it was given.
diminutive|adj|extremely small|tiny, small, little|enormous, huge|Latin deminuere (to lessen)|The ______ dog barely came up to {{NAME_1}}'s ankle, but its bark was enormous.
discourse|n|serious discussion or conversation about a topic|discussion, dialogue, debate|silence, quiet|Latin discursus (running to and fro)|The podcast was praised for raising the level of public ______ about science.
discrepancy|n|a difference between things that should match|inconsistency, difference, mismatch|agreement, consistency|Latin discrepare (to sound differently)|The accountant traced the ______ between the receipts and the bank statement to a single typo.
discretion|n|the freedom to decide; good judgment about what to say|judgment, prudence, choice|recklessness, indiscretion|Latin discernere (to separate)|The teacher left it to each student's ______ whether to write a poem or an essay.
disdain|n|the feeling that someone or something is unworthy of respect|contempt, scorn, derision|respect, admiration|Old French desdeignier (to scorn)|The critic made no effort to hide her ______ for the film, calling it a waste of time.
disparate|adj|so different that they cannot be compared|different, distinct, dissimilar|similar, alike|Latin disparare (to separate)|The festival brings together ______ groups, from jazz musicians to folk dancers.
disperse|v|to spread or scatter over a wide area|scatter, spread, dissipate|gather, assemble|Latin dispergere (to scatter)|When the rain started, the crowd in the square began to ______ in every direction.
disregard|v|to pay no attention to; to ignore|ignore, overlook, neglect|heed, regard|dis- (not) + regard|Drivers who ______ the speed limit near schools face steep fines.
disrupt|v|to interrupt or disturb the normal course of something|interrupt, disturb, upset|maintain, support|Latin dis- (apart) + rumpere (to break)|A loud phone alarm can ______ an entire class during a test.
dissent|n|disagreement with an official or popular opinion|disagreement, opposition, objection|agreement, consent|Latin dis- (apart) + sentire (to feel)|Although most members supported the plan, there was some ______ from the youngest voters.
distinct|adj|clearly different or separate|separate, different, unmistakable|similar, vague|Latin distinguere (to separate)|The twins have ______ personalities: one is outgoing and the other is shy.
diverse|adj|showing a great deal of variety|varied, assorted, mixed|uniform, identical|Latin divertere (to turn aside)|The school's ______ student body includes people from more than forty countries.
divulge|v|to reveal information that was secret|reveal, disclose, expose|conceal, hide|Latin divulgare (to publish)|The reporter refused to ______ the name of her source, even under pressure.
dogmatic|adj|insisting that one's beliefs are true without considering others|rigid, inflexible, opinionated|open-minded, flexible|Greek dogma (opinion)|{{NAME_1}} was so ______ about the rules that no one could suggest any changes.
dominant|adj|most important, powerful, or influential|leading, controlling, prevailing|subordinate, minor|Latin dominari (to rule)|For a decade the team was ______ in the league, losing only a handful of games.
dormant|adj|temporarily inactive or asleep|inactive, sleeping, latent|active, awake|Latin dormire (to sleep)|The volcano has been ______ for three hundred years, but scientists still monitor it.
drastic|adj|extreme and having a strong effect|extreme, severe, radical|mild, moderate|Greek drastikos (effective)|After losing every game, the coach made ______ changes, replacing half the starting lineup.
dubious|adj|doubtful; probably not true or honest|doubtful, questionable, suspicious|certain, reliable|Latin dubium (doubt)|The website's claims about the miracle diet were ______, and none of them cited any research.
durable|adj|able to last a long time without wearing out|sturdy, long-lasting, tough|fragile, flimsy|Latin durare (to last)|Hiking boots need to be ______ enough to survive years of rocks and mud.
eccentric|adj|unusual or strange in a harmless way|odd, quirky, unconventional|ordinary, conventional|Greek ek- (out of) + kentron (center)|The ______ professor wore a different colored bow tie every day of the week.
eclectic|adj|drawn from many different sources or styles|varied, diverse, wide-ranging|narrow, uniform|Greek eklegein (to pick out)|{{NAME_1}}'s playlist is ______, mixing classical piano, hip-hop, and old country songs.
efficacy|n|the ability to produce the intended result|effectiveness, success, potency|ineffectiveness, failure|Latin efficax (powerful)|Researchers tested the ______ of the new vaccine on thousands of volunteers.
efficient|adj|working well without wasting time or energy|productive, effective, economical|inefficient, wasteful|Latin efficere (to accomplish)|The new dishwasher is more ______, cleaning twice as many plates with half the water.
elaborate|adj|detailed and complicated|detailed, intricate, complex|simple, plain|Latin elaborare (to work out)|The wedding cake was so ______ that it had six layers and hundreds of sugar flowers.
elicit|v|to draw out a response or reaction|evoke, draw out, provoke|suppress, stifle|Latin elicere (to lure out)|The comedian's first joke did not ______ a single laugh from the audience.
eloquent|adj|fluent and persuasive in speaking or writing|articulate, expressive, persuasive|inarticulate, tongue-tied|Latin eloqui (to speak out)|{{NAME_1}}'s speech was so ______ that several people in the audience were moved to tears.
elusive|adj|difficult to find, catch, or achieve|evasive, slippery, hard to pin down|obvious, accessible|Latin eludere (to escape)|Despite years of searching, the rare bird remained ______, and no one managed to photograph it.
embellish|v|to make more attractive by adding details, sometimes untrue ones|decorate, exaggerate, adorn|simplify, strip|Old French embellir (to make beautiful)|{{NAME_1}} tends to ______ every story, so a small fish quickly becomes a giant one.
emerge|v|to come out or become known|appear, arise, surface|disappear, vanish|Latin emergere (to rise out)|After weeks of investigation, new details began to ______ about the missing painting.
eminent|adj|famous and respected in a particular field|distinguished, renowned, prominent|unknown, obscure|Latin eminere (to stand out)|The conference featured ______ scientists from around the world, including two Nobel winners.
empathy|n|the ability to understand and share another's feelings|compassion, understanding, sympathy|indifference, coldness|Greek em- (in) + pathos (feeling)|{{NAME_1}}'s ______ made {{NAME_1_OBJ}} a wonderful nurse; patients felt truly understood.
emphasize|v|to give special importance to something|stress, highlight, underline|minimize, downplay|Greek emphasis (display)|The coach would always ______ defense, reminding players that games are won by stopping goals.
emulate|v|to try to match or copy someone admired|imitate, copy, follow|ignore, differ from|Latin aemulari (to rival)|Young players often ______ their heroes, copying their moves and even their haircuts.
encompass|v|to include a wide range of things|include, cover, contain|exclude, omit|en- (in) + compass|The new course will ______ everything from ancient history to modern politics.
endeavor|n|a serious attempt to achieve something|effort, attempt, venture|inaction, idleness|French en devoir (in duty)|Building the community garden was a group ______ that took the whole summer.
endorse|v|to declare public support or approval|support, approve, back|oppose, reject|Latin in- + dorsum (back)|Three former mayors decided to ______ the young candidate, giving her campaign a big boost.
endure|v|to suffer patiently; to continue to exist|withstand, bear, last|surrender, perish|Latin indurare (to harden)|The old oak tree managed to ______ storms for over two hundred years.
enhance|v|to improve the quality or value of|improve, boost, strengthen|diminish, worsen|Old French enhaucier (to raise)|Good lighting can ______ a photograph, making colors look richer.
enigmatic|adj|mysterious and difficult to understand|mysterious, puzzling, cryptic|clear, obvious|Greek ainigma (riddle)|{{NAME_1}}'s ______ smile left everyone wondering what {{NAME_1}} was really thinking.
enumerate|v|to list items one by one|list, itemize, count|summarize, generalize|Latin enumerare (to count out)|The guide will ______ the safety rules before the rafting trip begins.
equitable|adj|fair and impartial|fair, just, even-handed|unfair, biased|Latin aequus (equal)|The coach wanted playing time to be ______, so all twelve players got the same number of minutes.
erode|v|to wear away gradually|wear away, corrode, diminish|build up, strengthen|Latin erodere (to gnaw away)|Ocean waves slowly ______ the cliffs, moving the coastline inland each year.
erratic|adj|not regular or predictable|unpredictable, irregular, inconsistent|steady, consistent|Latin errare (to wander)|The old car's ______ engine would run perfectly one day and refuse to start the next.
erroneous|adj|wrong; containing errors|incorrect, mistaken, inaccurate|correct, accurate|Latin erroneus (wandering)|The newspaper printed a correction after publishing ______ figures about the budget.
escalate|v|to increase rapidly in size or seriousness|intensify, increase, worsen|decrease, de-escalate|from escalator (moving stairs)|What began as a small disagreement threatened to ______ into a shouting match.
essential|adj|absolutely necessary; extremely important|vital, necessary, crucial|unnecessary, optional|Latin essentia (being)|Water and a flashlight are ______ items in any emergency kit.
esteem|n|respect and admiration|respect, admiration, regard|contempt, disrespect|Latin aestimare (to value)|The retiring teacher was held in such high ______ that hundreds of former students attended her party.
evaluate|v|to judge the value or quality of something|assess, appraise, judge|ignore, neglect|French évaluer (to value)|The judges will ______ each project on creativity, accuracy, and presentation.
evoke|v|to bring a feeling or memory to mind|summon, elicit, conjure|suppress, stifle|Latin evocare (to call out)|The smell of fresh bread can ______ memories of {{NAME_1_POSS}} grandmother's kitchen.
exasperate|v|to irritate intensely|annoy, irritate, infuriate|soothe, please|Latin exasperare (to roughen)|The constant interruptions began to ______ the speaker, who finally stopped and asked for quiet.
exceed|v|to go beyond a limit or expected amount|surpass, outdo, top|fall short, trail|Latin excedere (to go out)|Ticket sales were expected to ______ last year's record by thousands.
exemplary|adj|serving as an excellent example|ideal, model, outstanding|deplorable, poor|Latin exemplum (example)|{{NAME_1}}'s attendance was ______: not a single absence in four years.
exhaustive|adj|including every possible detail; thorough|comprehensive, thorough, complete|partial, cursory|Latin exhaurire (to drain out)|The detective's search of the house was ______: she checked every drawer, closet, and shelf.
exonerate|v|to officially clear someone of blame|acquit, clear, absolve|convict, blame|Latin ex- (from) + onus (burden)|New DNA evidence helped ______ the man, who had spent years in prison for a crime he did not commit.
expedite|v|to make something happen faster|accelerate, hasten, speed up|delay, slow|Latin expedire (to free the feet)|Paying an extra fee will ______ the shipping, so the package arrives tomorrow.
explicit|adj|stated clearly and directly, leaving no doubt|clear, direct, specific|implicit, vague|Latin explicare (to unfold)|The instructions were ______: no phones may be used during the exam.
exploit|v|to use something unfairly for one's own advantage|take advantage of, misuse, abuse|respect, protect|Old French esploit (achievement)|The scammers tried to ______ elderly people's trust to steal their savings.
extensive|adj|covering a large area or amount|wide-ranging, broad, comprehensive|limited, narrow|Latin extendere (to stretch out)|The storm caused ______ damage across three counties.
extraneous|adj|not relevant or essential|irrelevant, unnecessary, superfluous|relevant, essential|Latin extraneus (external)|The editor cut every ______ detail, trimming the article to a single page.
fabricate|v|to invent something false in order to deceive|invent, make up, falsify|verify, tell the truth|Latin fabricare (to make)|The reporter was fired after it was discovered that she would ______ quotes from people who did not exist.
facilitate|v|to make an action or process easier|ease, enable, assist|hinder, obstruct|Latin facilis (easy)|The new software will ______ communication between teachers and parents.
fallacy|n|a mistaken belief or faulty reasoning|misconception, error, myth|truth, fact|Latin fallere (to deceive)|The belief that lightning never strikes the same place twice is pure ______: tall towers are struck many times a year.
feasible|adj|possible to do easily or conveniently|possible, practical, achievable|impossible, impractical|Old French faisable (doable)|With only two days left, finishing the entire mural was no longer ______.
fervent|adj|having or showing intense feeling|passionate, ardent, intense|apathetic, indifferent|Latin fervere (to boil)|{{NAME_1}}'s support for the team was ______: {{NAME_1}} attended every game for ten years.
fickle|adj|changing one's mind or loyalties frequently|changeable, unpredictable, inconstant|loyal, steady|Old English ficol (deceitful)|The ______ weather switched from sunshine to hail and back again in a single afternoon.
fluctuate|v|to rise and fall irregularly|vary, change, swing|stabilize, remain|Latin fluctus (wave)|Gas prices can ______ wildly, rising one week and falling the next.
formidable|adj|inspiring fear or respect because of size or power|intimidating, daunting, powerful|weak, feeble|Latin formido (fear)|The defending champions were ______ opponents who had not lost in three seasons.
fortify|v|to strengthen or protect|strengthen, reinforce, secure|weaken, undermine|Latin fortis (strong)|Villagers worked through the night to ______ the riverbank with sandbags before the flood.
fortuitous|adj|happening by lucky chance|lucky, accidental, chance|planned, intentional|Latin fors (chance)|Their meeting was ______: both happened to miss the same train and ended up talking for hours.
frugal|adj|careful about spending money; thrifty|thrifty, economical, careful|wasteful, extravagant|Latin frugalis (useful, virtuous)|By being ______ for a year, {{NAME_1}} saved enough to pay for a trip abroad.
dispel|v|to make a feeling or belief disappear|banish, dismiss, eliminate|create, encourage|Latin dis- (apart) + pellere (to drive)|The scientist's clear explanation helped ______ the rumor that the water was unsafe to drink.
exuberant|adj|full of energy, excitement, and cheerfulness|enthusiastic, lively, high-spirited|subdued, gloomy|Latin exuberare (to be abundant)|The ______ fans danced in the streets for hours after the team won the title.
flourish|v|to grow or develop in a healthy, successful way|thrive, prosper, bloom|wither, decline|Latin florere (to bloom)|With enough sunlight and water, the tomato plants began to ______ in the backyard garden.
futile|adj|having no useful result; pointless|pointless, useless, vain|fruitful, effective|Latin futilis (leaky)|It was ______ to keep shouting; the wind carried every word away.
`);
